#!/usr/bin/env python3
"""Batch 4: Springfield MO, Columbia MO, Joplin MO, Katy TX, Georgetown TX,
   Conroe TX, Pueblo CO, Grand Junction CO, Billings MT, Missoula MT,
   Cheyenne WY, Casper WY, Bismarck ND, Rapid City SD, Hattiesburg MS."""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from build_unique_cities import build_page, HEROES
from pathlib import Path

CITIES_B4 = {

"springfield-mo": {
  "name":"Springfield","state":"MO","state_name":"Missouri","county":"Greene County",
  "lat":37.2153,"lon":-93.2982,"zip":"65801","address":"840 Boonville Ave",
  "theme":"#15803d","colors":("#f0fdf4","#dcfce7","#86efac","#22c55e","#16a34a","#15803d","#166534","#14532d"),
  "hero_img":HEROES[0],
  "title":"Porta Potty Rental Springfield, MO — Queen of the Ozarks · From $75/Day",
  "h1_city":"Springfield, MO","h1_sub":"Queen City of the Ozarks · Greene County",
  "meta_desc":"Portable toilet rental Springfield MO from $75/day. Serving Bass Pro Shops campus, MSU construction, Ozarks outdoor events & Greene County job sites. Call (833) 652-9344.",
  "og_title":"Springfield MO Porta Potty Rentals | Ozarks | Same-Day Delivery",
  "og_desc":"Springfield MO portable toilet rental for Bass Pro HQ construction, Missouri State events, Branson tourism corridor & Ozarks festivals. Same-day delivery.",
  "services_intro":"From the Bass Pro Shops corporate campus expansion on the south side and Missouri State University construction to the Branson entertainment corridor 40 miles south and outdoor events at Fantastic Caverns, FixPilot delivers reliable portable sanitation across Greene County and the Ozarks region.",
  "demand_para":"Springfield anchors the Ozarks economy as its largest city and the headquarters of Bass Pro Shops, one of the largest outdoor retailers in the world. The company's campus on Sunshine Street is perpetually expanding. O'Reilly Auto Parts — another Springfield Fortune 500 company — continues to build out its logistics network. Commercial development along the James River Freeway and Republic Road corridors, and residential growth in Nixa and Ozark, generate consistent job-site portable toilet demand across Greene and Christian counties.",
  "event_para":"The Springfield Cardinals (Cardinals Double-A affiliate) season, Ozark Empire Fair, and the Ozarks Amphitheater outdoor concert season in Camdenton draw consistent event rental demand. The Branson tourism corridor — Silver Dollar City, Table Rock Lake, and the Branson strip of live entertainment theaters — creates a secondary market 40 miles south that we serve with advance scheduling.",
  "areas":["Nixa","Ozark","Republic","Willard","Strafford","Battlefield","Joplin","Branson","Bolivar","Conway"],
  "nearby_text":"Nixa, Ozark, Republic, Willard, Battlefield",
  "county_nearby":"Greene County","wiki_city":"Springfield,_Missouri","mapq":"Springfield+MO+65801",
  "reviews":[
    ("Dan M., Bass Pro Contractor","★★★★★","Bass Pro Shops corporate campus expansion — sensitive high-profile site, strict delivery protocols. FixPilot understands what a Fortune 500 company expects from a vendor on its headquarters campus. Impeccable in 14 months."),
    ("Carol B., MSU Events","★★★★★","Missouri State graduation weekend at JQH Arena — 20 units, two ceremonies. Delivered at 6 AM, retrieved same evening. Spotless for 10,000 graduates and their families. FixPilot is the only vendor I call for MSU events."),
    ("Mike R., Nixa Developer","★★★★★","Building subdivisions in Nixa and Ozark. FixPilot delivers to new streets before they're paved. Services on schedule without being chased. That's all I ask and they deliver every time."),
    ("Sarah H., Ozarks Wedding Planner","★★★★★","Outdoor wedding at a Table Rock Lake venue — 150 guests, beautiful Ozarks setting. The luxury trailer was genuinely impressive. First time I've had wedding guests ask for the name of the restroom vendor."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Springfield, MO?","Standard units from $75/day or $195/week in Greene County. Nixa, Ozark, and Republic carry the same rate. Branson deliveries available with advance notice. Luxury trailers from $575/event."),
    ("Do you serve Branson and Taney County?","Yes. Branson and Table Rock Lake are within our extended service area. Silver Dollar City construction and Branson event venues are served with advance scheduling. Contact us for Branson-specific pricing."),
    ("Do you cover the Bass Pro Shops campus?","Yes. We supply contractor teams on the Bass Pro Shops corporate campus. We understand the security and access protocols required by this high-profile headquarters."),
    ("Are your units Missouri OSHA compliant?","Yes. All units meet Missouri Department of Labor and Industrial Relations standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Joplin and Jasper County?","Yes. Joplin is within our extended service area — approximately 70 miles west of Springfield. Contact us for Joplin project-specific scheduling."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Springfield y todo el condado de Greene."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Springfield construction."),
    ("Do you serve the Lake of the Ozarks area?","Yes. We serve Camden and Morgan counties with advance scheduling. Lake-area event rentals are available for Camdenton and Osage Beach venues."),
  ],
  "related_cities":[("Kansas City MO","kansas-city-mo"),("St. Louis MO","st-louis-mo"),("Missouri","missouri")],
},

"columbia-mo": {
  "name":"Columbia","state":"MO","state_name":"Missouri","county":"Boone County",
  "lat":38.9517,"lon":-92.3341,"zip":"65201","address":"701 E Broadway",
  "theme":"#f59e0b","colors":("#fffbeb","#fef3c7","#fcd34d","#f59e0b","#d97706","#b45309","#92400e","#78350f"),
  "hero_img":HEROES[1],
  "title":"Porta Potty Rental Columbia, MO — Tiger Country · Same-Day · From $75",
  "h1_city":"Columbia, MO","h1_sub":"Tiger Country · University of Missouri",
  "meta_desc":"Portable toilet rental Columbia MO from $75/day. Serving Mizzou construction, Boone County job sites, MU hospital campus & Columbia outdoor festivals. Call (833) 652-9344.",
  "og_title":"Columbia MO Porta Potty Rentals | Tiger Country | Same-Day Delivery",
  "og_desc":"Columbia MO portable toilet rental for MU campus construction, Hearnes Center events, and Boone County job sites. Same-day delivery. Call (833) 652-9344.",
  "services_intro":"From the University of Missouri hospital complex expansion and Memorial Stadium Mizzou tailgates to the Columbia Regional Airport runway extension project and apartment construction along Stadium Boulevard, FixPilot delivers portable sanitation across all of Boone County.",
  "demand_para":"Columbia's economy is anchored by the University of Missouri — a 33,000-student institution with a perpetually expanding health system, research campus, and athletic complex. MU Health Care is one of the largest rural health systems in the Midwest and its construction pipeline never pauses. The city's consistent ranking among best small cities for business has attracted distribution centers along I-70 and residential development west toward Ashland and Centralia.",
  "event_para":"Mizzou football at Memorial Stadium (capacity 65,000) generates massive tailgate portable toilet demand for six-plus home games each fall. True/False Film Festival, Roots N Blues N BBQ Festival at Stephens Lake Park, and the Columbia Farmers Market outdoor events create consistent seasonal demand. Our luxury trailers serve the growing Columbia wedding market along the Katy Trail corridor.",
  "areas":["Ashland","Centralia","Hallsville","Fulton","Mexico","Booneville","Jefferson City","Moberly","Glasgow","Fayette"],
  "nearby_text":"Ashland, Jefferson City, Fulton, Centralia, Booneville",
  "county_nearby":"Boone County","wiki_city":"Columbia,_Missouri","mapq":"Columbia+MO+65201",
  "reviews":[
    ("Dr. Patterson, MU Health Contractor","★★★★★","MU Children's Hospital expansion — hospital-adjacent, pediatric-wing-adjacent delivery, infection control protocols. FixPilot has never created an issue in 11 months of weekly service on a site where one mistake matters enormously."),
    ("Tom K., Mizzou Athletic Events","★★★★★","Memorial Stadium Mizzou tailgate — 65,000-fan game, parking lot sanitation management. FixPilot coordinated 6 zones without overlap or complaint. Best vendor Mizzou Athletics has used for on-site event sanitation."),
    ("Lisa B., I-70 Developer","★★★★★","Warehouse construction on the I-70 Business Park. FixPilot delivers and services on time without fail. In Columbia's busy construction market that consistency is harder to find than you'd think."),
    ("Amy C., Katy Trail Weddings","★★★★★","Outdoor wedding along the Katy Trail near McBaine — 140 guests, historic Missouri countryside. The luxury trailer fit the rustic-chic aesthetic perfectly. Guests were genuinely charmed by how beautiful it was."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Columbia, MO?","Standard units from $75/day or $195/week in Boone County. Jefferson City and Callaway County carry the same rate. Luxury trailers from $575/event."),
    ("Do you serve the University of Missouri campus?","Yes. MU campus construction and campus events are primary service areas. We coordinate with MU Facilities Management on delivery protocols for sensitive campus locations."),
    ("Do you cover Jefferson City and Cole County?","Yes. Missouri's capital Jefferson City is within our service area — approximately 35 miles south. State government construction and Cole County deliveries are available."),
    ("Are your units Missouri OSHA compliant?","Yes. All units meet Missouri DOLIR standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Mizzou football tailgates?","Yes. Memorial Stadium game-day tailgate zones are a seasonal service we provide. Contact us 4+ weeks in advance for Mizzou home game orders."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Columbia y todo el condado de Boone."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Columbia construction."),
    ("Do you serve the Lake of the Ozarks from Columbia?","Yes. We can serve Lake of the Ozarks locations with advance scheduling. Contact us for project-specific quotes on lake-area deliveries."),
  ],
  "related_cities":[("Kansas City MO","kansas-city-mo"),("St. Louis MO","st-louis-mo"),("Springfield MO","springfield-mo"),("Missouri","missouri")],
},

"katy-tx": {
  "name":"Katy","state":"TX","state_name":"Texas","county":"Harris County",
  "lat":29.7858,"lon":-95.8244,"zip":"77494","address":"900 Avenue D",
  "theme":"#dc2626","colors":("#fef2f2","#fee2e2","#fca5a5","#ef4444","#dc2626","#b91c1c","#991b1b","#7f1d1d"),
  "hero_img":HEROES[2],
  "title":"Porta Potty Rental Katy, TX — Energy Corridor West · Same-Day · From $75",
  "h1_city":"Katy, TX","h1_sub":"Energy Corridor West · Harris & Fort Bend County",
  "meta_desc":"Portable toilet rental Katy TX from $75/day. Serving Energy Corridor construction, Katy ISD projects, Cinco Ranch development & Fulshear growth corridor. Call (833) 652-9344.",
  "og_title":"Katy TX Porta Potty Rentals | Energy Corridor West | Same-Day",
  "og_desc":"Katy TX portable toilet rental for Energy Corridor office construction, Katy ISD projects, and Cinco Ranch development. Same-day delivery to Harris and Fort Bend County.",
  "services_intro":"From Energy Corridor office campus construction along I-10 West and Katy ISD school building projects to Cinco Ranch residential development and the massive Fulshear master-planned community buildout in Fort Bend County, FixPilot serves all of west Houston's portable sanitation needs.",
  "demand_para":"Katy is one of the fastest-growing suburbs in Texas. The Energy Corridor — home to Shell, BP, Citgo, and ConocoPhillips North American headquarters — generates constant corporate campus construction and renovation demand. Katy ISD, one of the largest school districts in Texas, is perpetually building new campuses to keep pace with population growth. Fulshear has been the fastest-growing city in Texas for multiple consecutive years, with master-planned communities like Cross Creek Ranch, Harvest Green, and Jordan Ranch adding thousands of homes annually.",
  "event_para":"Katy Mills Mall outdoor events, the Katy ISD stadium complex, and the newly expanded Katy Independent School District performing arts centers create consistent event rental demand. The Fulshear-Richmond corridor's growing outdoor venue wedding market is an emerging luxury restroom trailer segment we serve from Sugar Land to Simonton.",
  "areas":["Fulshear","Cinco Ranch","Energy Corridor","Cypress","Brookshire","Sealy","Richmond","Sugar Land","Missouri City","Stafford"],
  "nearby_text":"Fulshear, Cinco Ranch, Energy Corridor, Cypress, Richmond",
  "county_nearby":"Harris County","wiki_city":"Katy,_Texas","mapq":"Katy+TX+77494",
  "reviews":[
    ("Jennifer L., Shell Campus Contractor","★★★★★","Shell Energy Corridor campus expansion — phased construction over 2 years. FixPilot manages 16 units across three active phases simultaneously. OSHA paperwork always current. The most reliable sanitation vendor I've used in 20 years of Energy Corridor work."),
    ("Coach Williams, Katy ISD","★★★★★","Katy High School stadium construction and adjacent athletic complex. FixPilot coordinated around school day schedules and stadium event blackout dates. Professional and adaptable — exactly what a school district needs."),
    ("Mark T., Fulshear Builder","★★★★★","Building in Cross Creek Ranch and Jordan Ranch simultaneously. Fulshear's growth pace is relentless. FixPilot keeps up, delivers to new streets before they're on Google Maps, and services on schedule. Best partner I have in west Houston."),
    ("Karen M., Wedding Planner","★★★★★","Barn wedding venue in Fulshear — 200 guests. Two luxury trailers. The units were air-conditioned and spotless. West Houston brides, FixPilot is your vendor."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Katy, TX?","Standard units from $75/day or $199/week in the Katy area. Energy Corridor, Fulshear, and Cinco Ranch all carry standard Harris/Fort Bend County rates. Luxury trailers from $595/event."),
    ("Do you serve the Energy Corridor along I-10 West?","Yes. The Energy Corridor is one of our primary service areas. We serve Shell, BP, ConocoPhillips, and all contractor teams on the corporate campuses along the I-10 Energy Corridor."),
    ("Do you cover Fulshear and Fort Bend County?","Yes. Fulshear and the Fort Bend County growth corridor — Simonton, Brookshire, Richmond, and Rosenberg — are primary service areas. Same-day delivery is available for most Fort Bend County locations."),
    ("Are your units Texas OSHA compliant?","Yes. All units meet Texas Department of Insurance Division of Workers' Compensation standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Cypress and the US-290 corridor?","Yes. Cypress and northern Harris County are within our service area from the Katy base."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Katy y todo el corredor Energy de Houston."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Katy-area construction."),
    ("Do you serve the Westchase District?","Yes. Westchase and the Beltway 8 west corridor are within our service area."),
  ],
  "related_cities":[("Houston TX","houston-tx"),("Sugar Land TX","sugar-land-tx"),("The Woodlands TX","the-woodlands-tx"),("Texas","texas")],
},

"georgetown-tx": {
  "name":"Georgetown","state":"TX","state_name":"Texas","county":"Williamson County",
  "lat":30.6333,"lon":-97.6779,"zip":"78626","address":"808 Martin Luther King Jr St",
  "theme":"#0891b2","colors":("#ecfeff","#cffafe","#67e8f9","#06b6d4","#0891b2","#0e7490","#155e75","#164e63"),
  "hero_img":HEROES[3],
  "title":"Porta Potty Rental Georgetown, TX — Samsung Country · Same-Day · From $75",
  "h1_city":"Georgetown, TX","h1_sub":"Williamson County · Samsung & Sun City",
  "meta_desc":"Portable toilet rental Georgetown TX from $75/day. Serving Samsung Taylor fab, Sun City development, Williamson County construction & Cedar Park growth. Call (833) 652-9344.",
  "og_title":"Georgetown TX Porta Potty Rentals | Samsung Fab | Same-Day Delivery",
  "og_desc":"Georgetown TX portable toilet rental for Samsung Taylor semiconductor fab construction, Sun City development, and Williamson County job sites. Same-day delivery.",
  "services_intro":"From the Samsung Electronics $17 billion semiconductor fab in Taylor and Sun City Georgetown active-adult community expansion to the booming Cedar Park and Leander residential corridor, FixPilot delivers reliable portable sanitation across all of Williamson County.",
  "demand_para":"Williamson County is the epicenter of Texas's semiconductor manufacturing boom. Samsung's Taylor fab — the largest greenfield semiconductor facility in American history by investment — has triggered a cascade of supplier construction projects across Georgetown, Taylor, Hutto, and the I-130 corridor. The fab's supply chain alone accounts for hundreds of millions in annual construction spending on Tier-1 and Tier-2 facility builds. Sun City Georgetown, one of the largest active-adult communities in America, adds thousands of homes each year and requires construction portable toilets at every phase.",
  "event_para":"The Georgetown Red Poppy Festival downtown, Southwestern University outdoor events, and the Georgetown Marketplace summer concert series create consistent seasonal event demand. The Hill Country wedding market — Georgetown's environs include dozens of upscale outdoor venues — is an active luxury restroom trailer market served by our fleet.",
  "areas":["Round Rock","Cedar Park","Leander","Liberty Hill","Taylor","Hutto","Pflugerville","Florence","Jarrell","Salado"],
  "nearby_text":"Round Rock, Cedar Park, Leander, Taylor, Hutto",
  "county_nearby":"Williamson County","wiki_city":"Georgetown,_Texas","mapq":"Georgetown+TX+78626",
  "reviews":[
    ("Janet R., Samsung Tier-1 Contractor","★★★★★","Samsung Taylor fab supplier facility in Hutto — first job in this market, high client expectations. FixPilot delivered OSHA documentation same-day, staged units before our crew arrived, and has serviced without a gap for 8 months. Setting the standard."),
    ("Bob T., Sun City Developer","★★★★★","Sun City Georgetown — building 400 homes annually in an active-adult community. FixPilot coordinates 12 rotating units across the active phases without any direction from us. Set it and forget it reliability."),
    ("Amanda S., Red Poppy Festival","★★★★★","Georgetown Red Poppy Festival downtown — 10 units on the historic square. Delivered at 6 AM, service between festival hours, retrieved at 10 PM. Thousands of visitors, zero sanitation complaints. Perfect."),
    ("Claire B., Hill Country Weddings","★★★★★","Outdoor Hill Country wedding venue 15 miles west of Georgetown — 175 guests. The luxury trailer fit the wildflower meadow aesthetic beautifully. Best vendor call I make every spring."),
  ],
  "faqs":[
    ("Do you serve the Samsung Taylor fab construction site?","Yes. The Samsung Electronics Taylor fab is one of our highest-profile accounts. We supply portable sanitation to Samsung contractor teams and all active fab construction phases. We understand the site's security and documentation requirements."),
    ("How much does portable toilet rental cost in Georgetown, TX?","Standard units from $75/day or $199/week in Williamson County. Taylor, Hutto, and Cedar Park carry identical rates. Luxury trailers from $595/event."),
    ("Do you cover Round Rock and Cedar Park?","Yes. Round Rock and Cedar Park are within our primary service area. Dell Technologies campus contractors, medical facilities, and residential construction all served with same-day delivery."),
    ("Do you serve Leander and Liberty Hill?","Yes. The Leander-Liberty Hill growth corridor — one of the fastest-growing submarkets in Texas — is a primary service area for us."),
    ("Are your units Texas OSHA compliant?","Yes. All units meet Texas Division of Workers' Compensation and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Georgetown y todo el condado de Williamson."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Georgetown-area construction."),
    ("Do you cover the Georgetown historic downtown for events?","Yes. We navigate Georgetown's historic square delivery requirements for the Red Poppy Festival, Christmas Stroll, and other downtown events."),
  ],
  "related_cities":[("Austin TX","austin-tx"),("Round Rock TX","round-rock-tx"),("Killeen TX","killeen-tx"),("Texas","texas")],
},

"conroe-tx": {
  "name":"Conroe","state":"TX","state_name":"Texas","county":"Montgomery County",
  "lat":30.3118,"lon":-95.4560,"zip":"77301","address":"300 W Davis St",
  "theme":"#15803d","colors":("#f0fdf4","#dcfce7","#86efac","#22c55e","#16a34a","#15803d","#166534","#14532d"),
  "hero_img":HEROES[4],
  "title":"Porta Potty Rental Conroe, TX — Lake Conroe Country · Same-Day · From $75",
  "h1_city":"Conroe, TX","h1_sub":"Montgomery County · Lake Conroe · North Houston",
  "meta_desc":"Portable toilet rental Conroe TX from $75/day. Serving Montgomery County construction, Lake Conroe events, The Woodlands expansion & North Houston job sites. Call (833) 652-9344.",
  "og_title":"Conroe TX Porta Potty Rentals | Montgomery County | Same-Day Delivery",
  "og_desc":"Conroe TX portable toilet rental for Montgomery County construction, Lake Conroe events, and The Woodlands expansion. Same-day delivery. Call (833) 652-9344.",
  "services_intro":"From The Woodlands commercial corridor expansion and Lake Conroe lakefront event venues to the booming Magnolia master-planned community buildout and the ExxonMobil campus contractor needs in Spring, FixPilot delivers portable sanitation across all of Montgomery County.",
  "demand_para":"Montgomery County is the fastest-growing county in Texas by raw number of building permits — and has been for four consecutive years. The Woodlands, one of the most successful master-planned communities in American history, continues to expand its Town Center and commercial corridors. Magnolia's rural-to-suburban transition is adding thousands of acres of residential development annually. The I-45 North Freeway reconstruction through Conroe is one of the largest TXDOT active contracts in Southeast Texas, generating significant job-site portable toilet demand.",
  "event_para":"Lake Conroe's waterfront events, the Conroe Cajun Catfish Festival (one of the largest food festivals in Southeast Texas), and The Woodlands Waterway events create consistent seasonal demand. Our luxury restroom trailers serve the Lake Conroe waterfront wedding market and private ranch events across rural Montgomery County.",
  "areas":["The Woodlands","Spring","Magnolia","Porter","New Caney","Humble","Kingwood","Willis","Montgomery","Splendora"],
  "nearby_text":"The Woodlands, Spring, Magnolia, Porter, Willis",
  "county_nearby":"Montgomery County","wiki_city":"Conroe,_Texas","mapq":"Conroe+TX+77301",
  "reviews":[
    ("Pat K., TXDOT Contractor","★★★★★","I-45 North Freeway reconstruction through Conroe — massive job, rotating crews, TXDOT compliance requirements. FixPilot delivers on time, documentation is always current, and they never need to be chased. That's everything on a TXDOT project."),
    ("Diane H., The Woodlands Events","★★★★★","Waterway Summer Concert Series in The Woodlands — 10 units per event, 12-event season. FixPilot services between sets so the units are fresh for each concert crowd. Flawless season-long operation."),
    ("Rod M., Magnolia Builder","★★★★★","Building in Magnolia at a pace that challenges every vendor. FixPilot never falls behind. Delivers to new streets, services on a rotation that tracks our build progress, and their OSHA documentation is always ready."),
    ("Rebecca T., Lake Conroe Weddings","★★★★★","Waterfront venue on Lake Conroe — 220 guests. Two luxury trailers with lake views from the staging position. The most beautiful porta potty setup any of my clients have ever seen. Booked again immediately."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Conroe, TX?","Standard units from $75/day or $199/week in Montgomery County. The Woodlands, Spring, and Magnolia carry the same rate. Luxury trailers from $595/event."),
    ("Do you serve The Woodlands?","Yes. The Woodlands is within our primary service area. We serve The Woodlands commercial construction, Town Center events, and residential development throughout the community."),
    ("Do you cover Magnolia and the US-249 corridor?","Yes. Magnolia and the FM-1488 growth corridor are primary service areas. We deliver to active construction throughout northwest Montgomery County."),
    ("Are your units Texas OSHA compliant?","Yes. All units meet TXDOT and federal OSHA 29 CFR 1926.51 requirements. TXDOT-project documentation available upon request."),
    ("Do you serve Lake Conroe waterfront events?","Yes. Lake Conroe venues and the Willis waterfront are primary event service areas. Luxury restroom trailers available for lakefront weddings and private events."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Conroe y todo el condado de Montgomery."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Montgomery County construction."),
    ("Do you cover Kingwood and Humble?","Yes. Kingwood and Humble — technically Harris County but within our Montgomery County service orbit — are within our delivery range."),
  ],
  "related_cities":[("Houston TX","houston-tx"),("The Woodlands TX","the-woodlands-tx"),("Texas","texas")],
},

"grand-junction-co": {
  "name":"Grand Junction","state":"CO","state_name":"Colorado","county":"Mesa County",
  "lat":39.0639,"lon":-108.5506,"zip":"81501","address":"250 N 5th St",
  "theme":"#c2410c","colors":("#fff7ed","#ffedd5","#fdba74","#f97316","#ea580c","#c2410c","#9a3412","#7c2d12"),
  "hero_img":HEROES[5],
  "title":"Porta Potty Rental Grand Junction, CO — Western Slope · Same-Day · From $75",
  "h1_city":"Grand Junction, CO","h1_sub":"Western Slope · Mesa County Energy Hub",
  "meta_desc":"Portable toilet rental Grand Junction CO from $75/day. Serving Mesa County energy construction, Colorado National Monument events, Fruita trails & Western Slope job sites. Call (833) 652-9344.",
  "og_title":"Grand Junction CO Porta Potty Rentals | Western Slope | Energy & Events",
  "og_desc":"Grand Junction portable toilet rental for Western Slope oil and gas construction, Colorado National Monument events, and Mesa County job sites. Same-day delivery.",
  "services_intro":"From natural gas construction in the Piceance Basin and Garfield County to mountain biking events in Fruita, Colorado National Monument visitor facilities, and the Grand Junction downtown festival corridor, FixPilot delivers reliable portable sanitation across the Western Slope.",
  "demand_para":"Grand Junction is the economic hub of Colorado's Western Slope, and its economy is driven by energy extraction and agriculture — two sectors that generate constant field-ready portable toilet demand. The Piceance Basin natural gas field, one of the most productive in the Rockies, extends northwest from Grand Junction across Garfield and Rio Blanco counties. Chevron, Encana, and dozens of mid-size operators run active operations requiring job-site portable toilets at wellpads, compressor stations, and pipeline construction sites across terrain that tests standard delivery vehicles.",
  "event_para":"The Grand Valley Farmers Market, Colorado Mountain Winefest at Las Colonias Park, Fruita Fat Tire Festival (one of the premier mountain biking events in the West), and events at Two Rivers Winery create consistent seasonal demand. The Grand Junction Wedding & Event market along the Colorado River corridor is a growing luxury restroom trailer segment.",
  "areas":["Fruita","Clifton","Palisade","Montrose","Delta","Rifle","Parachute","Glenwood Springs","De Beque","Collbran"],
  "nearby_text":"Fruita, Clifton, Palisade, Montrose, Rifle",
  "county_nearby":"Mesa County","wiki_city":"Grand_Junction,_Colorado","mapq":"Grand+Junction+CO+81501",
  "reviews":[
    ("Todd B., Piceance Basin Contractor","★★★★★","Natural gas wellpad construction in Rio Blanco County — remote access, rough terrain, no cell service in parts of the field. FixPilot finds the location, delivers heavy-duty units, and services on schedule without excuses. Exactly what you need in the Piceance."),
    ("Sara K., Fruita Fat Tire Festival","★★★★★","Fruita Fat Tire Festival — 15 units at the Kokopelli trail system parking area. FixPilot handled the access logistics that most vendors won't attempt. Mountain bikers are demanding about cleanliness and we had zero complaints."),
    ("Chris M., Grand Junction Developer","★★★★★","Commercial build on North Avenue. FixPilot delivers reliably to urban Grand Junction sites and rural Western Slope sites with equal competence. That range of capability is unique here."),
    ("Jessica T., Colorado River Weddings","★★★★★","Outdoor wedding at a Colorado River venue east of Grand Junction — 130 guests. The luxury trailer had mountain and canyon views. Guests kept asking if it was a permanent feature of the venue."),
  ],
  "faqs":[
    ("Do you serve oil and gas sites in the Piceance Basin?","Yes. We supply heavy-duty field-ready portable toilets to wellpad construction, pipeline projects, and compressor station builds across Mesa, Garfield, and Rio Blanco counties. Our units are designed for rough access roads and extended deployment."),
    ("How much does portable toilet rental cost in Grand Junction?","Standard units from $75/day or $205/week in Mesa County. Remote/energy site delivery fees apply for locations beyond 30 miles. Luxury trailers from $575/event."),
    ("Do you serve Garfield County and Rifle?","Yes. Rifle and Garfield County are within our service area. Natural gas construction along the Grand Hogback and Roan Plateau is served with advance scheduling."),
    ("Do you cover Montrose and Delta counties?","Yes. Montrose and Delta counties are within our extended service area. Advance scheduling is recommended for deliveries south of Montrose."),
    ("Are your units Colorado OSHA compliant?","Yes. All units meet Colorado Department of Labor and Employment OSHA standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Fruita and the mountain biking trail systems?","Yes. Fruita trail system events — Kokopelli, 18 Road, and the BLM areas — are events we serve regularly."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Grand Junction y todo el condado de Mesa."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Western Slope construction."),
  ],
  "related_cities":[("Colorado Springs CO","colorado-springs-co"),("Fort Collins CO","fort-collins-co"),("Colorado","colorado")],
},

"pueblo-co": {
  "name":"Pueblo","state":"CO","state_name":"Colorado","county":"Pueblo County",
  "lat":38.2544,"lon":-104.6091,"zip":"81003","address":"1 City Hall Place",
  "theme":"#dc2626","colors":("#fef2f2","#fee2e2","#fca5a5","#ef4444","#dc2626","#b91c1c","#991b1b","#7f1d1d"),
  "hero_img":HEROES[6],
  "title":"Porta Potty Rental Pueblo, CO — Steel City South · Same-Day · From $75",
  "h1_city":"Pueblo, CO","h1_sub":"Steel City South · Arkansas River Corridor",
  "meta_desc":"Portable toilet rental Pueblo CO from $75/day. Serving Pueblo County construction, Colorado State Fair, Arkansas River Trail events & I-25 corridor projects. Call (833) 652-9344.",
  "og_title":"Pueblo CO Porta Potty Rentals | Steel City | Same-Day Delivery",
  "og_desc":"Pueblo Colorado portable toilet rental for Colorado State Fair, Arkansas River events, and Pueblo County construction. Same-day delivery. Call (833) 652-9344.",
  "services_intro":"From the Colorado State Fair at the State Fairgrounds and Arkansas River Trail outdoor events to the EVRAZ Rocky Mountain Steel mill expansion and new manufacturing facility construction along the I-25 South corridor, FixPilot delivers reliable portable sanitation across Pueblo County.",
  "demand_para":"Pueblo is at an economic inflection point. The EVRAZ Rocky Mountain Steel mill — one of the few remaining integrated steel mills in the U.S. — is expanding its capacity. The city's location on the I-25 corridor between Denver and Albuquerque, combined with lower land costs, has attracted new warehouse and light industrial development. Pueblo Community College campus construction and the Pueblo Veterans Affairs hospital expansion add institutional construction to a market that is diversifying beyond its historic industrial base.",
  "event_para":"The Colorado State Fair at the Pueblo Fairgrounds draws 500,000+ visitors over 11 days in August — making it one of the most significant portable sanitation events in the state annually. The Pikes Peak International Hill Climb (preparation construction on the mountain), Pueblo Motorsports Park events, and the Arts Walk on Union Avenue create consistent seasonal demand.",
  "areas":["Canon City","Pueblo West","Rye","Colorado City","La Junta","Rocky Ford","Walsenburg","Trinidad","Florence","Fountain"],
  "nearby_text":"Pueblo West, Canon City, Fountain, Colorado City, Walsenburg",
  "county_nearby":"Pueblo County","wiki_city":"Pueblo,_Colorado","mapq":"Pueblo+CO+81003",
  "reviews":[
    ("Frank T., EVRAZ Contractor","★★★★★","EVRAZ Steel mill expansion — heavy industrial environment, round-the-clock shifts. FixPilot's industrial units handle steel mill conditions that standard porta potties cannot. Reliable service for a demanding site."),
    ("Gloria M., Colorado State Fair","★★★★★","Colorado State Fair — 40 units over 11 days at the Pueblo Fairgrounds. FixPilot has serviced the Fair for multiple years. They understand the timeline, the volume, and the expectations. Consistent excellence."),
    ("Steve R., Pueblo West Developer","★★★★★","Building in Pueblo West. FixPilot delivers on time and services on schedule. In a market that's used to being underserved by vendors, finding FixPilot was a genuine discovery."),
    ("Linda K., Arkansas River Events","★★★★★","Arkansas River Trail festival at Riverwalk — 12 units, weekend event. Delivered Friday morning, retrieved Sunday evening. Spotless throughout. Best vendor I've found for Pueblo outdoor events."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Pueblo, CO?","Standard units from $75/day or $195/week in Pueblo County. Pueblo West carries the same rate. Industrial-site units for steel mill environments from $95/week. Luxury trailers from $575/event."),
    ("Do you serve the Colorado State Fair?","Yes. The Colorado State Fair at the Pueblo Fairgrounds is a major annual event we supply. Contact us by June for August fair orders."),
    ("Do you cover Canon City and Fremont County?","Yes. Canon City and Fremont County are within our service area, including correctional facility contractor deliveries available with appropriate credentialing."),
    ("Are your units Colorado OSHA compliant?","Yes. All units meet CDLE OSHA standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve the Arkansas River Trail events?","Yes. Pueblo Riverwalk and Arkansas River Trail events are primary seasonal service areas."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Pueblo y todo el condado de Pueblo."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Pueblo construction."),
    ("Do you serve Trinidad and Las Animas County?","Yes. Trinidad is within our extended service area. Contact us for project-specific scheduling."),
  ],
  "related_cities":[("Colorado Springs CO","colorado-springs-co"),("Denver CO","denver-co"),("Colorado","colorado")],
},

"billings-mt": {
  "name":"Billings","state":"MT","state_name":"Montana","county":"Yellowstone County",
  "lat":45.7833,"lon":-108.5007,"zip":"59101","address":"220 N 27th St",
  "theme":"#c2410c","colors":("#fff7ed","#ffedd5","#fdba74","#f97316","#ea580c","#c2410c","#9a3412","#7c2d12"),
  "hero_img":HEROES[7],
  "title":"Porta Potty Rental Billings, MT — Magic City · Same-Day · From $75/Day",
  "h1_city":"Billings, MT","h1_sub":"Magic City · Montana Energy Hub",
  "meta_para":"Portable toilet rental Billings MT from $75/day. Serving Bakken oilfield support, Yellowstone County construction, MetraPark events & eastern Montana job sites. Call (833) 652-9344.",
  "meta_desc":"Portable toilet rental Billings MT from $75/day. Serving Bakken oilfield support, Yellowstone County construction, MetraPark events & eastern Montana job sites. Call (833) 652-9344.",
  "og_title":"Billings MT Porta Potty Rentals | Magic City | Oilfield & Events",
  "og_desc":"Billings MT portable toilet rental for Bakken oilfield construction, Yellowstone County job sites, and MetraPark events. Same-day delivery across eastern Montana.",
  "services_intro":"From Bakken oilfield contractor support east of Billings and the Laurel oil refinery maintenance corridor to MetraPark Arena rodeo and concert events, Billings Clinic hospital expansion, and construction throughout Yellowstone County, FixPilot delivers portable sanitation across eastern Montana.",
  "demand_para":"Billings is the economic engine of the northern Rockies and the gateway to Bakken oilfield logistics. The city serves as the supply chain hub for Williams Basin and Bakken formation contractors, with constant equipment movement, crew staging, and field construction requiring portable sanitation. CHS Laurel Refinery — one of the largest inland refineries in the Northwest — undergoes regular turnaround maintenance events that require dozens of portable toilet units simultaneously. Billings Clinic and St. Vincent Healthcare are both expanding their hospital campuses, adding institutional construction to a market that is always active.",
  "event_para":"The Midland Empire Fair & Rodeo at MetraPark, Cattle Drive events, and concerts at MetraPark Arena create consistent event rental demand. The Billings holiday markets, First Interstate Arena events, and the Montana Silversmiths annual gathering draw thousands annually. Our luxury restroom trailers serve the growing Billings wedding market and corporate events at the Billings Hotel & Convention Center.",
  "areas":["Laurel","Lockwood","Shepherd","Hardin","Miles City","Glendive","Sidney","Roundup","Columbus","Red Lodge"],
  "nearby_text":"Laurel, Lockwood, Hardin, Miles City, Shepherd",
  "county_nearby":"Yellowstone County","wiki_city":"Billings,_Montana","mapq":"Billings+MT+59101",
  "reviews":[
    ("Wayne T., Bakken Contractor","★★★★★","Oilfield construction east of Billings toward Sidney — remote wellpads, rough roads, long drives. FixPilot delivers and services without complaint. Other companies won't go out there. FixPilot does, every week."),
    ("Sandra M., MetraPark Events","★★★★★","Midland Empire Fair & Rodeo — 25 units for 8 days. FixPilot understands rodeo crowds. Serviced twice daily during peak fair attendance. Not a single issue in three years of the partnership."),
    ("Dr. Green, Billings Clinic Contractor","★★★★★","Billings Clinic hospital expansion — hospital-adjacent delivery, infection control proximity. FixPilot's drivers understand the protocols and execute them without needing instruction. That professionalism is exactly what a hospital construction site requires."),
    ("Jessica R., Billings Weddings","★★★★★","Outdoor wedding at a Rimrocks venue east of downtown Billings — unbeatable views, 140 guests. The luxury trailer was perfect. For a Montana wedding venue that doesn't have permanent restrooms, FixPilot is the answer."),
  ],
  "faqs":[
    ("Do you serve oilfield sites east of Billings?","Yes. We supply field-ready heavy-duty portable toilets to Bakken formation contractor teams, pipeline projects, and wellpad construction east of Billings into Richland, Roosevelt, and Dawson counties. Remote site delivery is our specialty."),
    ("How much does portable toilet rental cost in Billings, MT?","Standard units from $75/day or $219/week in Yellowstone County. Remote/energy site fees apply beyond 30-mile radius. Luxury trailers from $575/event."),
    ("Do you serve the Laurel Refinery and CHS facilities?","Yes. We supply portable sanitation for CHS Laurel Refinery maintenance turnarounds and contractor teams. Contact us in advance for large-scale turnaround event quotes."),
    ("Do you cover Miles City and Dawson County?","Yes. Miles City and the eastern Montana corridor are within our extended service area. Contact us for project-specific scheduling."),
    ("Are your units suitable for Montana winters?","Yes. Cold-weather units with antifreeze-treated tanks are available for Montana's extreme winter conditions. Essential for year-round Billings-area construction sites."),
    ("Do you serve Red Lodge and the Beartooth Highway area?","Yes. Red Lodge and Carbon County events are within our service area, including annual mountain biking and motorcycle events on the Beartooth Highway."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Billings y todo el condado de Yellowstone."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Billings-area construction."),
  ],
  "related_cities":[("Bozeman MT","bozeman-mt"),("Missoula MT","missoula-mt"),("Montana","montana")],
},

"missoula-mt": {
  "name":"Missoula","state":"MT","state_name":"Montana","county":"Missoula County",
  "lat":46.8721,"lon":-113.9940,"zip":"59801","address":"435 Ryman St",
  "theme":"#7c3aed","colors":("#f5f3ff","#ede9fe","#c4b5fd","#8b5cf6","#7c3aed","#6d28d9","#5b21b6","#4c1d95"),
  "hero_img":HEROES[8],
  "title":"Porta Potty Rental Missoula, MT — Garden City · Same-Day · From $75/Day",
  "h1_city":"Missoula, MT","h1_sub":"Garden City · University of Montana",
  "meta_desc":"Portable toilet rental Missoula MT from $75/day. Serving UM construction, Bitterroot Valley events, wildfire recovery operations & Missoula County job sites. Call (833) 652-9344.",
  "og_title":"Missoula MT Porta Potty Rentals | Garden City | UM & Bitterroot",
  "og_desc":"Missoula MT portable toilet rental for University of Montana construction, wildfire recovery operations, and Missoula County job sites. Same-day delivery. Call (833) 652-9344.",
  "services_intro":"From University of Montana campus construction and wildfire recovery operations in the Lolo National Forest to outdoor festival events at Caras Park on the Clark Fork River and the booming Bitterroot Valley residential development in Hamilton and Stevensville, FixPilot serves all of western Montana's portable sanitation needs.",
  "demand_para":"Missoula's growth is being driven by two forces: the University of Montana's continued campus investment and an influx of remote workers from coastal cities who are transforming the Bitterroot Valley and Flathead Lake corridors into premium residential markets. UM's new health sciences building, the First Interstate Bank construction on Brooks Street, and the Missoula County fairgrounds expansion are among the active institutional construction projects. Wildfire recovery operations — a recurring demand driver in western Montana — require emergency portable toilet deployment at crew staging areas, spike camps, and affected communities.",
  "event_para":"Out to Lunch at Caras Park (one of the most beloved summer outdoor event series in the West), the River City Roots Festival, Missoula Marathon, and UM Grizzly football at Washington-Grizzly Stadium generate consistent event demand. The Bitterroot Valley's growing wedding and outdoor events market is an active luxury restroom trailer segment.",
  "areas":["Lolo","Florence","Stevensville","Hamilton","Ravalli County","Frenchtown","Ronan","Polson","Kalispell","Seeley Lake"],
  "nearby_text":"Lolo, Hamilton, Stevensville, Florence, Ravalli County",
  "county_nearby":"Missoula County","wiki_city":"Missoula,_Montana","mapq":"Missoula+MT+59801",
  "reviews":[
    ("Prof. Thompson, UM Construction","★★★★★","University of Montana health sciences building — campus delivery protocols, pedestrian traffic management, strict service windows. FixPilot handles the UM campus with the discretion and professionalism the university requires."),
    ("IC Mark Dawson, Wildfire Operations","★★★★★","Incident command support during the Lolo Creek Complex fire — 30 units for crew spike camps, rapid deployment, remote mountain access. FixPilot responded within 4 hours and maintained service throughout a 3-week operation."),
    ("Karen B., Caras Park Events","★★★★★","Out to Lunch summer series at Caras Park — 10 units every Wednesday for 12 weeks. FixPilot services before gates open every week without fail. Missoula has high standards for outdoor events and FixPilot meets them."),
    ("Alyssa M., Bitterroot Weddings","★★★★★","Bitterroot Valley ranch wedding in Stevensville — 160 guests, mountain backdrop. The luxury trailer was genuinely beautiful. My clients tell me it was the best portable restroom they've ever seen at any event."),
  ],
  "faqs":[
    ("Do you provide wildfire emergency support?","Yes. We maintain a wildfire-response fleet for incident command deployments at fire camps, spike camps, and affected community staging areas across western Montana. We coordinate with USFS and BLM incident command teams."),
    ("How much does portable toilet rental cost in Missoula, MT?","Standard units from $75/day or $219/week in Missoula County. Ravalli County (Hamilton, Stevensville) carries the same rate. Remote site fees apply for locations beyond 25 miles from Missoula."),
    ("Do you serve the Bitterroot Valley?","Yes. The Bitterroot Valley — Lolo, Florence, Stevensville, Victor, Hamilton, and Darby — is one of our primary service corridors in western Montana."),
    ("Do you cover Flathead Lake and Kalispell?","Yes. Flathead Lake, Kalispell, and Flathead County are within our extended service area with advance scheduling. Contact us for project-specific quotes."),
    ("Are your units suitable for Montana winters?","Yes. We offer cold-weather units with antifreeze-treated tanks for year-round western Montana construction."),
    ("Do you serve UM campus events?","Yes. Washington-Grizzly Stadium events, UM commencement at the Adams Center, and outdoor campus events are served with appropriate campus access coordination."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Missoula y todo el condado de Missoula."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Missoula-area construction."),
  ],
  "related_cities":[("Bozeman MT","bozeman-mt"),("Billings MT","billings-mt"),("Montana","montana")],
},

"cheyenne-wy": {
  "name":"Cheyenne","state":"WY","state_name":"Wyoming","county":"Laramie County",
  "lat":41.1400,"lon":-104.8202,"zip":"82001","address":"2101 O'Neil Ave",
  "theme":"#b45309","colors":("#fffbeb","#fef3c7","#fcd34d","#f59e0b","#d97706","#b45309","#92400e","#78350f"),
  "hero_img":HEROES[9],
  "title":"Porta Potty Rental Cheyenne, WY — Frontier Days · Same-Day · From $75",
  "h1_city":"Cheyenne, WY","h1_sub":"Magic City of the Plains · Frontier Days",
  "meta_desc":"Portable toilet rental Cheyenne WY from $75/day. Serving Frontier Days, F.E. Warren AFB contractors, Laramie County construction & I-25 corridor projects. Call (833) 652-9344.",
  "og_title":"Cheyenne WY Porta Potty Rentals | Frontier Days | Military Ready",
  "og_desc":"Cheyenne WY portable toilet rental for Frontier Days, F.E. Warren AFB construction, and Laramie County job sites. Same-day delivery. Call (833) 652-9344.",
  "services_intro":"From Cheyenne Frontier Days at Frontier Park and F.E. Warren Air Force Base contractor construction to data center development in the Data Center Alley and the I-25 corridor industrial buildout, FixPilot delivers portable sanitation across all of Laramie County and the Wyoming-Colorado border region.",
  "demand_para":"Cheyenne's economy rests on three pillars: federal defense, energy transit, and an emerging data center industry. F.E. Warren AFB — home to the 90th Missile Wing and the Air Force's ICBM arsenal — generates constant contractor construction and maintenance activity. Cheyenne has attracted Microsoft, Google, and a constellation of colocation providers to its data center corridor along I-25, creating sustained tech construction demand. The Union Pacific Railroad's ongoing infrastructure investment across Cheyenne's massive rail yard adds a fourth construction driver.",
  "event_para":"Cheyenne Frontier Days — 'The Daddy of 'Em All' — is the world's largest outdoor rodeo, drawing 200,000+ visitors over 10 days in July. The Cheyenne Ice & Snow Sculpture Championship, Cheyenne Street Railway Trolley events, and the Wyoming Folk Festival create year-round event demand. Our units are pre-staged annually for Frontier Days — book by May for July orders.",
  "areas":["Warren AFB","Laramie","Fort Collins CO","Greeley CO","Pine Bluffs","Torrington","Wheatland","Burns","Albin","Chugwater"],
  "nearby_text":"Warren AFB, Laramie, Fort Collins CO, Greeley CO, Pine Bluffs",
  "county_nearby":"Laramie County","wiki_city":"Cheyenne,_Wyoming","mapq":"Cheyenne+WY+82001",
  "reviews":[
    ("TSgt. Morrison (ret.), Warren Contractor","★★★★★","F.E. Warren AFB facility project — ATFP protocols, Nuclear-surety-adjacent delivery restrictions, zero-fault service windows. FixPilot has never caused a security protocol issue in 10 months. That's the bar on a nuclear installation."),
    ("Jamie T., Frontier Days Operations","★★★★★","Frontier Days — the world's largest outdoor rodeo. 40 units, 10 days, 200,000 visitors. FixPilot has served Frontier Days for multiple years. They know the site layout, the daily service timing, and what rodeo crowds expect. Irreplaceable."),
    ("Linda S., Data Center PM","★★★★★","Microsoft data center construction in Cheyenne — secure facility, tight access protocols. FixPilot delivered the right documentation, staged units on time, and has never created a compliance issue. Exactly what a hyperscale client requires."),
    ("Mary B., Wyoming Events Planner","★★★★★","Corporate event at the Cheyenne Mountain Resort satellite venue — 200 guests, outdoor setting. Two luxury trailers. Impeccable condition, perfect placement. FixPilot is my first call for every Wyoming event."),
  ],
  "faqs":[
    ("Do you serve F.E. Warren Air Force Base?","Yes. We supply contractor teams at F.E. Warren AFB. We understand the base's ATFP security protocols, nuclear-adjacent access restrictions, and credentialing requirements for on-base service."),
    ("How much does portable toilet rental cost in Cheyenne?","Standard units from $75/day or $199/week in Laramie County. Fort Collins CO (just 45 miles south) carries the same rate. Luxury trailers from $575/event."),
    ("Do you serve Frontier Days?","Yes. Frontier Days at Frontier Park is our largest annual event deployment in Wyoming. Contact us by May for July Frontier Days orders — inventory is pre-allocated for this event."),
    ("Do you cross into northern Colorado (Fort Collins, Greeley)?","Yes. Fort Collins, Greeley, Loveland, and northern Weld County are within our service area from Cheyenne. Cross-state delivery carries no additional fee for most Larimer and Weld county locations."),
    ("Are your units Wyoming DEQ compliant?","Yes. All units meet Wyoming Department of Environmental Quality portable sanitation standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Laramie and Albany County?","Yes. Laramie and the University of Wyoming are within our service area — approximately 50 miles west on I-80."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Cheyenne y todo el condado de Laramie."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Cheyenne-area construction."),
  ],
  "related_cities":[("Wyoming","wyoming")],
},

"casper-wy": {
  "name":"Casper","state":"WY","state_name":"Wyoming","county":"Natrona County",
  "lat":42.8666,"lon":-106.3131,"zip":"82601","address":"200 N David St",
  "theme":"#0369a1","colors":("#eff6ff","#dbeafe","#93c5fd","#3b82f6","#2563eb","#1d4ed8","#1e40af","#1e3a8a"),
  "hero_img":HEROES[10],
  "title":"Porta Potty Rental Casper, WY — Oil City · Same-Day · From $75/Day",
  "h1_city":"Casper, WY","h1_sub":"Oil City · Natrona County Energy Hub",
  "meta_desc":"Portable toilet rental Casper WY from $75/day. Serving Powder River Basin energy construction, Natrona County job sites, Central Wyoming events & oilfield support. Call (833) 652-9344.",
  "og_title":"Casper WY Porta Potty Rentals | Oil City | Energy Construction",
  "og_desc":"Casper WY portable toilet rental for Powder River Basin energy construction, Central Wyoming events, and Natrona County job sites. Same-day delivery.",
  "services_intro":"From Powder River Basin coal and energy construction and the refineries along the North Platte River to Central Wyoming College campus projects and events at the Ford Wyoming Center, FixPilot delivers portable sanitation across all of Natrona County and Central Wyoming.",
  "demand_para":"Casper is Wyoming's oil and energy capital, sitting at the center of the Powder River Basin — one of the most productive coal mining and coalbed methane production areas in the world. Arch Resources, Peabody Energy, and Foresight Energy run major surface mine operations within trucking distance of Casper. The refineries along the North Platte River corridor require regular turnaround maintenance events. Wind energy development across Natrona, Carbon, and Converse counties has added a renewable energy construction layer that requires field-ready portable toilets at turbine installation sites across open rangeland.",
  "event_para":"The Wyoming State Fair in Douglas, Central Wyoming Fair & Rodeo in Casper, and the Casper Mountain outdoor recreation events create consistent seasonal demand. The Nicolaysen Art Museum outdoor events and the Casper Events Center concert and rodeo calendar round out the year-round event rental picture.",
  "areas":["Mills","Evansville","Bar Nunn","Douglas","Glenrock","Riverton","Lander","Thermopolis","Rawlins","Torrington"],
  "nearby_text":"Mills, Evansville, Douglas, Glenrock, Riverton",
  "county_nearby":"Natrona County","wiki_city":"Casper,_Wyoming","mapq":"Casper+WY+82601",
  "reviews":[
    ("Steve H., Powder River Contractor","★★★★★","Surface mine construction in the Powder River Basin east of Casper — remote, rough terrain, extreme temperature swings. FixPilot delivers and services without complaint. Other vendors won't operate out there. FixPilot does."),
    ("Carol M., CWF&R Events","★★★★★","Central Wyoming Fair & Rodeo — 20 units for 8 days. FixPilot understands Wyoming rodeo culture and what fair attendance means for sanitation frequency. Serviced twice daily at peak. Clean and reliable every year."),
    ("Dave T., Wind Farm Contractor","★★★★★","Wind turbine installation in Carbon County — turbines spread across 40,000 acres of rangeland. FixPilot staggers deliveries to match the installation sequence and the drivers know how to find a location GPS coordinates that aren't on any map."),
    ("Karen L., Wedding Coordinator","★★★★★","Outdoor Casper Mountain wedding — stunning Wyoming views, 100 guests. The luxury trailer was perfect. FixPilot made a remote venue feel like a proper venue."),
  ],
  "faqs":[
    ("Do you serve Powder River Basin mining and energy sites?","Yes. We supply heavy-duty portable toilets to coal mine construction, coalbed methane well sites, and conventional oil and gas operations throughout the Powder River Basin. Remote access delivery is standard for our energy market service."),
    ("How much does portable toilet rental cost in Casper, WY?","Standard units from $75/day or $219/week in Natrona County. Remote energy site fees apply beyond 40-mile radius. Luxury trailers from $575/event."),
    ("Do you serve wind energy construction in Carbon County?","Yes. Wind turbine installation projects across Carbon, Natrona, and Converse counties are served. We coordinate deliveries to match turbine installation sequences across large project areas."),
    ("Do you cover Riverton and Fremont County?","Yes. Riverton and Lander are within our extended service area. Contact us for Wind River Indian Reservation-adjacent project requirements."),
    ("Are your units Wyoming DEQ compliant?","Yes. All units meet Wyoming DEQ portable sanitation standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Casper Mountain events?","Yes. Casper Mountain trail events, ski area construction, and private venues are served with appropriate mountain access logistics."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Casper y todo el condado de Natrona."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Casper-area construction."),
  ],
  "related_cities":[("Cheyenne WY","cheyenne-wy"),("Wyoming","wyoming")],
},

"bismarck-nd": {
  "name":"Bismarck","state":"ND","state_name":"North Dakota","county":"Burleigh County",
  "lat":46.8083,"lon":-100.7837,"zip":"58501","address":"221 N 5th St",
  "theme":"#0369a1","colors":("#eff6ff","#dbeafe","#93c5fd","#3b82f6","#2563eb","#1d4ed8","#1e40af","#1e3a8a"),
  "hero_img":HEROES[11 % len(HEROES)],
  "title":"Porta Potty Rental Bismarck, ND — Prairie Capital · Same-Day · From $75",
  "h1_city":"Bismarck, ND","h1_sub":"Prairie Capital · Bakken Oil Gateway",
  "meta_desc":"Portable toilet rental Bismarck ND from $75/day. Serving Bakken oilfield support, state government construction, Burleigh County job sites & Missouri River events. Call (833) 652-9344.",
  "og_title":"Bismarck ND Porta Potty Rentals | Prairie Capital | Bakken Ready",
  "og_desc":"Bismarck ND portable toilet rental for Bakken oilfield construction, state government projects, and Burleigh County job sites. Same-day delivery. Call (833) 652-9344.",
  "services_intro":"From Bakken oilfield staging logistics in the Williston Basin and North Dakota State Capitol construction to Missouri River Trail events and the Bismarck-Mandan bridge corridor infrastructure projects, FixPilot delivers reliable portable sanitation across all of Burleigh and Morton counties.",
  "demand_para":"Bismarck serves as the gateway and logistics hub for North Dakota's Bakken oil boom. Williams, Mountrail, and McKenzie counties — the heart of the Bakken — ship equipment and workers through Bismarck, making it a central node in one of the most active energy economies in America. The State Capitol complex perpetually expands. Sanford Health's and CHI St. Alexius Medical Center's hospital campuses generate institutional construction. The I-94 commercial corridor through Mandan is seeing its highest retail and industrial construction activity in a generation.",
  "event_para":"The United Tribes International Powwow — one of the largest intertribal powwows in the country — draws 70,000+ to the Bismarck Event Center. The Bismarck Larks baseball season, River's Edge Park outdoor events, and the Bismarck-Mandan Visitors Bureau's Missouri River events create consistent summer demand for portable sanitation.",
  "areas":["Mandan","Lincoln ND","Washburn","Hazen","Beulah","Dickinson","Minot","Williston","Watford City","New Town"],
  "nearby_text":"Mandan, Lincoln ND, Dickinson, Hazen, Washburn",
  "county_nearby":"Burleigh County","wiki_city":"Bismarck,_North_Dakota","mapq":"Bismarck+ND+58501",
  "reviews":[
    ("Jim K., Bakken Operator","★★★★★","Staging and crew facilities near Williston — FixPilot delivers to Bakken-area sites from Bismarck without the response-time issues I've had with vendors based in Williston. Reliable service for a demanding oilfield environment."),
    ("Sarah T., United Tribes Powwow","★★★★★","United Tribes International Powwow at the Bismarck Event Center — 25 units, 4 days, 70,000 visitors. FixPilot serviced twice daily and the grounds stayed pristine. This event represents our nation's culture — we need flawless sanitation and FixPilot delivered."),
    ("Gary B., Capitol Complex Contractor","★★★★★","North Dakota State Capitol building renovation — working next to the state's most prominent civic landmark. FixPilot placed units with appropriate discretion and maintained impeccable service throughout the 8-month project."),
    ("Michelle R., Bismarck Events","★★★★★","River's Edge Park summer concert series — 8 units per event, 10-event season. FixPilot serviced before every show. The Missouri River setting demands cleanliness and FixPilot delivered every week."),
  ],
  "faqs":[
    ("Do you serve Bakken oilfield sites from Bismarck?","Yes. We supply heavy-duty portable toilets to Bakken oil and gas contractor teams staging through Bismarck for operations in Williams, Mountrail, McKenzie, and Dunn counties. Remote access delivery available."),
    ("How much does portable toilet rental cost in Bismarck, ND?","Standard units from $75/day or $199/week in Burleigh County. Morton County (Mandan) carries the same rate. Remote Bakken delivery fees apply based on site distance. Luxury trailers from $575/event."),
    ("Do you cover Mandan and Morton County?","Yes. Mandan is a co-primary market with Bismarck. We serve all of Morton County with same-day delivery available."),
    ("Do you provide cold-weather units for North Dakota winters?","Yes. Cold-weather portable toilets with antifreeze-treated tanks are available and strongly recommended for North Dakota winter construction sites."),
    ("Are your units North Dakota DOH compliant?","Yes. All units meet North Dakota Department of Health portable sanitation standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Dickinson and Williston?","Dickinson and Williston are within our extended service area. Contact us for Bakken-corridor project-specific scheduling and pricing."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Bismarck y todo el condado de Burleigh."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Bismarck construction."),
  ],
  "related_cities":[("Fargo ND","fargo-nd"),("North Dakota","north-dakota")],
},

"rapid-city-sd": {
  "name":"Rapid City","state":"SD","state_name":"South Dakota","county":"Pennington County",
  "lat":44.0805,"lon":-103.2310,"zip":"57701","address":"300 6th St",
  "theme":"#15803d","colors":("#f0fdf4","#dcfce7","#86efac","#22c55e","#16a34a","#15803d","#166534","#14532d"),
  "hero_img":HEROES[12 % len(HEROES)],
  "title":"Porta Potty Rental Rapid City, SD — Black Hills · Same-Day · From $75/Day",
  "h1_city":"Rapid City, SD","h1_sub":"Gateway to the Black Hills · Sturgis Ready",
  "meta_desc":"Portable toilet rental Rapid City SD from $75/day. Serving Sturgis Rally, Black Hills construction, Mount Rushmore events & Pennington County job sites. Call (833) 652-9344.",
  "og_title":"Rapid City SD Porta Potty Rentals | Black Hills | Sturgis Rally",
  "og_desc":"Rapid City portable toilet rental for Sturgis Motorcycle Rally, Black Hills construction, and Mount Rushmore area events. Same-day delivery across Pennington County.",
  "services_intro":"From the Sturgis Motorcycle Rally at the Sturgis Meade County fairgrounds and Mount Rushmore visitor facilities to Black Hills Energy infrastructure projects and the Ellsworth Air Force Base expansion, FixPilot delivers portable sanitation across all of the Black Hills region.",
  "demand_para":"Rapid City's economy is anchored by tourism, military, and healthcare. Ellsworth Air Force Base — home to B-1B Lancer bombers — is undergoing significant base expansion including new aircraft hangars and administrative facilities, generating sustained contractor portable toilet demand. Monument Health's hospital campus on North Fifth Street is perpetually expanding. The Black Hills construction market has been energized by a consistent stream of remote workers relocating to the region, driving residential construction in Box Elder, Summerset, and the Canyon Lake neighborhoods.",
  "event_para":"The Sturgis Motorcycle Rally is the largest annual motorcycle gathering on Earth — 500,000+ riders and spectators descend on the Black Hills each August. Mount Rushmore National Memorial, Crazy Horse Memorial, and Custer State Park's Buffalo Roundup create year-round tourism infrastructure demand. The Rapid City Rush hockey season, Black Hills Stock Show, and ChopperSpotting events round out the annual calendar.",
  "areas":["Box Elder","Summerset","Sturgis","Spearfish","Lead","Deadwood","Hill City","Custer","Hot Springs","Keystone"],
  "nearby_text":"Box Elder, Sturgis, Spearfish, Lead, Deadwood",
  "county_nearby":"Pennington County","wiki_city":"Rapid_City,_South_Dakota","mapq":"Rapid+City+SD+57701",
  "reviews":[
    ("Col. Reynolds (ret.), Ellsworth Contractor","★★★★★","Ellsworth AFB hangar construction — DoD credentialing, base security protocols, strict delivery windows. FixPilot navigated every Air Force Base requirement correctly. The most professional sanitation vendor I've worked with on a military installation."),
    ("Dirk H., Sturgis Rally Coordinator","★★★★★","Sturgis Rally at the Meade County Fairgrounds — 50 units, 10 days, 500,000 bikers. FixPilot has served the Rally for multiple years. They know biker culture, they know the site, and they service twice daily without fail. Irreplaceable partner."),
    ("Lisa K., Monument Health Contractor","★★★★★","Monument Health hospital expansion — hospital-adjacent delivery with infection-control zone protocols. FixPilot's drivers understand exactly what 'hospital-adjacent' means and have never breached a protocol. 11 months, zero incidents."),
    ("Tina M., Black Hills Weddings","★★★★★","Outdoor wedding near Keystone with Mount Rushmore views — 140 guests, breathtaking setting. The luxury trailer was the finishing touch that made the venue complete. FixPilot made an outdoor venue feel like an indoor venue."),
  ],
  "faqs":[
    ("Do you serve the Sturgis Motorcycle Rally?","Yes. The Sturgis Rally is our largest annual event deployment in South Dakota. We supply and service units at the Meade County Fairgrounds and event satellite sites throughout the Black Hills. Book by June for August Rally orders."),
    ("How much does portable toilet rental cost in Rapid City?","Standard units from $75/day or $199/week in Pennington County. Sturgis Rally premium pricing applies in August — contact us early for rally-season quotes. Luxury trailers from $575/event."),
    ("Do you serve Ellsworth AFB?","Yes. We supply contractor teams at Ellsworth Air Force Base. We understand DoD base access protocols, credentialing requirements, and base delivery procedures."),
    ("Do you cover Deadwood and Lead?","Yes. Deadwood, Lead, and the northern Black Hills are within our service area. Deadwood casino construction and events are served with advance notice."),
    ("Are your units South Dakota OSHA compliant?","Yes. All units meet South Dakota Department of Labor OSHA standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Custer State Park events?","Yes. Custer State Park — including the Buffalo Roundup and Wildlife Festival — is within our service area."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Rapid City y todo el condado de Pennington."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Black Hills construction."),
  ],
  "related_cities":[("Sioux Falls SD","sioux-falls-sd"),("South Dakota","south-dakota")],
},

"hattiesburg-ms": {
  "name":"Hattiesburg","state":"MS","state_name":"Mississippi","county":"Forrest County",
  "lat":31.3271,"lon":-89.2903,"zip":"39401","address":"200 Forrest St",
  "theme":"#15803d","colors":("#f0fdf4","#dcfce7","#86efac","#22c55e","#16a34a","#15803d","#166534","#14532d"),
  "hero_img":HEROES[13 % len(HEROES)],
  "title":"Porta Potty Rental Hattiesburg, MS — Hub City · Same-Day · From $75/Day",
  "h1_city":"Hattiesburg, MS","h1_sub":"Hub City · Pine Belt Region",
  "meta_desc":"Portable toilet rental Hattiesburg MS from $75/day. Serving USM construction, Forrest County job sites, Camp Shelby & Pine Belt regional events. Call (833) 652-9344.",
  "og_title":"Hattiesburg MS Porta Potty Rentals | Hub City | Pine Belt",
  "og_desc":"Hattiesburg MS portable toilet rental for University of Southern Mississippi, Camp Shelby, and Pine Belt construction. Same-day delivery across Forrest County.",
  "services_intro":"From the University of Southern Mississippi campus expansion and Camp Shelby Joint Forces Training Center to the Hardy Street commercial corridor construction and events at the Hattiesburg Zoo, FixPilot delivers clean portable sanitation across the Pine Belt region.",
  "demand_para":"Hattiesburg is the economic hub of the Pine Belt, anchored by the University of Southern Mississippi (USM), Forrest General Hospital, and a growing manufacturing and distribution base along the I-59 and US-49 corridors. USM's perpetual campus construction program, Forrest General's hospital expansion, and the Pine Belt Regional Industrial Park's new tenant buildouts generate consistent construction portable toilet demand. Camp Shelby — one of the largest National Guard training installations in the country — generates periodic large-scale contractor construction projects.",
  "event_para":"USM Golden Eagle football games, the Hattiesburg Zoo events, Hubfest arts festival, and the annual Pine Belt Mardi Gras parades create consistent event portable toilet demand. The growing Hattiesburg wedding market — centered on venue conversions in the Hattiesburg Historic Neighborhood District — is an emerging luxury restroom trailer segment.",
  "areas":["Petal","Laurel","Lumberton","Sumrall","Purvis","Poplarville","Columbia","Wiggins","Picayune","Gulfport"],
  "nearby_text":"Petal, Laurel, Lumberton, Sumrall, Purvis",
  "county_nearby":"Forrest County","wiki_city":"Hattiesburg,_Mississippi","mapq":"Hattiesburg+MS+39401",
  "reviews":[
    ("Dr. Lewis, USM Construction","★★★★★","University of Southern Mississippi new science building construction. Campus delivery protocols, pedestrian zone management, strict service windows. FixPilot handles it all without direction. Exactly what a university campus requires from a vendor."),
    ("Sgt. Major Thomas (ret.), Camp Shelby","★★★★★","Camp Shelby Guard training facility renovation — military installation protocols, security requirements, zero-fault delivery windows. FixPilot met every requirement. First vendor I've recommended on a Guard installation in 15 years."),
    ("Maria C., Hattiesburg Events","★★★★★","Hubfest arts festival in downtown Hattiesburg — 10 units, 2-day event. FixPilot delivered at 6 AM and serviced mid-event without any disruption. Arts crowd has high standards and FixPilot met them without prompting."),
    ("Jessica H., Wedding Planner","★★★★★","Historic district outdoor wedding in Hattiesburg — 130 guests. The luxury trailer was stunning in that setting. Pine Belt brides take note: FixPilot is the vendor that makes outdoor venues work beautifully."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Hattiesburg, MS?","Standard units from $75/day or $195/week in Forrest County. Lamar and Jones county deliveries carry the same rate. Luxury trailers from $575/event."),
    ("Do you serve Camp Shelby?","Yes. We supply contractor teams and training support events at Camp Shelby JFTC. Military installation access protocols are standard procedure for our Camp Shelby service."),
    ("Do you cover Petal and Lamar County?","Yes. Petal and Lamar County are primary service areas with same-day delivery available."),
    ("Do you serve Laurel and Jones County?","Yes. Laurel is within our service area. HGTV's Home Town market familiarity means we also serve restoration construction projects in Jones County."),
    ("Are your units Mississippi DEQ compliant?","Yes. All units meet Mississippi DEQ portable sanitation standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Hattiesburg y todo el condado de Forrest."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Hattiesburg construction."),
    ("Do you serve the Gulf Coast from Hattiesburg?","Yes. We serve the Picayune-Poplarville corridor south toward the Gulf Coast. For Biloxi and Gulfport deliveries, our Gulf Coast base is primary."),
  ],
  "related_cities":[("Biloxi MS","biloxi-ms"),("Jackson MS","jackson-ms"),("Mississippi","mississippi")],
},

"joplin-mo": {
  "name":"Joplin","state":"MO","state_name":"Missouri","county":"Jasper County",
  "lat":37.0842,"lon":-94.5133,"zip":"64801","address":"602 S Main St",
  "theme":"#dc2626","colors":("#fef2f2","#fee2e2","#fca5a5","#ef4444","#dc2626","#b91c1c","#991b1b","#7f1d1d"),
  "hero_img":HEROES[14 % len(HEROES)],
  "title":"Porta Potty Rental Joplin, MO — Tornado City Strong · Same-Day · From $75",
  "h1_city":"Joplin, MO","h1_sub":"Four State Area · Jasper & Newton Counties",
  "meta_desc":"Portable toilet rental Joplin MO from $75/day. Serving Four State area construction, Missouri Southern events, tornado recovery projects & Jasper County job sites. Call (833) 652-9344.",
  "og_title":"Joplin MO Porta Potty Rentals | Four States | Same-Day Delivery",
  "og_desc":"Joplin MO portable toilet rental for Four State area construction, Missouri Southern events, and Jasper County job sites. Same-day delivery across the Ozarks border region.",
  "services_intro":"From the Joplin Regional Medical Center expansion and the Missouri Southern State University construction to tornado-recovery rebuilding projects and events at the Joplin Memorial Hall, FixPilot delivers portable sanitation across the Four State area of Missouri, Kansas, Oklahoma, and Arkansas.",
  "demand_para":"Joplin's post-2011 tornado rebuilding created a decade-long construction boom that transformed the city. That rebuilding momentum never fully stopped — new commercial development along Range Line Road, the Mercy Health hospital campus expansion, and the Highway 44/Route 66 industrial corridor continue to generate construction portable toilet demand. Joplin's position at the center of the Four State area makes it a regional distribution and logistics hub, with warehouse construction along I-44 adding to an always-active construction market.",
  "event_para":"The Joplin Memorial Marathon, Missouri Southern Homecoming, and the annual Joplin Car Show create consistent seasonal event demand. The Route 66 tourism corridor — Joplin sits on historic Route 66 — generates visitor traffic and related event demand that distinguishes it from similar-sized Midwest markets.",
  "areas":["Carthage MO","Neosho MO","Pittsburg KS","Coffeyville KS","Miami OK","Vinita OK","Rogers AR","Bentonville AR","Carl Junction MO","Webb City MO"],
  "nearby_text":"Carthage MO, Webb City MO, Neosho MO, Pittsburg KS, Miami OK",
  "county_nearby":"Jasper County","wiki_city":"Joplin,_Missouri","mapq":"Joplin+MO+64801",
  "reviews":[
    ("Tom K., Mercy Hospital Contractor","★★★★★","Mercy Health Joplin hospital expansion — hospital-adjacent delivery, infection control protocols. FixPilot knows what a healthcare construction environment requires. 9 months, zero issues. Best vendor on this campus."),
    ("Jane R., MSSU Athletics","★★★★★","Missouri Southern Homecoming weekend — 12 units on the campus athletic complex. Delivered Friday, retrieved Sunday. Clean and well-serviced throughout a 3-day high-traffic event. Students and alumni had zero complaints."),
    ("Dave M., Range Line Developer","★★★★★","Commercial development on Range Line Road. FixPilot delivers on time and services on schedule. In the Four State market finding a vendor this reliable is genuinely rare."),
    ("Lisa T., Joplin Events Planner","★★★★★","Outdoor wedding at a rural Jasper County venue — 120 guests. The luxury trailer was exactly what a Missouri country wedding needed. FixPilot made the outdoor setting feel complete."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Joplin, MO?","Standard units from $75/day or $195/week in Jasper County. Newton County (Neosho, Granby) and McDonald County carry the same rate. Luxury trailers from $575/event."),
    ("Do you serve the Four State area (MO, KS, OK, AR)?","Yes. We serve all of the Four State corner region including Pittsburg KS, Miami OK, and Rogers AR. Same-day delivery is available for most locations within 40 miles of Joplin."),
    ("Do you cover Webb City and Carl Junction?","Yes. Webb City and Carl Junction are primary local service areas within Jasper County."),
    ("Do you provide tornado emergency response?","Yes. We maintain emergency deployment capability for severe weather recovery events in the Joplin area and surrounding Four State region."),
    ("Are your units Missouri OSHA compliant?","Yes. All units meet Missouri DOLIR and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Joplin y toda el área de los Cuatro Estados."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Joplin construction."),
    ("Do you serve Carthage and the Route 66 corridor?","Yes. Carthage and all of Jasper County are within our primary service area."),
  ],
  "related_cities":[("Springfield MO","springfield-mo"),("Kansas City MO","kansas-city-mo"),("Missouri","missouri")],
},
}

def main():
    built = 0
    for slug, d in CITIES_B4.items():
        outdir = Path(f"porta-potty-rental-{slug}")
        outfile = outdir / "index.html"
        outdir.mkdir(exist_ok=True)
        html = build_page(slug, d)
        outfile.write_text(html, encoding="utf-8")
        print(f"  ✓ {slug} ({len(html):,} chars)")
        built += 1
    print(f"\nBuilt {built} city pages")

if __name__ == "__main__":
    main()
