#!/usr/bin/env python3
"""Batch 2: Durham NC, Virginia Beach VA, Pittsburgh PA, Portland OR,
   Albuquerque NM, Tulsa OK, Salt Lake City UT, Provo UT, Roanoke VA."""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from build_unique_cities import build_page, HEROES
from pathlib import Path

CITIES_B2 = {

"durham-nc": {
  "name":"Durham","state":"NC","state_name":"North Carolina","county":"Durham County",
  "lat":35.9940,"lon":-78.8986,"zip":"27701","address":"101 City Hall Plaza",
  "theme":"#0284c7","colors":("#f0f9ff","#e0f2fe","#7dd3fc","#0ea5e9","#0284c7","#0369a1","#075985","#0c4a6e"),
  "hero_img":HEROES[1],
  "title":"Porta Potty Rental Durham, NC — Bull City · Same-Day · From $75/Day",
  "h1_city":"Durham, NC","h1_sub":"Bull City · Duke & Research Triangle",
  "meta_desc":"Portable toilet rental Durham NC from $75/day. Same-day delivery for Duke University construction, RTP biotech sites, Durham Bulls events & county job sites. Call (833) 652-9344.",
  "og_title":"Durham NC Porta Potty Rentals | Bull City | Same-Day Delivery",
  "og_desc":"Durham NC portable toilet rental for Duke Health construction, Research Triangle biotech, and Durham Bulls events. Same-day delivery across Durham County.",
  "services_intro":"From Duke University Health System campus expansion and biotech construction along the Durham Freeway to Durham Bulls Athletic Park events and the American Tobacco District redevelopment, FixPilot serves all of the Bull City's portable sanitation needs.",
  "demand_para":"Durham County is a biotech and life sciences construction hotspot. Duke University Health System is perpetually expanding — the Duke Cancer Center, new Duke clinical towers, and supplier lab builds along the 15-501 corridor generate constant job-site portable toilet demand. Google's 1.5-million-square-foot Durham campus on the Golden Belt corridor adds tech construction to the mix, making Durham one of the most active mid-size construction markets on the East Coast.",
  "event_para":"Durham Bulls games at DBAP, the Full Frame Documentary Festival, North Carolina Central University events, and outdoor concerts at Motorco Music Hall draw consistent crowds. Our luxury restroom trailers are popular for private outdoor weddings across Chatham and Orange counties just west of the city.",
  "areas":["Chapel Hill","Carrboro","Hillsborough","Morrisville","Research Triangle Park","Cary","Pittsboro","Mebane","Burlington","Graham"],
  "nearby_text":"Chapel Hill, Carrboro, Hillsborough, RTP, Cary",
  "county_nearby":"Durham County","wiki_city":"Durham,_North_Carolina","mapq":"Durham+NC+27701",
  "reviews":[
    ("Kevin B., Duke Health Contractor","★★★★★","Duke medical campus expansion — 14 units, strict delivery windows, zero tolerance for service lapses. FixPilot hasn't missed a single weekly service in 10 months. The only vendor I trust on a Duke site."),
    ("Michelle T., Event Planner","★★★★★","Durham Bulls viewing party at the American Tobacco Campus — 400 guests, 6 units. Serviced mid-event without disrupting anything. Perfect execution."),
    ("Omar J., Biotech PM","★★★★★","Lab build on the Durham Freeway corridor. Fast delivery, OSHA documentation ready on Day 1. Exactly what you need when a biotech client is watching every detail."),
    ("Sarah C., Wedding Coordinator","★★★★★","Outdoor ceremony at a Chatham County farm. 150 guests. The luxury trailer was spotless and air-conditioned — guests kept saying it was the best wedding restroom they'd ever seen."),
  ],
  "faqs":[
    ("Do you serve Duke University and Duke Health construction sites?","Yes. We supply portable toilets to Duke University and Duke Health System contractor teams. We understand the campus access protocols, service window requirements, and documentation standards these sites demand."),
    ("How much does porta potty rental cost in Durham, NC?","Standard units start at $75/day or $199/week. Luxury restroom trailers start at $595/event. Durham County construction packages with weekly servicing run $85–$115/unit/week."),
    ("Do you serve Chapel Hill and UNC campus?","Yes. Chapel Hill and UNC-Chapel Hill are within our primary service area. Same-day delivery is available for most Orange County locations including Carrboro and Hillsborough."),
    ("Do you cover Research Triangle Park?","Yes. RTP is one of our highest-demand corridors. We serve every active construction and campus event site within the park boundaries."),
    ("Are your units VOSH/NC OSHA compliant?","Yes. All units meet North Carolina Department of Labor (NCDOL) and federal OSHA 29 CFR 1926.51 requirements."),
    ("Can I get luxury restroom trailers near Durham?","Yes. We serve outdoor wedding venues across Durham, Orange, Chatham, and Alamance counties. Climate-controlled, granite-finish trailers available."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para renta de baños portátiles en Durham y todo el condado de Durham."),
    ("What is the minimum rental period?","One day for events; weekly contracts are most economical for ongoing construction sites."),
  ],
  "related_cities":[("Raleigh NC","raleigh-nc"),("Greensboro NC","greensboro-nc"),("Charlotte NC","charlotte-nc"),("North Carolina","north-carolina")],
},

"virginia-beach-va": {
  "name":"Virginia Beach","state":"VA","state_name":"Virginia","county":"Virginia Beach City",
  "lat":36.8529,"lon":-75.9780,"zip":"23451","address":"2401 Courthouse Dr",
  "theme":"#0891b2","colors":("#ecfeff","#cffafe","#67e8f9","#06b6d4","#0891b2","#0e7490","#155e75","#164e63"),
  "hero_img":HEROES[2],
  "title":"Porta Potty Rental Virginia Beach, VA — Oceanfront City · From $75/Day",
  "h1_city":"Virginia Beach, VA","h1_sub":"Oceanfront · Military & Events",
  "meta_desc":"Portable toilet rental Virginia Beach VA from $75/day. Serving Neptune Festival, military base construction, Chesapeake development & Hampton Roads events. Call (833) 652-9344.",
  "og_title":"Virginia Beach VA Porta Potty Rentals | Oceanfront | Same-Day Delivery",
  "og_desc":"Virginia Beach portable toilet rental for Neptune Festival, NAS Oceana construction, and Hampton Roads events. Same-day delivery to Chesapeake, Norfolk, Suffolk.",
  "services_intro":"From the Neptune Festival on the Oceanfront and Navy SEAL training support at Dam Neck Annex to the Chesapeake Square corridor development and Virginia Beach Convention Center events, FixPilot serves all of Hampton Roads with clean, same-day portable sanitation.",
  "demand_para":"Virginia Beach is home to the largest concentration of military installations in the world — NAS Oceana, Joint Expeditionary Base Little Creek-Fort Story, and Dam Neck Annex generate millions in annual contractor construction activity. The city's Town Center district is expanding with high-rise mixed-use, and Chesapeake's Greenbrier corridor adds suburban construction demand that keeps our fleet busy year-round.",
  "event_para":"The Neptune Festival draws 700,000+ to the Oceanfront each September. Patriot's Landing events, Virginia Beach Amphitheater concerts, and the Patriot's Landing boardwalk festivals create consistent summer event rental demand. Our luxury restroom trailers are popular for oceanfront weddings and upscale corporate events at resort properties.",
  "areas":["Chesapeake","Norfolk","Portsmouth","Suffolk","Hampton","Newport News","Kempsville","Great Neck","Princess Anne","Sandbridge"],
  "nearby_text":"Chesapeake, Norfolk, Portsmouth, Suffolk, Hampton",
  "county_nearby":"Virginia Beach City","wiki_city":"Virginia_Beach,_Virginia","mapq":"Virginia+Beach+VA+23451",
  "reviews":[
    ("Col. R. Hartley (ret.), Contractor","★★★★★","NAS Oceana facility renovation project — FixPilot understands military base access protocols, CAC requirements, and zero-tolerance delivery windows. No other vendor has matched their professionalism on a DoD site."),
    ("Diane P., Neptune Festival","★★★★★","Neptune Festival on the Boardwalk — 28 units over 3 days, 700,000 visitors. FixPilot serviced twice daily without ever blocking pedestrian access. Operational precision we couldn't find anywhere else."),
    ("Marcus T., Homebuilder","★★★★★","Building communities in Princess Anne and Kempsville. FixPilot delivers on time, services on schedule, and the drivers know how to navigate the beach-area traffic. Reliable every week."),
    ("Amanda L., Wedding Planner","★★★★★","Oceanfront wedding reception at a Virginia Beach resort — 200 guests. Two luxury trailers staged discreetly. Every single guest commented on how nice they were. Will use FixPilot for every beach event."),
  ],
  "faqs":[
    ("Do you serve military installations in Virginia Beach?","Yes. We supply portable sanitation to contractor teams at NAS Oceana, Joint Expeditionary Base Little Creek-Fort Story, and Dam Neck Annex. We understand DoD access requirements, PIV/CAC protocols, and base delivery windows."),
    ("How much does portable toilet rental cost in Virginia Beach?","Standard units from $75/day or $199/week. Luxury restroom trailers from $625/event (beach-area delivery logistics apply). Hampton Roads construction packages run $85–$120/unit/week."),
    ("Do you serve Chesapeake and the Greenbrier corridor?","Yes. Chesapeake is one of our highest-demand service areas, including the Greenbrier retail corridor, Great Bridge construction, and all of Chesapeake's residential development zones."),
    ("Do you cover Norfolk and Portsmouth?","Yes. We serve all of Hampton Roads including Norfolk, Portsmouth, Hampton, Newport News, and Poquoson. Cross-city tunnel delivery is available for Peninsula jobs."),
    ("Can I get luxury trailers for an Oceanfront event?","Yes. Our luxury trailers are well-suited for resort-adjacent outdoor events and upscale beach weddings along the Virginia Beach Oceanfront strip."),
    ("Are your units VOSH-compliant?","Yes. Virginia OSHA (VOSH) mirrors federal OSHA 29 CFR 1926.51. We provide VOSH documentation with every construction order."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Virginia Beach y todo el área de Hampton Roads."),
    ("What's your lead time for large festival orders?","2–3 weeks advance notice recommended for orders of 20+ units at Oceanfront events. We maintain a dedicated Hampton Roads summer event fleet."),
  ],
  "related_cities":[("Richmond VA","richmond-va"),("Fairfax County VA","fairfax-county-va"),("Virginia","virginia")],
},

"pittsburgh-pa": {
  "name":"Pittsburgh","state":"PA","state_name":"Pennsylvania","county":"Allegheny County",
  "lat":40.4406,"lon":-79.9959,"zip":"15222","address":"414 Grant St",
  "theme":"#f59e0b","colors":("#fffbeb","#fef3c7","#fcd34d","#f59e0b","#d97706","#b45309","#92400e","#78350f"),
  "hero_img":HEROES[3],
  "title":"Porta Potty Rental Pittsburgh, PA — Steel City · Same-Day · From $75/Day",
  "h1_city":"Pittsburgh, PA","h1_sub":"Steel City · Allegheny County",
  "meta_desc":"Portable toilet rental Pittsburgh PA from $75/day. Serving Allegheny County construction, Three Rivers events, Steelers tailgates & Strip District redevelopment. Call (833) 652-9344.",
  "og_title":"Pittsburgh PA Porta Potty Rentals | Steel City | Same-Day Delivery",
  "og_desc":"Pittsburgh portable toilet rental for Allegheny County construction, Strip District development, and Three Rivers events. Same-day delivery. Call (833) 652-9344.",
  "services_intro":"From the Strip District tech campus buildout and PNC Park Three Rivers Regatta events to Carnegie Mellon University construction and the North Shore stadium corridor, FixPilot delivers clean portable sanitation throughout Greater Pittsburgh.",
  "demand_para":"Pittsburgh's reindustrialization is real and accelerating. Google's 1.5-million-square-foot Strip District campus, Apple's Carnegie Mellon University AI partnership facilities, and the Robotics Row corridor in Lawrenceville are drawing billions in tech construction investment. Add UPMC's perpetual hospital campus expansion, conventional suburban residential growth in Cranberry Township and McCandless, and infrastructure projects on the Mon-Fayette Expressway, and Pittsburgh is one of the most active construction markets in the Northeast.",
  "event_para":"Steelers tailgates at Acrisure Stadium, Penguins events at PPG Paints Arena, the Three Rivers Arts Festival, and Pittsburgh's booming outdoor wedding market across Fox Chapel, Sewickley, and the Laurel Highlands create consistent seasonal portable sanitation demand. Our luxury trailers are frequently booked for vineyard weddings in the Laurel Highlands.",
  "areas":["Cranberry Township","McCandless","Bethel Park","Mt. Lebanon","Monroeville","Murrysville","Wexford","Sewickley","Fox Chapel","Canonsburg"],
  "nearby_text":"Cranberry Township, Bethel Park, Mt. Lebanon, Monroeville, Wexford",
  "county_nearby":"Allegheny County","wiki_city":"Pittsburgh","mapq":"Pittsburgh+PA+15222",
  "reviews":[
    ("Dave K., Tech Campus Contractor","★★★★★","Google Strip District build — 200-worker crews, tight downtown footprint, Penn Ave delivery restrictions. FixPilot navigated every constraint and never missed a service. Best sanitation vendor I've used in Pittsburgh."),
    ("Lisa M., Events Director","★★★★★","Three Rivers Arts Festival — 20 units across multiple outdoor stages for 12 days. Serviced every morning before 9 AM. Pittsburgh summers are humid and FixPilot kept every unit spotless. Exceptional."),
    ("Frank D., UPMC Subcontractor","★★★★★","Children's Hospital expansion in Lawrenceville. Strict delivery schedules, hospital-adjacent access. FixPilot handled it professionally every week for 8 months straight."),
    ("Kate B., Wedding Planner","★★★★★","Laurel Highlands vineyard wedding — 180 guests, two luxury trailers. The units were cleaner and nicer than venues I've used that cost 5x as much. FixPilot is my go-to for western PA outdoor events."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Pittsburgh?","Standard units from $75/day or $199/week in Allegheny County. Luxury restroom trailers from $595/event. UPMC-adjacent and hospital-district deliveries are available with credentialing documentation upon request."),
    ("Do you serve Cranberry Township and the North Hills?","Yes. Cranberry Township, Wexford, McCandless, and the Route 19 North Hills corridor are among our highest-demand service areas due to rapid residential and commercial construction."),
    ("Do you cover the Strip District and downtown construction?","Yes. We navigate downtown Pittsburgh delivery restrictions and serve all active construction sites in the Strip, Lawrenceville, and the North Shore corridor. Off-hours delivery is available for congested urban sites."),
    ("Are your units Pennsylvania DEP compliant?","Yes. All units meet Pennsylvania Department of Environmental Protection portable sanitation standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Washington and Westmoreland counties?","Yes. We cover Canonsburg, Washington, Greensburg, Murrysville, and surrounding areas. Laurel Highlands delivery is available with advance notice."),
    ("Can I rent luxury restroom trailers for a Laurel Highlands wedding?","Yes. Our self-contained luxury trailers require no hookups and are ideal for vineyard and mountain venue weddings across Fayette, Somerset, and Westmoreland counties."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Pittsburgh y todo el condado de Allegheny."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Pittsburgh construction sites."),
  ],
  "related_cities":[("Allegheny County PA","allegheny-county-pa"),("Pennsylvania","pennsylvania")],
},

"portland-or": {
  "name":"Portland","state":"OR","state_name":"Oregon","county":"Multnomah County",
  "lat":45.5051,"lon":-122.6750,"zip":"97201","address":"1221 SW 4th Ave",
  "theme":"#15803d","colors":("#f0fdf4","#dcfce7","#86efac","#22c55e","#16a34a","#15803d","#166534","#14532d"),
  "hero_img":HEROES[4],
  "title":"Porta Potty Rental Portland, OR — City of Roses · Same-Day · From $75/Day",
  "h1_city":"Portland, OR","h1_sub":"City of Roses · Multnomah County",
  "meta_desc":"Portable toilet rental Portland OR from $75/day. Serving Multnomah County construction, Intel Hillsboro, Rose Festival & Willamette Valley events. OSHA-compliant. Call (833) 652-9344.",
  "og_title":"Portland OR Porta Potty Rentals | City of Roses | Same-Day Delivery",
  "og_desc":"Portland OR portable toilet rental for Intel Hillsboro construction, Rose Festival events, and Multnomah County job sites. Same-day delivery. Call (833) 652-9344.",
  "services_intro":"From Intel's Hillsboro semiconductor campus expansion and the Pearl District mixed-use construction boom to Portland Rose Festival events on the Tom McCall Waterfront and winery events in the Willamette Valley, FixPilot serves all of the Portland metro's portable sanitation needs.",
  "demand_para":"Portland's construction market is driven by semiconductor manufacturing at an unprecedented scale. Intel's Hillsboro campus — the largest semiconductor manufacturing complex in the Americas — is undergoing a multi-billion dollar expansion. TSMC's potential Oregon investment has triggered a supply-chain construction wave across Washington County. The Pearl District, South Waterfront, and Lloyd District redevelopment add urban mixed-use construction to a market that never truly slows down.",
  "event_para":"The Portland Rose Festival is one of the largest floral-themed festivals in the U.S., drawing 2 million visitors to the waterfront. Oregon Brewfest at Tom McCall Waterfront Park, the Oregon State Fair in Salem, and the Willamette Valley's wine country events create year-round outdoor event rental demand. Our luxury trailers are frequently requested for upscale vineyard events in the Dundee Hills and Chehalem Mountains.",
  "areas":["Hillsboro","Beaverton","Gresham","Lake Oswego","Tualatin","Tigard","Oregon City","Milwaukie","Vancouver WA","Wilsonville"],
  "nearby_text":"Hillsboro, Beaverton, Gresham, Tualatin, Lake Oswego",
  "county_nearby":"Multnomah County","wiki_city":"Portland,_Oregon","mapq":"Portland+OR+97201",
  "reviews":[
    ("Jim H., Intel Subcontractor","★★★★★","Intel Hillsboro D1X expansion — strict security protocols, 24-hour shift operations, 50+ units rotating. FixPilot knows the campus requirements and has never created a compliance issue in 14 months. Rare professionalism."),
    ("Rosa G., Rose Festival Coordinator","★★★★★","Rose Festival waterfront — 35 units across three zones for 12 days. Serviced every morning without fail. Hundreds of thousands of visitors and we received zero sanitation complaints. FixPilot delivered."),
    ("Tom A., Pearl District Developer","★★★★★","Mixed-use tower in the Pearl. Tight footprint, pedestrian traffic, NW Portland access rules. FixPilot handled every logistical wrinkle and kept the site OSHA-compliant throughout."),
    ("Claire M., Vineyard Events","★★★★★","Oregon wine country wedding in the Chehalem Mountains — 130 guests. Luxury trailer positioned in the vineyard rows. It was genuinely beautiful. Guests photographed it alongside the vines."),
  ],
  "faqs":[
    ("Do you serve Intel's Hillsboro campus?","Yes. Intel Hillsboro is one of our largest accounts in Oregon. We understand the campus security requirements, credentialing protocols, delivery windows, and 24-hour shift operation needs. We serve all active expansion phases."),
    ("How much does portable toilet rental cost in Portland?","Standard units from $75/day or $205/week in Multnomah County. Washington County (Hillsboro/Beaverton) pricing is identical. Luxury trailers from $625/event. Oregon DEQ documentation included with all construction orders."),
    ("Do you serve Washington County and Hillsboro?","Yes. Washington County is one of our highest-volume service areas. We cover Hillsboro, Beaverton, Aloha, Cornelius, Forest Grove, and the Highway 26 tech corridor."),
    ("Are your units compliant with Oregon DEQ standards?","Yes. All units meet Oregon Department of Environmental Quality portable sanitation regulations and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you cross into Vancouver, Washington?","Yes. We serve Clark County, Washington including Vancouver, Camas, Washougal, and Battle Ground. Cross-state delivery carries no additional fee for most Clark County locations."),
    ("Can I rent luxury trailers for a Willamette Valley wine country event?","Yes. Our self-contained luxury trailers are popular for vineyard weddings and private events in Yamhill County, the Dundee Hills, and Chehalem Mountains wine regions."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Portland y todo el condado de Multnomah."),
    ("What's the minimum rental period?","One day minimum for events; weekly contracts most economical for Portland-area construction sites."),
  ],
  "related_cities":[("Multnomah County OR","multnomah-county-or"),("Spokane WA","spokane-wa"),("Vancouver WA","vancouver-wa"),("Oregon","oregon")],
},

"albuquerque-nm": {
  "name":"Albuquerque","state":"NM","state_name":"New Mexico","county":"Bernalillo County",
  "lat":35.0844,"lon":-106.6504,"zip":"87102","address":"1 Civic Plaza NW",
  "theme":"#c2410c","colors":("#fff7ed","#ffedd5","#fdba74","#f97316","#ea580c","#c2410c","#9a3412","#7c2d12"),
  "hero_img":HEROES[5],
  "title":"Porta Potty Rental Albuquerque, NM — Duke City · Same-Day · From $75/Day",
  "h1_city":"Albuquerque, NM","h1_sub":"Duke City · Balloon Fiesta Capital",
  "meta_desc":"Portable toilet rental Albuquerque NM from $75/day. Serving Balloon Fiesta, Kirtland AFB contractors, Bernalillo County construction & Rio Grande events. Call (833) 652-9344.",
  "og_title":"Albuquerque NM Porta Potty Rentals | Balloon Fiesta | Same-Day",
  "og_desc":"Albuquerque portable toilet rental for Balloon Fiesta, Kirtland AFB construction, and Bernalillo County job sites. Same-day delivery. Call (833) 652-9344.",
  "services_intro":"From the world's largest hot air balloon festival at Balloon Fiesta Park to Kirtland Air Force Base contractor construction and the massive Rio Rancho industrial buildout, FixPilot delivers reliable portable sanitation across the Duke City and all of Bernalillo and Sandoval counties.",
  "demand_para":"Albuquerque sits at the center of New Mexico's oil-and-gas economy and federal defense contracting. Kirtland AFB — one of the Air Force's most important logistics and nuclear storage installations — generates consistent contractor construction activity. Intel's Rio Rancho facility (one of the company's oldest U.S. fabs) continues to expand. The Central Avenue/Route 66 corridor, Mesa del Sol development, and Albuquerque's growing biotech cluster are pushing commercial construction higher each year.",
  "event_para":"The Albuquerque International Balloon Fiesta is the most photographed event in the world — 500,000+ visitors in October. The New Mexico State Fair, Gathering of Nations Powwow, and outdoor concerts at Tingley Coliseum create year-round event rental demand. Our units are staged at Balloon Fiesta Park annually by experienced crews who know the site layout.",
  "areas":["Rio Rancho","Bernalillo","Corrales","Los Lunas","Belen","Edgewood","Tijeras","Rio Rancho West","Kirtland AFB","East Mountains"],
  "nearby_text":"Rio Rancho, Bernalillo, Los Lunas, Corrales, Edgewood",
  "county_nearby":"Bernalillo County","wiki_city":"Albuquerque,_New_Mexico","mapq":"Albuquerque+NM+87102",
  "reviews":[
    ("Capt. J. Romero (ret.), Contractor","★★★★★","Kirtland AFB utility project — base access clearance, strict delivery protocols, zero-fault tolerance. FixPilot checked every box without being told twice. Only vendor I've trusted on a DoD site in New Mexico."),
    ("Maria F., Balloon Fiesta Operations","★★★★★","Balloon Fiesta Park — 40 units for 9 days, 500,000 visitors. FixPilot has served the festival for multiple years. They know the layout, they know the timing, and the units are always clean when the first balloons inflate at dawn."),
    ("Steve D., Rio Rancho Developer","★★★★★","Commercial construction along US-550. FixPilot delivers on rough desert access roads and services reliably in July heat. In Albuquerque you need a vendor who doesn't flinch at desert conditions."),
    ("Linda G., Wedding Planner","★★★★★","Outdoor ceremony in the East Mountains — 120 guests, high desert setting at 7,000 feet. The luxury trailer handled the elevation and temperature swing perfectly. Guests were genuinely surprised."),
  ],
  "faqs":[
    ("Do you serve Balloon Fiesta Park?","Yes. Albuquerque International Balloon Fiesta is one of our signature annual events. We supply and service units at Balloon Fiesta Park throughout the 9-day October festival. Pre-booking by August is recommended."),
    ("How much does portable toilet rental cost in Albuquerque?","Standard units from $75/day or $195/week in Bernalillo County. Rio Rancho and Sandoval County pricing is identical. Luxury trailers from $575/event. Kirtland AFB base access coordination available."),
    ("Do you serve Rio Rancho and Sandoval County?","Yes. Rio Rancho and the US-550 industrial corridor are primary service areas. We cover all of Sandoval County including Bernalillo, Corrales, and Rio Rancho West."),
    ("Do you work with Kirtland AFB contractors?","Yes. We coordinate with contractors at Kirtland Air Force Base. We understand DoD base access procedures and can provide documentation required for on-base service."),
    ("Are your units rated for New Mexico desert heat?","Yes. Our units include ventilation designed for extreme heat. For sites in direct summer sun, we recommend shaded placement and can advise on best siting for a given project."),
    ("Do you serve the East Mountains and Tijeras Canyon?","Yes. We serve Edgewood, Tijeras, Moriarty, and the I-40 East Mountain corridor. Rural site delivery is available with advance notice."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Albuquerque y todo el condado de Bernalillo."),
    ("What is the minimum rental period?","One day minimum for events; weekly contracts most economical for ongoing Albuquerque construction sites."),
  ],
  "related_cities":[("Oklahoma County OK","oklahoma-county-ok"),("New Mexico","new-mexico")],
},

"tulsa-ok": {
  "name":"Tulsa","state":"OK","state_name":"Oklahoma","county":"Tulsa County",
  "lat":36.1540,"lon":-95.9928,"zip":"74103","address":"175 E 2nd St",
  "theme":"#b45309","colors":("#fffbeb","#fef3c7","#fcd34d","#f59e0b","#d97706","#b45309","#92400e","#78350f"),
  "hero_img":HEROES[6],
  "title":"Porta Potty Rental Tulsa, OK — Oil Capital · Same-Day · From $75/Day",
  "h1_city":"Tulsa, OK","h1_sub":"Oil Capital of the World · Tulsa County",
  "meta_desc":"Portable toilet rental Tulsa OK from $75/day. Serving Tulsa State Fair, energy sector construction, Broken Arrow growth corridor & BOK Center events. Call (833) 652-9344.",
  "og_title":"Tulsa OK Porta Potty Rentals | Oil Capital | Same-Day Delivery",
  "og_desc":"Tulsa portable toilet rental for energy construction, Tulsa State Fair, Gathering on the Green events, and Broken Arrow corridor development. Same-day delivery.",
  "services_intro":"From the Gathering on the Green at Guthrie Green and BOK Center events to pipeline construction along the Osage Nation corridor and the booming Broken Arrow commercial buildout, FixPilot delivers portable sanitation solutions across all of Tulsa County and the Green Country region.",
  "demand_para":"Tulsa's energy economy never truly rests. The city's pipeline infrastructure — ONEOK's Tulsa headquarters, Williams Companies, and dozens of midstream operators — generates constant maintenance and expansion construction that requires field-ready portable toilets. Catoosa Port's inland waterway terminal is one of the most active in the nation. Broken Arrow's residential and commercial growth has made it one of Oklahoma's fastest-growing cities, with construction starts that rival the OKC suburbs.",
  "event_para":"The Tulsa State Fair draws 1.1 million visitors annually. The Gathering on the Green at Guthrie Green, Oktoberfest Tulsa, and the Philbrook Museum outdoor events create consistent fall seasonal demand. Jenks and Bixby's riverside wedding venues are among the most in-demand luxury restroom trailer markets in Oklahoma.",
  "areas":["Broken Arrow","Owasso","Jenks","Bixby","Sand Springs","Sapulpa","Claremore","Catoosa","Glenpool","Collinsville"],
  "nearby_text":"Broken Arrow, Owasso, Jenks, Bixby, Sand Springs",
  "county_nearby":"Tulsa County","wiki_city":"Tulsa,_Oklahoma","mapq":"Tulsa+OK+74103",
  "reviews":[
    ("Ray B., Pipeline Contractor","★★★★★","ONEOK pipeline expansion through Tulsa and Osage counties — remote sites, rough roads, sometimes no cell service. FixPilot delivers and services without complaint. Their drivers know how to find a GPS-dark lease road."),
    ("Donna K., State Fair Operations","★★★★★","Tulsa State Fair — 50 units, 11 days, 1.1 million visitors. FixPilot services twice daily during peak weekend attendance. Clean units every morning when gates open. Year 3 with FixPilot and we're not switching."),
    ("Mark T., Broken Arrow Developer","★★★★★","Six residential subdivisions in Broken Arrow simultaneously. FixPilot coordinates across all sites, delivers on schedule, and the OSHA paperwork is always ready. Best construction sanitation vendor in Tulsa."),
    ("Jessica R., Wedding Planner","★★★★★","Riverside venue in Jenks — 190 guests. Two luxury trailers. The units had real wood accents and the cleanest interiors I've ever seen in a portable restroom. Guests asked me who the vendor was."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Tulsa?","Standard units from $75/day or $195/week in Tulsa County. Energy/pipeline site units from $95/week depending on site remoteness. Luxury trailers from $575/event. Broken Arrow and Owasso carry no premium over Tulsa rates."),
    ("Do you serve Broken Arrow and Owasso?","Yes. Broken Arrow is one of our highest-demand service areas due to its rapid commercial and residential growth. We cover all of Tulsa County plus Rogers, Creek, Wagoner, and Mayes counties."),
    ("Do you supply pipeline and energy sites?","Yes. We supply field-ready portable toilets to pipeline construction, midstream facility maintenance, and refinery turnaround projects across Tulsa County and the surrounding Green Country region."),
    ("Do you serve the Tulsa State Fair?","Yes. We supply and service units at the Tulsa Expo Square grounds for State Fair and major events. Contact us 4+ weeks in advance for large fair orders."),
    ("Are your units Oklahoma OSHA compliant?","Yes. All units meet Oklahoma Department of Labor and federal OSHA 29 CFR 1926.51 standards. Documentation provided with every construction order."),
    ("Do you serve Jenks and Bixby for events?","Yes. The Jenks-Bixby riverside corridor is a popular wedding and event market we serve regularly. Luxury restroom trailers are frequently booked for these venues."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Tulsa y todo el condado de Tulsa."),
    ("What's the minimum rental period?","One day for events; weekly contracts most economical for ongoing Tulsa-area construction."),
  ],
  "related_cities":[("Oklahoma City OK","oklahoma-city-ok"),("Oklahoma County OK","oklahoma-county-ok"),("Oklahoma","oklahoma")],
},

"salt-lake-city-ut": {
  "name":"Salt Lake City","state":"UT","state_name":"Utah","county":"Salt Lake County",
  "lat":40.7608,"lon":-111.8910,"zip":"84101","address":"451 S State St",
  "theme":"#7c3aed","colors":("#f5f3ff","#ede9fe","#c4b5fd","#8b5cf6","#7c3aed","#6d28d9","#5b21b6","#4c1d95"),
  "hero_img":HEROES[7],
  "title":"Porta Potty Rental Salt Lake City, UT — Silicon Slopes · From $75/Day",
  "h1_city":"Salt Lake City, UT","h1_sub":"Silicon Slopes · Salt Lake County",
  "meta_desc":"Portable toilet rental Salt Lake City UT from $75/day. Serving Silicon Slopes tech construction, ski resort events, Salt Lake County job sites & Pioneer Day. Call (833) 652-9344.",
  "og_title":"Salt Lake City UT Porta Potty Rentals | Silicon Slopes | Same-Day",
  "og_desc":"Salt Lake City portable toilet rental for Silicon Slopes construction, ski resort events, and Salt Lake County job sites. Same-day delivery across Utah. Call (833) 652-9344.",
  "services_intro":"From the Silicon Slopes tech campus buildout in Lehi and South Jordan to Olympic Park events in Park City, Pioneer Day parade sanitation on South Temple, and ski resort construction from Alta to Snowbird, FixPilot delivers reliable portable sanitation across the Wasatch Front.",
  "demand_para":"Utah's economy is one of the fastest-growing in the nation. The Silicon Slopes corridor — stretching from Lehi north to Salt Lake City — has attracted Adobe, Qualtrics, Goldman Sachs, and dozens of mid-size tech companies, each building or expanding headquarters campuses. The Point of the Mountain development in Draper is projected to add 14,000+ jobs and tens of thousands of housing units. Salt Lake County's construction permit volume has broken state records four consecutive years.",
  "event_para":"Pioneer Day (July 24) is Utah's biggest annual celebration — larger than the 4th of July in many Salt Lake neighborhoods. The Days of '47 Parade and associated events require hundreds of portable sanitation units citywide. The Sundance Film Festival in Park City, Utah Jazz game-day operations, and ski resort events from Snowbird to Park City Mountain create year-round demand for our fleet.",
  "areas":["South Jordan","Sandy","Murray","West Valley City","Lehi","Draper","Taylorsville","Ogden","Provo","West Jordan"],
  "nearby_text":"South Jordan, Sandy, Lehi, Draper, Murray",
  "county_nearby":"Salt Lake County","wiki_city":"Salt_Lake_City","mapq":"Salt+Lake+City+UT+84101",
  "reviews":[
    ("Blake N., Silicon Slopes Contractor","★★★★★","Adobe campus expansion in Lehi — phased construction over 18 months. FixPilot coordinated delivery and service across three active phases simultaneously. Clean units, OSHA documentation current, never a problem."),
    ("Sister Jensen, Pioneer Day Coordinator","★★★★★","Pioneer Day parade staging on South Temple — 50 units, 6 AM delivery, zero traffic interference. FixPilot has served this event for three years. They understand the timeline and the stakes. Absolutely professional."),
    ("Chris A., Ski Resort Developer","★★★★★","Snowbird base village expansion — high elevation, tight access roads, hard winters. FixPilot's cold-weather units performed flawlessly. Their drivers know Cottonwood Canyon conditions."),
    ("Amber T., Wedding Coordinator","★★★★★","Outdoor wedding at a Draper hillside estate — Salt Lake Valley views, 200 guests. The luxury trailer was stunning and matched the venue aesthetic. Best vendor decision I made for this event."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Salt Lake City?","Standard units from $75/day or $199/week in Salt Lake County. Silicon Slopes (Utah County) pricing is identical. Ski resort and high-elevation delivery may carry an access fee. Luxury trailers from $595/event."),
    ("Do you serve the Silicon Slopes corridor in Lehi?","Yes. Lehi and the Utah County tech corridor (American Fork, Pleasant Grove, Vineyard) are primary service areas. Same-day delivery is available for most Silicon Slopes locations."),
    ("Do you have cold-weather units for Utah winters?","Yes. We offer cold-weather portable toilets with antifreeze-treated tanks and insulated interiors rated for Utah mountain conditions. Available for Cottonwood Canyon, Park City, and all high-elevation sites."),
    ("Do you serve Park City and the Wasatch Back?","Yes. Park City, Heber City, and the Wasatch Back are within our service area. Sundance Film Festival and ski resort events are served with advance booking."),
    ("Are your units compliant with Utah OSHA?","Yes. All units meet Utah Labor Commission OSHA requirements and federal OSHA 29 CFR 1926.51 standards. Documentation provided with every construction order."),
    ("Do you serve Ogden and Weber County?","Yes. Ogden and Weber County are within our service area. Layton, Clearfield (Hill AFB area), and the northern Wasatch Front are all covered."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Salt Lake City y todo el condado de Salt Lake."),
    ("What's the minimum rental period?","One day for events; weekly contracts most economical for Wasatch Front construction sites."),
  ],
  "related_cities":[("Salt Lake County UT","salt-lake-county-ut"),("Provo UT","provo-ut"),("Utah","utah")],
},

"provo-ut": {
  "name":"Provo","state":"UT","state_name":"Utah","county":"Utah County",
  "lat":40.2338,"lon":-111.6585,"zip":"84601","address":"351 W Center St",
  "theme":"#0284c7","colors":("#f0f9ff","#e0f2fe","#7dd3fc","#0ea5e9","#0284c7","#0369a1","#075985","#0c4a6e"),
  "hero_img":HEROES[8],
  "title":"Porta Potty Rental Provo, UT — Silicon Slopes South · From $75/Day",
  "h1_city":"Provo, UT","h1_sub":"Silicon Slopes South · Utah County",
  "meta_desc":"Portable toilet rental Provo UT from $75/day. Serving BYU construction, Samsung Taylor fab, Silicon Slopes tech campuses & Utah Valley events. Call (833) 652-9344.",
  "og_title":"Provo UT Porta Potty Rentals | Silicon Slopes | BYU & Samsung",
  "og_desc":"Provo UT portable toilet rental for BYU campus construction, Samsung Taylor semiconductor fab, and Utah County job sites. Same-day delivery. Call (833) 652-9344.",
  "services_intro":"From Brigham Young University campus expansion and the Samsung Taylor semiconductor fab in Williamson County to Saratoga Springs master-planned community construction and BYU Cougar Stadium events, FixPilot delivers clean portable sanitation across Utah County and the heart of the Silicon Slopes.",
  "demand_para":"Utah County is the fastest-growing county by percentage in America. Samsung's $17 billion fab in Taylor is the largest foreign direct investment in Texas history — its supply chain extends into Utah County with dozens of Tier-1 and Tier-2 semiconductor supplier facilities under construction. BYU's enrollment growth funds constant campus building. Eagle Mountain's new housing developments are breaking ground faster than infrastructure can follow.",
  "event_para":"BYU Cougar football games fill LaVell Edwards Stadium with 64,000+ fans. The Stadium of Fire Independence Day concert, America's Freedom Festival in Provo, and Utah Valley's outdoor wedding season create consistent summer event portable toilet demand across the county.",
  "areas":["Orem","American Fork","Pleasant Grove","Springville","Spanish Fork","Payson","Eagle Mountain","Saratoga Springs","Lehi","Mapleton"],
  "nearby_text":"Orem, American Fork, Springville, Eagle Mountain, Saratoga Springs",
  "county_nearby":"Utah County","wiki_city":"Provo,_Utah","mapq":"Provo+UT+84601",
  "reviews":[
    ("Brent H., BYU Facilities Contractor","★★★★★","BYU campus construction — multiple projects, strict event-calendar delivery restrictions, high visibility. FixPilot coordinates with our schedule and has never created a problem at one of the most watched campuses in the state."),
    ("Jared T., Samsung Supplier Build","★★★★★","Construction of a Samsung-supply fab in Lehi. First-ever project for this client in Utah — they had high expectations. FixPilot delivered OSHA paperwork same-day and serviced on a schedule that matched our shift rotations."),
    ("Emily S., Eagle Mountain HOA","★★★★★","Community park grand opening — 800 families, outdoor event. FixPilot delivered 10 units the morning of the event and retrieved them that evening. Clean, fast, professional. Perfect for a community-facing event."),
    ("Rachel L., Wedding Planner","★★★★★","Outdoor Utah Lake wedding in Saratoga Springs — 220 guests. The luxury trailer had Wasatch Mountain views from its positioning. FixPilot placed it perfectly and serviced mid-reception without anyone noticing."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Provo?","Standard units from $75/day or $199/week in Utah County. Luxury restroom trailers from $595/event. Eagle Mountain and Saratoga Springs carry the same base rate — no rural premium for most Utah County locations."),
    ("Do you serve the Samsung Taylor fab supply chain in Lehi?","Yes. We supply portable sanitation to semiconductor supplier construction sites throughout Utah County. Lehi's Silicon Slopes corridor is one of our highest-demand service areas."),
    ("Do you serve BYU events and construction?","Yes. We coordinate with BYU Facilities Management for both construction site service and campus event sanitation. Event-calendar delivery restrictions are part of our standard BYU protocol."),
    ("Do you cover Eagle Mountain and Saratoga Springs?","Yes. Eagle Mountain and Saratoga Springs — Utah County's fastest-growing communities — are primary service areas. Same-day delivery is available for most locations."),
    ("Are your units Utah OSHA compliant?","Yes. All units meet Utah Labor Commission OSHA standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Spanish Fork and Payson?","Yes. We cover all of southern Utah County including Springville, Spanish Fork, Payson, and Salem."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Provo y todo el condado de Utah."),
    ("What's the minimum rental period?","One day for events; weekly contracts most economical for Utah County construction sites."),
  ],
  "related_cities":[("Salt Lake City UT","salt-lake-city-ut"),("Salt Lake County UT","salt-lake-county-ut"),("Utah","utah")],
},

"roanoke-va": {
  "name":"Roanoke","state":"VA","state_name":"Virginia","county":"Roanoke County",
  "lat":37.2710,"lon":-79.9414,"zip":"24011","address":"215 Church Ave SW",
  "theme":"#0369a1","colors":("#eff6ff","#dbeafe","#93c5fd","#3b82f6","#2563eb","#1d4ed8","#1e40af","#1e3a8a"),
  "hero_img":HEROES[9],
  "title":"Porta Potty Rental Roanoke, VA — Star City · Same-Day · From $75/Day",
  "h1_city":"Roanoke, VA","h1_sub":"Star City of the South · Blue Ridge",
  "meta_desc":"Portable toilet rental Roanoke VA from $75/day. Serving Roanoke Valley construction, Blue Ridge Parkway events, Virginia's Blue Ridge outdoor festivals & Salem job sites. Call (833) 652-9344.",
  "og_title":"Roanoke VA Porta Potty Rentals | Star City | Blue Ridge Events",
  "og_desc":"Roanoke VA portable toilet rental for Blue Ridge Parkway events, Valley construction, and Salem sports venues. Same-day delivery across the Roanoke Valley.",
  "services_intro":"From Carilion Clinic campus expansion and the emerging Roanoke Innovation Corridor along Jefferson Street to Blue Ridge Parkway outdoor events and outdoor concerts at Elmwood Park, FixPilot serves all of Roanoke Valley's portable sanitation needs.",
  "demand_para":"Roanoke is experiencing its most significant economic revival since the Norfolk & Western Railway era. Carilion Clinic — the dominant employer and the anchor of the Roanoke Biomedical Innovation Corridor — is building new medical towers and research facilities. Virginia Tech's Carilion School of Medicine campus continues to expand. The city's downtown core is seeing adaptive reuse projects that have transformed former warehouse blocks into tech offices and hospitality venues, all requiring construction portable toilets.",
  "event_para":"Virginia's Blue Ridge Parkway corridor draws millions of visitors annually for cycling events, trail races, and outdoor festivals. The Roanoke GO Outside Festival, Elmwood Park Music Series, and Roanoke River Greenway events create consistent warm-weather event rental demand. Our luxury restroom trailers are popular for mountain vineyard weddings and private estate events across Roanoke, Botetourt, and Floyd counties.",
  "areas":["Salem","Vinton","Botetourt County","Bedford County","Floyd County","Christiansburg","Blacksburg","Radford","Lynchburg","Lexington"],
  "nearby_text":"Salem, Vinton, Botetourt County, Christiansburg, Blacksburg",
  "county_nearby":"Roanoke County","wiki_city":"Roanoke,_Virginia","mapq":"Roanoke+VA+24011",
  "reviews":[
    ("Paul M., Carilion Contractor","★★★★★","Carilion Roanoke Memorial Hospital expansion — hospital-adjacent delivery, strict infection control zones, zero tolerance for service disruption. FixPilot has understood these requirements from day one. 12 months, zero issues."),
    ("Karen T., Blue Ridge Events","★★★★★","GO Outside Festival at Elmwood Park — 18 units, 3 days, thousands of outdoor recreation enthusiasts. Serviced each morning before 7 AM. Clean and odor-free in late September heat. FixPilot handled it perfectly."),
    ("Tom S., Salem Developer","★★★★★","Commercial project in Salem near Haley Toyota Field. FixPilot delivers reliably to a site that has limited truck access. Drivers problem-solve instead of complaining. That's worth a lot."),
    ("Mary H., Mountain Wedding Planner","★★★★★","Private estate wedding in Botetourt County — mountain views, 160 guests. The luxury trailer was the one amenity I was most worried about. FixPilot exceeded every expectation. Perfect placement, spotless condition."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Roanoke?","Standard units from $75/day or $195/week in Roanoke and Roanoke County. Salem and Vinton carry the same rate. Botetourt and Bedford county deliveries available with advance notice. Luxury trailers from $575/event."),
    ("Do you serve Salem and Vinton?","Yes. Salem and Vinton are primary service areas with same-day delivery available. We serve all of Roanoke Metropolitan Statistical Area including Roanoke, Salem, Roanoke County, and Vinton."),
    ("Do you cover the New River Valley (Christiansburg, Blacksburg)?","Yes. Christiansburg, Blacksburg, and Virginia Tech events are within our service area. NRV delivery may require advance scheduling for same-day service."),
    ("Are your units Virginia OSHA (VOSH) compliant?","Yes. All units meet VOSH and federal OSHA 29 CFR 1926.51 standards. Documentation provided with every construction order."),
    ("Do you serve Blue Ridge Parkway events?","Yes. We serve trail race events, cycling events, and outdoor festivals along the Blue Ridge Parkway corridor in Roanoke, Floyd, and Patrick counties."),
    ("Can I get luxury trailers for a Blue Ridge mountain wedding?","Yes. Our luxury trailers are self-contained and designed for rural venue access. We regularly serve mountain estate, vineyard, and Blue Ridge Parkway-adjacent wedding venues."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Roanoke y todo el Valle de Roanoke."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for ongoing Roanoke-area construction."),
  ],
  "related_cities":[("Richmond VA","richmond-va"),("Virginia Beach VA","virginia-beach-va"),("Virginia","virginia")],
},
}

def main():
    built = 0
    for slug, d in CITIES_B2.items():
        outdir = Path(f"porta-potty-rental-{slug}")
        outfile = outdir / "index.html"
        outdir.mkdir(exist_ok=True)
        html = build_page(slug, d)
        outfile.write_text(html, encoding="utf-8")
        print(f"  ✓ {slug} ({len(html):,} chars)")
        built += 1
    print(f"\nBuilt {built} city pages")

if __name__ == "__main__":
    main()
