#!/usr/bin/env python3
"""Batch 3: Fayetteville AR, Little Rock AR, Omaha NE, Des Moines IA,
   Lakeland FL, Sarasota FL, Pensacola FL, Jackson MS, Biloxi MS."""

import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from build_unique_cities import build_page, HEROES
from pathlib import Path

CITIES_B3 = {

"fayetteville-ar": {
  "name":"Fayetteville","state":"AR","state_name":"Arkansas","county":"Washington County",
  "lat":36.0626,"lon":-94.1574,"zip":"72701","address":"113 W Mountain St",
  "theme":"#dc2626","colors":("#fef2f2","#fee2e2","#fca5a5","#ef4444","#dc2626","#b91c1c","#991b1b","#7f1d1d"),
  "hero_img":HEROES[0],
  "title":"Porta Potty Rental Fayetteville, AR — Razorback Country · From $75/Day",
  "h1_city":"Fayetteville, AR","h1_sub":"Razorback Country · NW Arkansas Tech Hub",
  "meta_desc":"Portable toilet rental Fayetteville AR from $75/day. Serving Walmart HQ, Razorback Stadium, NW Arkansas construction & Washington County job sites. Call (833) 652-9344.",
  "og_title":"Fayetteville AR Porta Potty Rentals | Razorback Country | Same-Day",
  "og_desc":"Fayetteville AR portable toilet rental for Walmart HQ construction, Razorback Stadium events, and NW Arkansas tech corridor. Same-day delivery. Call (833) 652-9344.",
  "services_intro":"From Walmart Global Technology campus in Bentonville and the booming Rogers-Springdale industrial corridor to Razorback Stadium tailgates at the University of Arkansas and Crystal Bridges outdoor events, FixPilot delivers clean portable sanitation across all of Northwest Arkansas.",
  "demand_para":"Northwest Arkansas has transformed from a regional hub into one of America's most dynamic tech and logistics ecosystems. Walmart's global headquarters in Bentonville anchors a supplier ecosystem that requires millions of square feet of new office and warehouse construction annually. The NWA Council's regional plan has attracted Meta, Microsoft, and Walmart's home-grown tech spinoffs, each expanding their footprints. The area's housing shortage — one of the worst in the Mountain South — is driving massive residential construction in Springdale, Lowell, Cave Springs, and Centerton.",
  "event_para":"University of Arkansas Razorback football games at Donald W. Reynolds Razorback Stadium draw 72,000 fans, generating massive tailgate event demand. Bikes, Blues & BBQ motorcycle rally draws 400,000+. Crystal Bridges Museum outdoor events and the Walmart AMP amphitheater create year-round entertainment rental demand across Benton County.",
  "areas":["Springdale","Rogers","Bentonville","Siloam Springs","Fort Smith","Lowell","Cave Springs","Centerton","Farmington","Elkins"],
  "nearby_text":"Springdale, Rogers, Bentonville, Lowell, Siloam Springs",
  "county_nearby":"Washington County","wiki_city":"Fayetteville,_Arkansas","mapq":"Fayetteville+AR+72701",
  "reviews":[
    ("Lisa T., Walmart Supplier PM","★★★★★","New office campus for a Walmart supplier in Rogers — 18-month build. FixPilot serviced 12 units weekly without a single missed appointment. In NWA's tight construction market that reliability is everything."),
    ("Coach D. Harmon, UA Athletics Contractor","★★★★★","Razorback Stadium renovation staging area. FixPilot coordinated around game-day schedules and strict facilities access windows. They know how a D1 athletics department operates. Impressive."),
    ("Amber W., Crystal Bridges Events","★★★★★","Frank Lloyd Wright outdoor concert series — 8 units over 6 weeks. Serviced every morning before visitors arrived. The museum grounds stayed pristine. FixPilot understood what the Crystal Bridges brand requires."),
    ("Jason M., Homebuilder","★★★★★","Building in Cave Springs and Centerton simultaneously. FixPilot keeps up with the pace of NWA's construction market better than any vendor I've used. Delivers on time, services on schedule, never an excuse."),
  ],
  "faqs":[
    ("Do you serve Bentonville and the Walmart HQ area?","Yes. Bentonville is one of our primary service areas. We serve Walmart campus contractor teams, supplier office builds, and all active construction in Benton County. Same-day delivery available."),
    ("How much does portable toilet rental cost in Fayetteville, AR?","Standard units from $75/day or $195/week in Washington County. Benton County (Rogers, Bentonville, Springdale) pricing is identical. Luxury trailers from $575/event."),
    ("Do you cover Razorback Stadium and UA events?","Yes. We serve University of Arkansas events, tailgate zones, and campus construction. For Razorback home game orders, contact us 3+ weeks in advance."),
    ("Do you serve the Fort Smith area?","Yes. Fort Smith and Sebastian County are within our extended service area. Same-day delivery may require advance scheduling for Fort Smith locations."),
    ("Are your units Arkansas Department of Labor compliant?","Yes. All units meet Arkansas OSHA standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Fayetteville y todo el noroeste de Arkansas."),
    ("What's the minimum rental period?","One day for events; weekly contracts most economical for NWA construction sites."),
    ("Do you serve Siloam Springs and Gentry?","Yes. All of western Washington County and eastern Benton County, including the Arkansas-Oklahoma border corridor, is within our service area."),
  ],
  "related_cities":[("Little Rock AR","little-rock-ar"),("Arkansas","arkansas")],
},

"little-rock-ar": {
  "name":"Little Rock","state":"AR","state_name":"Arkansas","county":"Pulaski County",
  "lat":34.7465,"lon":-92.2896,"zip":"72201","address":"500 W Markham St",
  "theme":"#0284c7","colors":("#f0f9ff","#e0f2fe","#7dd3fc","#0ea5e9","#0284c7","#0369a1","#075985","#0c4a6e"),
  "hero_img":HEROES[1],
  "title":"Porta Potty Rental Little Rock, AR — Capital City · Same-Day · From $75",
  "h1_city":"Little Rock, AR","h1_sub":"Natural State Capital · Pulaski County",
  "meta_desc":"Portable toilet rental Little Rock AR from $75/day. Serving Pulaski County construction, Riverfront Park events, I-30 corridor development & Arkansas River projects. Call (833) 652-9344.",
  "og_title":"Little Rock AR Porta Potty Rentals | Capital City | Same-Day Delivery",
  "og_desc":"Little Rock portable toilet rental for Pulaski County construction, Riverfront Park events, and I-30 corridor development. Same-day delivery across Central Arkansas.",
  "services_intro":"From the I-30 bridge reconstruction and the Arkansas River Trail events at Riverfront Park to UAMS hospital expansion in the Medical District and the Argenta Arts District redevelopment in North Little Rock, FixPilot serves all of Central Arkansas's portable sanitation needs.",
  "demand_para":"Little Rock's construction pipeline is driven by the state's largest infrastructure project in decades: the I-30 Crossing reconstruction over the Arkansas River. Simultaneously, the University of Arkansas for Medical Sciences (UAMS) is expanding its hospital campus in the Medical District, the Port of Little Rock industrial corridor is growing, and the Route 10 commercial corridor in west Little Rock is seeing its highest construction volume in 20 years.",
  "event_para":"Little Rock Riverfront Park hosts the Greek Food Festival, Riverfest remnant events, and the Arkansas Times Blues Festival. Dickey-Stephens Park (Arkansas Travelers baseball) and the Simmons Bank Arena event calendar create consistent seasonal demand. The west Little Rock country club and lake-area wedding market generates luxury restroom trailer bookings spring through fall.",
  "areas":["North Little Rock","Conway","Maumelle","Benton","Bryant","Sherwood","Jacksonville","Cabot","Searcy","Pine Bluff"],
  "nearby_text":"North Little Rock, Conway, Maumelle, Benton, Bryant",
  "county_nearby":"Pulaski County","wiki_city":"Little_Rock,_Arkansas","mapq":"Little+Rock+AR+72201",
  "reviews":[
    ("Greg K., I-30 Bridge Contractor","★★★★★","I-30 Crossing project — urban bridge construction with no room for error on service timing. FixPilot handles the delivery windows, the river corridor access permits, and the OSHA documentation without a single gap. Remarkable."),
    ("Donna M., UAMS Facilities","★★★★★","UAMS hospital wing construction adjacent to active clinical areas. FixPilot's drivers understand infection control zones and never breach the boundaries. That's a level of professionalism other vendors don't have."),
    ("Mike T., West Little Rock Builder","★★★★★","Three subdivisions in west Little Rock simultaneously. FixPilot delivers to all three on the same rotation. Never short, never late. Best sanitation vendor I've used in Arkansas."),
    ("Jennifer S., Event Planner","★★★★★","Arkansas Times Blues Festival at Riverfront Park — 10 units, one-day event. Delivered at 7 AM, retrieved at midnight. Everything was clean throughout. I'll use FixPilot for every Central Arkansas event."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Little Rock?","Standard units from $75/day or $195/week in Pulaski County. North Little Rock, Maumelle, and Saline County (Benton, Bryant) pricing is identical. Luxury trailers from $575/event."),
    ("Do you serve North Little Rock and Maumelle?","Yes. North Little Rock and Maumelle are primary service areas. We cover all of Pulaski County plus Saline, Faulkner, Lonoke, and White counties."),
    ("Do you cover the I-30 corridor construction?","Yes. The I-30 bridge reconstruction corridor is one of our most active service areas. We coordinate with ARDOT-approved contractor teams on delivery windows and site access protocols."),
    ("Are your units Arkansas OSHA compliant?","Yes. All units meet Arkansas Department of Labor standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Conway and Faulkner County?","Yes. Conway is within our primary service area. Same-day delivery is available for most Faulkner County locations."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Little Rock y todo el condado de Pulaski."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for ongoing Little Rock construction."),
    ("Do you serve Pine Bluff and Jefferson County?","Yes. Pine Bluff is within our extended service area. Contact us for project-specific scheduling."),
  ],
  "related_cities":[("Fayetteville AR","fayetteville-ar"),("Arkansas","arkansas")],
},

"omaha-ne": {
  "name":"Omaha","state":"NE","state_name":"Nebraska","county":"Douglas County",
  "lat":41.2565,"lon":-95.9345,"zip":"68102","address":"1819 Farnam St",
  "theme":"#dc2626","colors":("#fef2f2","#fee2e2","#fca5a5","#ef4444","#dc2626","#b91c1c","#991b1b","#7f1d1d"),
  "hero_img":HEROES[2],
  "title":"Porta Potty Rental Omaha, NE — River City · Same-Day · From $75/Day",
  "h1_city":"Omaha, NE","h1_sub":"River City · College World Series Capital",
  "meta_desc":"Portable toilet rental Omaha NE from $75/day. Serving College World Series, Offutt AFB contractors, Douglas County construction & Missouri River events. Call (833) 652-9344.",
  "og_title":"Omaha NE Porta Potty Rentals | River City | CWS & Construction",
  "og_desc":"Omaha portable toilet rental for College World Series, Offutt AFB construction, and Douglas County job sites. Same-day delivery to Bellevue, Papillion, Council Bluffs.",
  "services_intro":"From the College World Series at Charles Schwab Field and Offutt Air Force Base contractor construction in Bellevue to the Midtown Crossing mixed-use development and the booming Sarpy County residential buildout in Papillion, FixPilot serves all of Omaha metro's portable sanitation needs.",
  "demand_para":"Omaha's economy is built on financial services, defense, and distribution — all of which are in an active construction phase. Warren Buffett's Berkshire Hathaway campus in midtown is perpetually expanding. Amazon, FedEx, and UPS have invested in major distribution fulfillment centers along the I-80 corridor east of Omaha. Offutt AFB's U.S. Strategic Command headquarters is undergoing a billion-dollar renovation. And Sarpy County — the fastest-growing county in Nebraska — is adding residential subdivisions faster than any market in the Plains.",
  "event_para":"The NCAA College World Series at Charles Schwab Field is one of the highest-attended baseball events in America, drawing 300,000+ over two weeks in June. The Omaha Rides cycling festival, the Berkshire Hathaway Annual Meeting (bringing 40,000 investors to Omaha), and the College World Series hospitality village create massive portable sanitation demand annually.",
  "areas":["Bellevue","Papillion","La Vista","Council Bluffs IA","Elkhorn","Gretna","Ralston","Millard","Fremont","Blair"],
  "nearby_text":"Bellevue, Papillion, La Vista, Council Bluffs IA, Elkhorn",
  "county_nearby":"Douglas County","wiki_city":"Omaha,_Nebraska","mapq":"Omaha+NE+68102",
  "reviews":[
    ("Sarah B., CWS Operations","★★★★★","College World Series hospitality village at Charles Schwab Field — 25 units, 14 days, 300,000+ total visitors. FixPilot serviced twice daily at peak weekend attendance. Zero odor complaints across two weeks. That's exceptional."),
    ("Lt. Col. Jensen (ret.), Offutt Contractor","★★★★★","USSTRATCOM renovation at Offutt AFB. DoD base access, CAC requirements, zero-fault delivery protocols. FixPilot handled every requirement correctly from day one. Rare competence for a sanitation vendor on a federal site."),
    ("Dave R., Sarpy County Builder","★★★★★","Running six subdivisions in Papillion and Gretna. FixPilot coordinates across all six sites without me having to manage them. They show up, service reliably, and the OSHA paperwork is always current. Perfect."),
    ("Amanda T., Event Planner","★★★★★","Berkshire Hathaway Annual Meeting hospitality event — 300 guests, outdoor venue near Qwest Center. FixPilot delivered two luxury trailers that the Berkshire crowd actually noticed and appreciated. High bar, met easily."),
  ],
  "faqs":[
    ("Do you serve the College World Series?","Yes. The CWS at Charles Schwab Field is one of our signature annual events. We supply and service units for both the stadium perimeter and the CWS hospitality village. Pre-booking by April is recommended for June orders."),
    ("How much does portable toilet rental cost in Omaha?","Standard units from $75/day or $195/week in Douglas County. Sarpy County (Bellevue, Papillion) and Council Bluffs IA carry the same rate. Luxury trailers from $575/event."),
    ("Do you serve Offutt AFB and Bellevue?","Yes. We supply contractor teams at Offutt Air Force Base with portable sanitation. We coordinate with base access protocols and can provide documentation for DoD inspections."),
    ("Do you cover Council Bluffs, Iowa?","Yes. Council Bluffs and Pottawattamie County, Iowa are within our service area. Cross-state delivery carries no fee for most Council Bluffs locations."),
    ("Are your units Nebraska DEQ and OSHA compliant?","Yes. All units meet Nebraska Department of Environment and Energy standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you cover Elkhorn and Gretna?","Yes. The western Douglas County and Sarpy County growth corridor — Elkhorn, Gretna, Papillion, and La Vista — are primary service areas."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Omaha y todo el condado de Douglas."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for ongoing Omaha construction."),
  ],
  "related_cities":[("Douglas County NE","douglas-county-ne"),("Nebraska","nebraska")],
},

"des-moines-ia": {
  "name":"Des Moines","state":"IA","state_name":"Iowa","county":"Polk County",
  "lat":41.5868,"lon":-93.6250,"zip":"50309","address":"400 Robert D Ray Dr",
  "theme":"#0284c7","colors":("#f0f9ff","#e0f2fe","#7dd3fc","#0ea5e9","#0284c7","#0369a1","#075985","#0c4a6e"),
  "hero_img":HEROES[3],
  "title":"Porta Potty Rental Des Moines, IA — Capital City · Same-Day · From $75",
  "h1_city":"Des Moines, IA","h1_sub":"Iowa Capital · Polk County",
  "meta_desc":"Portable toilet rental Des Moines IA from $75/day. Serving Iowa State Fair, Polk County construction, Ankeny industrial corridor & Des Moines River events. Call (833) 652-9344.",
  "og_title":"Des Moines IA Porta Potty Rentals | Iowa State Fair | Same-Day Delivery",
  "og_desc":"Des Moines portable toilet rental for Iowa State Fair, Ankeny industrial construction, and Polk County job sites. Same-day delivery across Central Iowa. Call (833) 652-9344.",
  "services_intro":"From the Iowa State Fairgrounds on the east side and Wells Fargo Arena events downtown to the Amazon and Microsoft data center buildout in Altoona and the Waukee commercial growth corridor, FixPilot delivers portable sanitation across all of Greater Des Moines.",
  "demand_para":"Des Moines is consistently ranked as one of America's best cities for business — and the construction activity proves it. Microsoft, Meta, and Google have built massive data centers in the Altoona corridor east of Des Moines, creating sustained demand for construction portable toilets in what was previously agricultural land. The Principal Financial headquarters campus, the Wellmark Blue Cross complex, and the ongoing Drake University expansion add corporate and institutional construction to an already busy market. Waukee, the fastest-growing city in Iowa, is adding housing developments at a pace the market can barely supply.",
  "event_para":"The Iowa State Fair is the largest event in Iowa, drawing 1.1 million visitors over 11 days in August — making it one of the largest state fairs in the country. RAGBRAI (Register's Annual Great Bicycle Ride Across Iowa) stages in Des Moines. The Iowa Cubs at Principal Park and the Kinnick Stadium tailgate market in Iowa City draw consistent event portable toilet demand seasonally.",
  "areas":["Ankeny","Waukee","West Des Moines","Urbandale","Johnston","Altoona","Clive","Ames","Indianola","Bondurant"],
  "nearby_text":"Ankeny, Waukee, West Des Moines, Urbandale, Altoona",
  "county_nearby":"Polk County","wiki_city":"Des_Moines,_Iowa","mapq":"Des+Moines+IA+50309",
  "reviews":[
    ("Tom F., Iowa State Fair","★★★★★","Iowa State Fair — the largest event in the state. FixPilot has supplied and serviced units at the fairgrounds for multiple years. They understand the volume, the timeline, and the standards the Fair demands. Consistent excellence."),
    ("Megan A., Data Center Contractor","★★★★★","Microsoft Altoona data center campus — phased construction, secure site, strict vendor protocols. FixPilot delivered credentialing documentation same-day and has never once failed a service visit in 16 months."),
    ("Ryan B., Waukee Builder","★★★★★","Building in Waukee — Iowa's fastest-growing city. Construction moves fast here. FixPilot keeps up, delivers on time to new streets that aren't yet on any map, and services without being chased. Perfect partner."),
    ("Lisa N., Wedding Planner","★★★★★","Outdoor wedding at an Indianola vineyard — 200 Iowa guests with high expectations. Two luxury trailers. Guests kept pointing them out as a highlight. In Iowa that's saying something."),
  ],
  "faqs":[
    ("Do you serve the Iowa State Fair?","Yes. The Iowa State Fairgrounds is one of our signature annual service accounts. We supply units for the 11-day fair in August. Pre-booking by June is essential — State Fair inventory fills early."),
    ("How much does portable toilet rental cost in Des Moines?","Standard units from $75/day or $195/week in Polk County. Ankeny, Waukee, Altoona, and West Des Moines carry the same base rate. Luxury trailers from $575/event."),
    ("Do you serve Ankeny and the I-35 industrial corridor?","Yes. Ankeny is one of our highest-demand service areas. We cover the full I-35 north corridor including Ankeny, Bondurant, Alleman, and Huxley."),
    ("Do you cover Ames and Story County?","Yes. Ames and Iowa State University are within our service area. ISU construction and Ames community events are served with advance notice."),
    ("Are your units Iowa DNR and OSHA compliant?","Yes. All units meet Iowa Department of Natural Resources portable sanitation standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve data center sites in Altoona?","Yes. The Altoona data center corridor — Microsoft, Meta, and Google campus construction — is one of our fastest-growing service segments. We understand secure site access and tech campus construction requirements."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Des Moines y todo el condado de Polk."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Des Moines area construction."),
  ],
  "related_cities":[("Iowa","iowa")],
},

"lakeland-fl": {
  "name":"Lakeland","state":"FL","state_name":"Florida","county":"Polk County",
  "lat":28.0395,"lon":-81.9498,"zip":"33801","address":"228 S Massachusetts Ave",
  "theme":"#0284c7","colors":("#f0f9ff","#e0f2fe","#7dd3fc","#0ea5e9","#0284c7","#0369a1","#075985","#0c4a6e"),
  "hero_img":HEROES[4],
  "title":"Porta Potty Rental Lakeland, FL — Swan City · Same-Day · From $75/Day",
  "h1_city":"Lakeland, FL","h1_sub":"Swan City · Polk County · I-4 Corridor",
  "meta_desc":"Portable toilet rental Lakeland FL from $75/day. Serving Polk County construction, Plant City Strawberry Festival, I-4 corridor development & Winter Haven events. Call (833) 652-9344.",
  "og_title":"Lakeland FL Porta Potty Rentals | Polk County | I-4 Corridor",
  "og_desc":"Lakeland FL portable toilet rental for I-4 corridor construction, Strawberry Festival events, and Polk County job sites. Same-day delivery across Central Florida.",
  "services_intro":"From the I-4 interchange expansion in Auburndale and Publix Super Markets' Lakeland headquarters distribution campus to the Plant City Strawberry Festival and ChampionsGate resort construction south of US-27, FixPilot delivers reliable portable sanitation across all of Polk County.",
  "demand_para":"Lakeland sits at the midpoint of Florida's I-4 corridor — the economic backbone of the Sunshine State — and is experiencing rapid industrial and residential growth driven by its position between Tampa and Orlando. Publix Supermarkets, headquartered in Lakeland, is expanding its distribution and office footprint annually. Amazon, FedEx, and USPS have major distribution centers in the I-4/Polk Parkway corridor. Poinciana — one of the fastest-growing master-planned communities in Florida — is adding thousands of housing units, driving construction demand that shows no sign of slowing.",
  "event_para":"The Florida Strawberry Festival in Plant City draws 500,000+ each spring. The SUN 'n FUN International Fly-In & Expo at Lakeland Linder Airport is one of the largest aviation events in North America. Detroit Tigers Spring Training at Joker Marchant Stadium, and the Legoland Florida events in Winter Haven create consistent seasonal event portable toilet demand across Polk County.",
  "areas":["Winter Haven","Bartow","Plant City","Haines City","Davenport","Auburndale","Poinciana","Mulberry","Fort Meade","Lake Wales"],
  "nearby_text":"Winter Haven, Plant City, Haines City, Davenport, Auburndale",
  "county_nearby":"Polk County","wiki_city":"Lakeland,_Florida","mapq":"Lakeland+FL+33801",
  "reviews":[
    ("Mark R., I-4 Contractor","★★★★★","I-4 Ultimate widening project through Polk County — massive crew, round-the-clock shifts, no tolerance for service gaps. FixPilot has been flawless for 14 months. The only sanitation vendor I trust on a FDOT project."),
    ("Carol B., Strawberry Festival","★★★★★","Florida Strawberry Festival in Plant City — 40 units over 11 days, 500,000 visitors. FixPilot serviced twice daily at peak weekend. Spotless condition throughout. We've used them three years running and they never disappoint."),
    ("Jason T., Poinciana Developer","★★★★★","Building in Poinciana — one of the most active residential communities in Florida. FixPilot delivers to new streets before they're paved and services on schedule. That adaptability is worth more than any other vendor quality."),
    ("Amy S., SUN 'n FUN Coordinator","★★★★★","SUN 'n FUN at Lakeland Linder Airport — 10-day aviation event. FixPilot coordinated delivery around flight operations and provided same-day emergency service when attendance exceeded projections. Exceptional."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Lakeland, FL?","Standard units from $75/day or $199/week in Polk County. Winter Haven, Haines City, and Auburndale carry the same rate. Luxury trailers from $595/event."),
    ("Do you serve Plant City and the Strawberry Festival?","Yes. The Florida Strawberry Festival in Plant City is a major annual event we serve. Contact us by January for March festival orders — inventory fills quickly."),
    ("Do you cover the I-4 corridor and ChampionsGate?","Yes. The I-4/US-27 commercial corridor including Davenport, ChampionsGate, and Haines City is one of our highest-demand service areas."),
    ("Do you serve the SUN 'n FUN Fly-In at Lakeland Linder?","Yes. We supply units for the SUN 'n FUN International Fly-In & Expo. Airside delivery coordination is available with advance notice."),
    ("Are your units Florida DEP and OSHA compliant?","Yes. All units meet Florida Department of Environmental Protection portable sanitation standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Poinciana and south Polk County?","Yes. Poinciana and the US-17 south Polk corridor are primary service areas. Osceola County border deliveries available."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Lakeland y todo el condado de Polk."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Polk County construction."),
  ],
  "related_cities":[("Tampa FL","tampa-fl"),("Orlando FL","orlando-fl"),("Florida","florida")],
},

"sarasota-fl": {
  "name":"Sarasota","state":"FL","state_name":"Florida","county":"Sarasota County",
  "lat":27.3364,"lon":-82.5307,"zip":"34236","address":"1565 1st St",
  "theme":"#0891b2","colors":("#ecfeff","#cffafe","#67e8f9","#06b6d4","#0891b2","#0e7490","#155e75","#164e63"),
  "hero_img":HEROES[5],
  "title":"Porta Potty Rental Sarasota, FL — Cultural Coast · Same-Day · From $75",
  "h1_city":"Sarasota, FL","h1_sub":"Cultural Coast · Siesta Key & Lakewood Ranch",
  "meta_desc":"Portable toilet rental Sarasota FL from $75/day. Serving Siesta Key beach events, Lakewood Ranch construction, luxury outdoor weddings & Sarasota County job sites. Call (833) 652-9344.",
  "og_title":"Sarasota FL Porta Potty Rentals | Cultural Coast | Luxury Trailers",
  "og_desc":"Sarasota portable toilet rental for Siesta Key events, Lakewood Ranch construction, and upscale outdoor weddings. Luxury restroom trailers available. Call (833) 652-9344.",
  "services_intro":"From Lakewood Ranch master-planned community construction and the Sarasota Memorial Hospital expansion to Siesta Key beach events, Ringling Museum outdoor festivals, and luxury estate weddings on Longboat Key, FixPilot delivers premium portable sanitation across all of the Sarasota-Manatee metro.",
  "demand_para":"Sarasota County is one of the fastest-growing counties in Florida, driven by wealthy retiree migration, remote-work relocations, and a booming luxury real estate market. Lakewood Ranch — one of the top-selling master-planned communities in the United States — is adding thousands of homes annually across Sarasota and Manatee counties, generating sustained residential and commercial construction portable toilet demand. Sarasota Memorial's hospital campus expansion, new luxury resort construction on Siesta Key, and the UTC Mall expansion in Sarasota all add to a construction market that has never been hotter.",
  "event_para":"Siesta Beach (consistently rated America's best beach) hosts the Siesta Key Crystal Classic sand sculpting festival. The Sarasota Film Festival, Ringling Museum Circus Arts events, and outdoor concerts at Sarasota's Bayfront Park create consistent seasonal demand. The Sarasota luxury wedding market — Longboat Key Club, The Ringling, and private Siesta Key estate venues — is one of the most active luxury restroom trailer markets in Florida.",
  "areas":["Siesta Key","Bradenton","Venice","North Port","Osprey","Nokomis","Longboat Key","Ellenton","Palmetto","Englewood"],
  "nearby_text":"Siesta Key, Bradenton, Venice, North Port, Osprey",
  "county_nearby":"Sarasota County","wiki_city":"Sarasota,_Florida","mapq":"Sarasota+FL+34236",
  "reviews":[
    ("Tom H., Lakewood Ranch Builder","★★★★★","Building in Lakewood Ranch across four simultaneous plats. FixPilot coordinates deliveries and service across all four with zero issues. In Florida's busy construction market that kind of reliability is rare and valuable."),
    ("Christine B., The Ringling Events","★★★★★","Ringling Museum outdoor event for 300 patrons — upscale crowd with high expectations. FixPilot's luxury trailer was museum-quality in terms of appearance. The most elegant portable restroom I've ever seen deployed."),
    ("Greg S., Siesta Key Developer","★★★★★","Luxury resort construction on Siesta Key — restricted access roads, beachfront delivery logistics, strict HOA protocols. FixPilot navigated every challenge without complaint. Outstanding vendor for barrier island construction."),
    ("Lauren M., Longboat Key Weddings","★★★★★","Longboat Key Club garden wedding — 250 guests, ultra-luxury setting. Two trailers with marble-look interiors. The mother-of-the-bride told me the restrooms were her favorite part of the venue. That's FixPilot."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Sarasota?","Standard units from $75/day or $205/week in Sarasota County. Barrier island delivery (Siesta Key, Longboat Key) carries a logistics fee. Luxury trailers from $650/event. Lakewood Ranch and Bradenton carry standard Sarasota rates."),
    ("Do you deliver to Siesta Key and Longboat Key?","Yes. We serve both barrier island venues with experience in the restricted-access logistics each requires. Island delivery fees apply — contact us for a site-specific quote."),
    ("Do you cover Manatee County and Bradenton?","Yes. Bradenton, Ellenton, Palmetto, and Manatee County are primary service areas with same-day delivery available."),
    ("Do you offer luxury restroom trailers for Sarasota weddings?","Yes. The Sarasota luxury wedding market is one of our strongest. We serve The Ringling, Longboat Key Club, Sarasota Yacht Club, and private estate venues with climate-controlled luxury trailers."),
    ("Do you serve North Port and Venice?","Yes. North Port and Venice are within our service area. Charlotte County border deliveries are available with advance notice."),
    ("Are your units Florida DEP and OSHA compliant?","Yes. All units meet Florida Department of Environmental Protection and federal OSHA 29 CFR 1926.51 standards."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Sarasota y todo el condado de Sarasota."),
    ("What is the minimum rental period?","One day minimum; weekly contracts most economical for Sarasota construction."),
  ],
  "related_cities":[("Tampa FL","tampa-fl"),("Cape Coral FL","cape-coral-fl"),("Florida","florida")],
},

"pensacola-fl": {
  "name":"Pensacola","state":"FL","state_name":"Florida","county":"Escambia County",
  "lat":30.4213,"lon":-87.2169,"zip":"32502","address":"222 W Main St",
  "theme":"#0369a1","colors":("#eff6ff","#dbeafe","#93c5fd","#3b82f6","#2563eb","#1d4ed8","#1e40af","#1e3a8a"),
  "hero_img":HEROES[6],
  "title":"Porta Potty Rental Pensacola, FL — Emerald Coast · Same-Day · From $75",
  "h1_city":"Pensacola, FL","h1_sub":"Emerald Coast · Military City USA",
  "meta_desc":"Portable toilet rental Pensacola FL from $75/day. Serving NAS Pensacola, Pensacola Beach events, Escambia County construction & hurricane recovery. Call (833) 652-9344.",
  "og_title":"Pensacola FL Porta Potty Rentals | Emerald Coast | Military Ready",
  "og_desc":"Pensacola portable toilet rental for NAS Pensacola contractors, Pensacola Beach events, and hurricane recovery. Same-day delivery across the Emerald Coast.",
  "services_intro":"From Naval Air Station Pensacola contractor construction and the Blue Angels air show at NAS Pensacola to Pensacola Beach Mardi Gras events and post-hurricane recovery operations across Escambia and Santa Rosa counties, FixPilot delivers reliable portable sanitation across the Emerald Coast.",
  "demand_para":"Pensacola is Military City USA — home to NAS Pensacola, Naval Air Station Whiting Field, and Eglin Air Force Base to the east. Military construction at these installations generates constant contractor portable toilet demand, including high-security delivery protocols that only experienced vendors can navigate. The civilian economy is growing too: the Port of Pensacola's industrial expansion, the Pensacola International Airport terminal replacement, and the I-10 widening project are major active construction contracts.",
  "event_para":"Pensacola Beach hosts one of the Gulf Coast's largest Mardi Gras celebrations. The Blue Angels' annual homecoming air show draws 200,000+ to NAS Pensacola. The Pensacola Seafood Festival and Pelican Drop on New Year's Eve are fixtures in the regional event calendar. Our hurricane-response fleet is always pre-staged during June–November storm season.",
  "areas":["Gulf Breeze","Navarre","Milton","Fort Walton Beach","Destin","Pace","Cantonment","Perdido Key","Crestview","Mary Esther"],
  "nearby_text":"Gulf Breeze, Navarre, Milton, Fort Walton Beach, Pace",
  "county_nearby":"Escambia County","wiki_city":"Pensacola,_Florida","mapq":"Pensacola+FL+32502",
  "reviews":[
    ("Chief Petty Officer (ret.) Mason","★★★★★","NAS Pensacola facility project — base credentialing requirements, ATFP protocols, zero-fault delivery windows. FixPilot knows how military installations work. Every requirement met without being asked twice."),
    ("Gina P., Pensacola Beach Events","★★★★★","Mardi Gras on the Beach — 20 units over three days, Gulf-side wind conditions. FixPilot weighted and secured every unit properly. Not a single tip. Serviced twice daily and the beach stayed pristine."),
    ("Robert K., Hurricane Recovery PM","★★★★★","Post-Sally recovery in Escambia County — emergency deployment, displaced communities, urgent timeline. FixPilot had 30 units staged within 8 hours of our call. That response capacity is exactly what you need after a major storm."),
    ("Susan A., Wedding Planner","★★★★★","Perdido Key waterfront wedding — 150 guests, Gulf breezes, gorgeous sunset setting. The luxury trailer FixPilot delivered was anchored perfectly and matched the upscale vibe exactly. Every guest commented."),
  ],
  "faqs":[
    ("Do you serve military installations in Pensacola?","Yes. We supply contractor teams at NAS Pensacola, NAS Whiting Field, and coordinate with Eglin AFB contractors. We understand ATFP security protocols, CAC/PIV requirements, and military base delivery procedures."),
    ("How much does portable toilet rental cost in Pensacola?","Standard units from $75/day or $199/week in Escambia County. Santa Rosa County (Gulf Breeze, Navarre) pricing is identical. Hurricane-response emergency pricing is available — contact us for disaster deployment rates."),
    ("Do you provide hurricane recovery services?","Yes. We maintain a 24/7 emergency dispatch and pre-staged storm-response fleet. For Escambia and Santa Rosa county post-storm deployments, we target 4–8 hour response for declared disaster areas."),
    ("Do you serve Navarre Beach and Fort Walton Beach?","Yes. We cover all of Santa Rosa County and extend service to Okaloosa County (Fort Walton Beach, Destin, Crestview, Niceville). Advance scheduling recommended for Destin locations."),
    ("Are your units rated for Gulf Coast hurricane conditions?","Our units include ballast and anchoring hardware designed for Gulf Coast wind conditions. For Category 2+ storms we recommend retrieval prior to landfall — we offer pre-storm pickup coordination."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Pensacola y toda la Costa Esmeralda."),
    ("Do you serve the Blue Angels homecoming air show?","Yes. The NAS Pensacola homecoming air show is one of our largest single-event deployments annually. Contact us by August for October air show orders."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Pensacola-area construction."),
  ],
  "related_cities":[("Tallahassee FL","tallahassee-fl"),("Florida","florida")],
},

"jackson-ms": {
  "name":"Jackson","state":"MS","state_name":"Mississippi","county":"Hinds County",
  "lat":32.2988,"lon":-90.1848,"zip":"39201","address":"219 S President St",
  "theme":"#15803d","colors":("#f0fdf4","#dcfce7","#86efac","#22c55e","#16a34a","#15803d","#166534","#14532d"),
  "hero_img":HEROES[7],
  "title":"Porta Potty Rental Jackson, MS — Crossroads City · Same-Day · From $75",
  "h1_city":"Jackson, MS","h1_sub":"Crossroads of the South · Central Mississippi",
  "meta_desc":"Portable toilet rental Jackson MS from $75/day. Serving Hinds County construction, Fondren District events, Mississippi State Fair & I-20 corridor projects. Call (833) 652-9344.",
  "og_title":"Jackson MS Porta Potty Rentals | Crossroads City | Same-Day Delivery",
  "og_desc":"Jackson MS portable toilet rental for Hinds County construction, Mississippi State Fair, and I-20 corridor development. Same-day delivery across Central Mississippi.",
  "services_intro":"From the Mississippi State Fair at the Fairgrounds and the Two Mississippi Museums campus construction on the Pearl Street Museum Mile to the VA Medical Center expansion in Flowood and utility infrastructure projects across Hinds County, FixPilot delivers reliable portable sanitation across Central Mississippi.",
  "demand_para":"Jackson is Mississippi's capital and largest city, anchoring a construction economy driven by state government infrastructure, healthcare campus expansion, and the I-20 corridor distribution buildout. The University of Mississippi Medical Center (UMMC) — one of the state's largest employers — is perpetually expanding its hospital and research campus on Lakeland Drive. The Pearl River Valley infrastructure improvement projects, the Mississippi Department of Transportation's Metro Jackson freeway projects, and Flowood's booming commercial strip along Lakeland Drive generate consistent portable toilet demand.",
  "event_para":"The Mississippi State Fair at the State Fairgrounds draws 600,000+ annually. The Crossroads Film Festival, the Jackson Rhythm & Blues Festival in Smith Park, and the Fondren Arts Festival create seasonal event demand. The Jackson metro's outdoor wedding market — centered on Rankin County venues and the Natchez Trace corridor — is a growing luxury restroom trailer market.",
  "areas":["Ridgeland","Flowood","Brandon","Clinton","Pearl","Byram","Richland","Vicksburg","Canton","Madison"],
  "nearby_text":"Ridgeland, Flowood, Brandon, Clinton, Pearl",
  "county_nearby":"Hinds County","wiki_city":"Jackson,_Mississippi","mapq":"Jackson+MS+39201",
  "reviews":[
    ("Dr. Williams, UMMC Contractor","★★★★★","UMMC hospital campus expansion in the Medical District — hospital-adjacent delivery, strict infection control protocols. FixPilot understands what a Level 1 trauma center requires from its vendors. Flawless in 10 months of service."),
    ("Kay F., MS State Fair Operations","★★★★★","Mississippi State Fair — 40 units at the Fairgrounds for 10 days. FixPilot services twice daily during peak weekend attendance. Clean units every morning. We've trusted FixPilot with the State Fair for two consecutive years."),
    ("Marcus B., Flowood Commercial","★★★★★","Commercial development on Lakeland Drive in Flowood. FixPilot delivered on our first call and has serviced reliably every week since. In a city that can be challenging for logistics, their consistency stands out."),
    ("Julie P., Wedding Coordinator","★★★★★","Outdoor estate wedding in Madison County — 180 guests, beautiful setting. The luxury trailer FixPilot delivered was spotless and air-conditioned. In Mississippi August heat that last part matters enormously."),
  ],
  "faqs":[
    ("How much does portable toilet rental cost in Jackson, MS?","Standard units from $75/day or $195/week in Hinds County. Rankin County (Brandon, Flowood, Pearl) and Madison County carry the same rate. Luxury trailers from $575/event."),
    ("Do you serve UMMC and the Medical District?","Yes. We supply portable sanitation to UMMC contractor teams and the Medical District construction corridor on Lakeland Drive. Hospital-adjacent delivery protocols are standard for our UMMC service."),
    ("Do you cover Ridgeland, Madison, and Madison County?","Yes. Madison County — including Ridgeland, Madison, and Canton — is within our primary service area with same-day delivery available."),
    ("Do you serve the Mississippi State Fair?","Yes. The State Fair at the Fairgrounds on High Street is a major annual deployment for us. Contact us by August for October fair orders."),
    ("Are your units Mississippi DEQ compliant?","Yes. All units meet Mississippi Department of Environmental Quality portable sanitation standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you serve Vicksburg and Warren County?","Yes. Vicksburg is within our extended service area. Mississippi River corridor project delivery is available with advance scheduling."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Jackson y todo el condado de Hinds."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Jackson-area construction."),
  ],
  "related_cities":[("Biloxi MS","biloxi-ms"),("Mississippi","mississippi")],
},

"biloxi-ms": {
  "name":"Biloxi","state":"MS","state_name":"Mississippi","county":"Harrison County",
  "lat":30.3960,"lon":-88.8853,"zip":"39530","address":"140 Lameuse St",
  "theme":"#0e7490","colors":("#ecfeff","#cffafe","#67e8f9","#06b6d4","#0891b2","#0e7490","#155e75","#164e63"),
  "hero_img":HEROES[8],
  "title":"Porta Potty Rental Biloxi, MS — Gulf Coast · Same-Day · From $75/Day",
  "h1_city":"Biloxi, MS","h1_sub":"Gulf Coast · Casino Corridor · Hurricane Ready",
  "meta_desc":"Portable toilet rental Biloxi MS from $75/day. Serving casino construction, Keesler AFB, hurricane recovery, Gulf Coast events & Harrison County job sites. Call (833) 652-9344.",
  "og_title":"Biloxi MS Porta Potty Rentals | Gulf Coast | Casino & Military",
  "og_desc":"Biloxi portable toilet rental for casino construction, Keesler AFB, hurricane recovery operations, and Harrison County job sites. Same-day delivery. Call (833) 652-9344.",
  "services_intro":"From Keesler Air Force Base contractor construction and MGM/Beau Rivage casino resort expansion to post-hurricane recovery operations across the Mississippi Gulf Coast and Ingalls Shipbuilding in Pascagoula, FixPilot delivers heavy-duty portable sanitation throughout Harrison and Jackson counties.",
  "demand_para":"Biloxi's economy is built on three pillars — military, gaming, and maritime — all of which generate consistent construction activity. Keesler AFB is home to the Air Force's largest technical training school and undergoes constant facility renovation. The Biloxi casino resort strip is perpetually renovating or expanding. Ingalls Shipbuilding in Pascagoula — one of the largest ship repair and construction facilities in the world — drives massive contractor portable toilet demand year-round.",
  "event_para":"The Biloxi Seafood Festival, Mississippi Gulf Coast Marathon, and Cruisin' the Coast car show (one of the largest antique car events in America, drawing 8,000+ vehicles) create consistent fall event demand. The Gulf Coast's hurricane recovery cycles — Katrina, Nate, Sally — mean our emergency fleet is a permanent fixture in the region. We pre-stage storm response inventory every June.",
  "areas":["Gulfport","Ocean Springs","D'Iberville","Pascagoula","Long Beach","Pass Christian","Bay St Louis","Waveland","Gautier","Moss Point"],
  "nearby_text":"Gulfport, Ocean Springs, D'Iberville, Pascagoula, Long Beach",
  "county_nearby":"Harrison County","wiki_city":"Biloxi,_Mississippi","mapq":"Biloxi+MS+39530",
  "reviews":[
    ("Col. Davis (ret.), Keesler Contractor","★★★★★","Keesler AFB facility renovation — ATFP security protocols, DoD credentialing requirements, strict base access procedures. FixPilot has handled every requirement without error across 12 months of weekly service. Exceptional for a DoD site."),
    ("Scott H., MGM Beau Rivage Contractor","★★★★★","Casino resort renovation — 24-hour operations, resort guest proximity, strict HOA and resort protocols. FixPilot placed units with discretion, serviced on schedule, and the resort management never raised an issue."),
    ("James R., Ingalls Subcontractor","★★★★★","Shipyard work in Pascagoula — heavy industrial environment, long shifts, remote yard locations. FixPilot's industrial-grade units handle conditions that standard porta potties can't. Reliable partner for a demanding site."),
    ("Monica T., Cruisin' the Coast","★★★★★","Cruisin' the Coast — 8,000 classic cars, 200,000+ spectators over 8 days along the Boulevard. FixPilot coordinated a 35-unit deployment across 5 zones. Serviced twice daily. No complaints from the event committee or the city."),
  ],
  "faqs":[
    ("Do you serve Keesler AFB and military sites?","Yes. We supply contractor teams at Keesler Air Force Base. We understand DoD ATFP security protocols, CAC/PIV access requirements, and military base service windows."),
    ("How much does portable toilet rental cost in Biloxi?","Standard units from $75/day or $199/week in Harrison County. Gulfport and Ocean Springs carry the same rate. Industrial units for Pascagoula shipyard sites from $95/week. Luxury trailers from $575/event."),
    ("Do you provide hurricane emergency response?","Yes. We maintain a pre-staged storm-response fleet and 24/7 emergency dispatch for Gulf Coast hurricane recovery operations. Harrison and Jackson county post-storm deployments typically deploy within 6–8 hours of an all-clear."),
    ("Do you serve Pascagoula and Jackson County?","Yes. Pascagoula and the Ingalls Shipbuilding corridor are within our primary service area. We supply heavy-duty industrial units designed for maritime and shipyard environments."),
    ("Do you cover Gulfport and Harrison County?","Yes. Gulfport is our co-primary market alongside Biloxi. We cover all of Harrison County with same-day delivery available."),
    ("Are your units Mississippi DEQ compliant?","Yes. All units meet Mississippi Department of Environmental Quality standards and federal OSHA 29 CFR 1926.51 requirements."),
    ("Do you speak Spanish?","Sí, hablamos español. Llámenos para la renta de baños portátiles en Biloxi y toda la Costa del Golfo de Mississippi."),
    ("What is the minimum rental period?","One day for events; weekly contracts most economical for Biloxi-area construction."),
  ],
  "related_cities":[("Jackson MS","jackson-ms"),("Mississippi","mississippi")],
},
}

def main():
    built = 0
    for slug, d in CITIES_B3.items():
        outdir = Path(f"porta-potty-rental-{slug}")
        outfile = outdir / "index.html"
        outdir.mkdir(exist_ok=True)
        html = build_page(slug, d)
        outfile.write_text(html, encoding="utf-8")
        print(f"  ✓ {slug} ({len(html):,} chars)")
        built += 1
    print(f"\nBuilt {built} city pages")

if __name__ == "__main__":
    main()
