#!/usr/bin/env python3
"""
Inject unique demand+event content into all 224 thin city pages.
Reads content from /tmp/city_content_upgrade.json (generated by workflow).
"""
import json, re, glob
from pathlib import Path

def inject_content(html: str, slug: str, demand_para: str, event_para: str, services_intro: str) -> tuple[str, bool]:
    """Inject the unique content section and update services intro."""

    # Skip if already has new-format demand section
    if 'City-Specific Demand Section' in html or 'text-gray-700 leading-relaxed mb-5' in html:
        return html, False

    # City display name from slug
    city_part = re.sub(r'-[a-z]{2}$', '', slug.replace('porta-potty-rental-', ''))
    city_display = city_part.replace('-', ' ').title()

    # Build the new section HTML
    new_section = f"""
  <!-- City-Specific Demand Section -->
  <section class="py-14 bg-white">
    <div class="container mx-auto px-4 max-w-4xl">
      <h2 class="text-3xl md:text-4xl font-extrabold text-brand-900 mb-5">{city_display} Portable Toilet Rental — Local Market Overview</h2>
      <p class="text-gray-700 leading-relaxed mb-5 text-lg">{demand_para}</p>
      <p class="text-gray-700 leading-relaxed text-lg">{event_para}</p>
      <div class="mt-8 grid grid-cols-2 md:grid-cols-4 gap-4 text-center">
        <div class="bg-brand-50 rounded-xl p-4"><div class="text-3xl font-black text-brand-900">$75</div><div class="text-xs text-gray-500 mt-1">Starting price/day</div></div>
        <div class="bg-brand-50 rounded-xl p-4"><div class="text-3xl font-black text-brand-900">4hr</div><div class="text-xs text-gray-500 mt-1">Avg delivery time</div></div>
        <div class="bg-brand-50 rounded-xl p-4"><div class="text-3xl font-black text-brand-900">24/7</div><div class="text-xs text-gray-500 mt-1">Emergency line</div></div>
        <div class="bg-brand-50 rounded-xl p-4"><div class="text-3xl font-black text-brand-900">100%</div><div class="text-xs text-gray-500 mt-1">OSHA-compliant</div></div>
      </div>
    </div>
  </section>

"""

    # Find the services section and inject before it
    services_idx = html.find('<section id="services"')
    if services_idx == -1:
        # Try alternate format
        services_idx = html.find('id="services"')
        if services_idx != -1:
            services_idx = html.rfind('<section', 0, services_idx)

    if services_idx == -1:
        return html, False

    # Find the closest </section> before services to insert after it
    last_section_end = html.rfind('</section>', 0, services_idx)
    if last_section_end == -1:
        insert_pos = services_idx
    else:
        insert_pos = last_section_end + len('</section>')

    new_html = html[:insert_pos] + new_section + html[insert_pos:]

    # Update the services intro paragraph
    # Find the intro paragraph inside the services section
    # Pattern: first <p> after the services H2
    services_section_start = new_html.find('<section id="services"')
    if services_section_start == -1:
        services_section_start = new_html.find('id="services"')
        services_section_start = new_html.rfind('<section', 0, services_section_start)

    if services_section_start > 0:
        # Find the H2 in services section
        h2_in_services = new_html.find('<h2', services_section_start)
        h2_end = new_html.find('</h2>', h2_in_services) + 5

        # Find next <p> after the H2
        next_p = new_html.find('<p', h2_end)
        next_p_end = new_html.find('</p>', next_p) + 4

        if next_p > 0 and next_p_end > 4:
            old_para = new_html[next_p:next_p_end]
            old_text = re.sub(r'<[^>]+>', '', old_para).strip()

            # Only replace if it looks like a template paragraph
            if ('From navigating' in old_text or 'from navigating' in old_text or
                'provide the most reliable' in old_text or
                'porta potty rental' in old_text.lower()):

                # Get the class from the original paragraph
                p_class_m = re.search(r'<p([^>]*)>', old_para)
                p_class = p_class_m.group(1) if p_class_m else ' class="text-gray-600 mb-12 leading-relaxed max-w-3xl mx-auto text-center"'

                new_para = f'<p{p_class}>{services_intro}</p>'
                new_html = new_html[:next_p] + new_para + new_html[next_p_end:]

    return new_html, True


def main():
    # Load the generated content
    content_file = Path('/tmp/city_content_upgrade.json')
    if not content_file.exists():
        print("ERROR: /tmp/city_content_upgrade.json not found. Run the workflow first.")
        return

    data = json.loads(content_file.read_text())
    cities = data.get('cities', [])

    print(f"Loaded content for {len(cities)} cities")

    # Build lookup map
    content_map = {c['slug']: c for c in cities if c.get('slug') and c.get('demand_para')}
    print(f"Valid content entries: {len(content_map)}")

    # Process all pages
    pages = sorted(glob.glob('porta-potty-rental-*-*/index.html'))
    injected = 0
    skipped = 0
    no_content = 0

    for path in pages:
        slug = path.split('/')[0]

        # Skip if already upgraded (has the demand section)
        html = Path(path).read_text(encoding='utf-8', errors='replace')
        if 'City-Specific Demand Section' in html or 'text-gray-700 leading-relaxed mb-5' in html:
            skipped += 1
            continue

        # Check if we have content for this page
        if slug not in content_map:
            no_content += 1
            continue

        content = content_map[slug]
        demand_para = content.get('demand_para', '').strip()
        event_para = content.get('event_para', '').strip()
        services_intro = content.get('services_intro', '').strip()

        if not demand_para or not event_para:
            no_content += 1
            continue

        # Inject
        new_html, changed = inject_content(html, slug, demand_para, event_para, services_intro)

        if changed:
            Path(path).write_text(new_html, encoding='utf-8')
            injected += 1
            if injected % 20 == 0:
                print(f"  Progress: {injected} pages injected...")
        else:
            skipped += 1

    print(f"\nResults:")
    print(f"  Injected: {injected} pages")
    print(f"  Already upgraded (skipped): {skipped} pages")
    print(f"  No content available: {no_content} pages")
    print(f"  Total: {len(pages)} pages")


if __name__ == '__main__':
    main()
