#!/usr/bin/env python3
"""Regenerate city pages from clean Atlanta template."""

import re
from pathlib import Path

TEMPLATE_PATH = Path("porta-potty-rental-atlanta-ga/index.html")

CITY_DATA = {
    "houston-tx": {
        "name": "Houston",
        "state": "TX",
        "state_name": "Texas",
        "county": "Harris County",
        "description": "Houston porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving TX. Get a free quote!",
        "title": "Porta Potty Rental Houston, TX | Harris County | Same-Day Delivery",
        "og_title": "Houston Porta Potty Rentals | Harris County | Same-Day Delivery",
        "og_description": "From Houston Astros games to Energy Capital construction, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "1001 Fannin St",
        "address_zip": "77002",
        "theme_color": "#dc2626",
        "brand_50": "#fef2f2",
        "brand_100": "#fee2e2",
        "brand_300": "#fca5a5",
        "brand_500": "#ef4444",
        "brand_600": "#dc2626",
        "brand_700": "#b91c1c",
        "brand_800": "#991b1b",
        "brand_900": "#7f1d1d",
        "areas": [
            ("Downtown Houston", "Perfect for construction near Discovery Green and events at Minute Maid Park."),
            ("Galleria", "Luxury restroom trailers for upscale weddings and events near The Galleria."),
            ("Medical Center", "Serving Texas Medical Center and all hospital facilities."),
            ("The Heights", "Event services for this historic neighborhood with Victorian architecture."),
            ("Midtown", "Quick delivery to Houston's growing arts and entertainment district."),
            ("Montrose", "Perfect for gallery openings, restaurants, and cultural events."),
            ("River Oaks", "Premium sanitation services for luxury events in Houston's premier neighborhood."),
            ("Sugar Land", "Serving Sugar Land Town Center and all Fort Bend County locations."),
            ("Pearland", "Fast delivery to Pearland and southern Harris County."),
            ("Katy", "Serving Katy ISD construction and community events."),
        ],
        "hero_keyword": "Space City",
        "services_keywords": "Houston Astros, Rockets games, Rodeo Houston, TX construction",
    },
    "phoenix-az": {
        "name": "Phoenix",
        "state": "AZ",
        "state_name": "Arizona",
        "county": "Maricopa County",
        "description": "Phoenix porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving AZ. Get a free quote!",
        "title": "Porta Potty Rental Phoenix, AZ | Maricopa County | Same-Day Delivery",
        "og_title": "Phoenix Porta Potty Rentals | Maricopa County | Same-Day Delivery",
        "og_description": "From Desert Ridge to Scottsdale events, Phoenix trusts us for porta potty rentals. Construction, events & desert heat emergency service.",
        "address_street": "201 E Washington St",
        "address_zip": "85004",
        "theme_color": "#ea580c",
        "brand_50": "#fff7ed",
        "brand_100": "#ffedd5",
        "brand_300": "#fdba74",
        "brand_500": "#f97316",
        "brand_600": "#ea580c",
        "brand_700": "#c2410c",
        "brand_800": "#9a3412",
        "brand_900": "#7c2d12",
        "areas": [
            ("Scottsdale", "Luxury restroom trailers for Scottsdale resorts and events."),
            ("Mesa", "Serving Mesa Convention Center and Apache Junction."),
            ("Tempe", "Perfect for ASU events and Tempe Town Lake activities."),
            ("Gilbert", "Family-friendly sanitation for Gilbert parks and community events."),
            ("Chandler", "Serving Chandler Fashion Center and downtown Chandler."),
            ("Glendale", "Quick delivery to State Farm Stadium and Gila River Arena."),
            ("Peoria", "Serving Peoria sports complexes and Spring Training venues."),
            ("Surprise", "Perfect for Surprise Stadium and Surprise Recreation Campus."),
            ("Arcadia", "Premium services for Arcadia neighborhood and Camelback Mountain events."),
            ("Desert Ridge", "Serving Desert Ridge Marketplace and JW Marriott Desert Ridge."),
        ],
        "hero_keyword": "Valley of the Sun",
        "services_keywords": "Spring Training baseball, Phoenix Open, AZ construction, desert events",
    },
    "charlotte-nc": {
        "name": "Charlotte",
        "state": "NC",
        "state_name": "North Carolina",
        "county": "Mecklenburg County",
        "description": "Charlotte porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving NC. Get a free quote!",
        "title": "Porta Potty Rental Charlotte, NC | Mecklenburg County | Same-Day Delivery",
        "og_title": "Charlotte Porta Potty Rentals | Mecklenburg County | Same-Day Delivery",
        "og_description": "From Bank of America Stadium to Myers Park weddings, Charlotte trusts us for porta potty rentals. Construction, events & emergency service.",
        "address_street": "2120 S College St",
        "address_zip": "28203",
        "theme_color": "#3b82f6",
        "brand_50": "#eff6ff",
        "brand_100": "#dbeafe",
        "brand_300": "#93c5fd",
        "brand_500": "#3b82f6",
        "brand_600": "#2563eb",
        "brand_700": "#1d4ed8",
        "brand_800": "#1e40af",
        "brand_900": "#1e3a8a",
        "areas": [
            ("South End", "Perfect for South End art walks and brewery events."),
            ("Uptown", "Serving Charlotte's urban core, Bank of America Stadium, and Spectrum Center."),
            ("NoDa", "Artistic sanitation for NoDa's galleries and music venues."),
            ("Plaza Midwood", "Community events and neighborhood festivals in Plaza Midwood."),
            ("Myers Park", "Luxury events and weddings in Charlotte's most prestigious neighborhood."),
            ("Dilworth", "Quick delivery to Dilworth's parks and historic district."),
            ("Ballantyne", "Serving Ballantyne Corporate Park and Ballantyne Village."),
            ("University City", "UNC Charlotte events and University City partnerships."),
            ("Lake Norman", "Lakefront events and Cornelius, Huntersville, and Davidson."),
            ("Fort Mill", "Fast delivery to Fort Mill, Tega Cay, and Rock Hill."),
        ],
        "hero_keyword": "Queen City",
        "services_keywords": "Panthers games, Charlotte Motor Speedway, NC music festivals",
    },
    "fort-worth-tx": {
        "name": "Fort Worth",
        "state": "TX",
        "state_name": "Texas",
        "county": "Tarrant County",
        "description": "Fort Worth porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving TX. Get a free quote!",
        "title": "Porta Potty Rental Fort Worth, TX | Tarrant County | Same-Day Delivery",
        "og_title": "Fort Worth Porta Potty Rentals | Cowtown | Same-Day Delivery",
        "og_description": "From Stockyards to DFW construction, Fort Worth trusts us for porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "1000 Throckmorton St",
        "address_zip": "76102",
        "theme_color": "#dc2626",
        "brand_50": "#fef2f2",
        "brand_100": "#fee2e2",
        "brand_300": "#fca5a5",
        "brand_500": "#ef4444",
        "brand_600": "#dc2626",
        "brand_700": "#b91c1c",
        "brand_800": "#991b1b",
        "brand_900": "#7f1d1d",
        "areas": [
            ("Downtown Fort Worth", "Perfect for Sundance Square events and cattle auctions."),
            ("Stockyards", "Authentic western experiences near Fort Worth Stockyards National Historic District."),
            ("Magnolia", "Serving the vibrant Magnolia District and Near Southside."),
            ("TCU", "Amphitheater events and TCU campus construction."),
            ("Sundance", "Premium services for Sundance Square Plaza events."),
            ("Riverside", "Quick delivery to Fort Worth's riverside developments."),
            ("North Fort Worth", "Serving AllianceTexas and Haslet construction projects."),
            ("South Fort Worth", "Community events and Hulen Mall area."),
            ("Benbrook", "Perfect for Benbrook Lake activities and community events."),
            ("Haltom City", "Fast delivery to Haltom City and North Richland Hills."),
        ],
        "hero_keyword": "Cowtown",
        "services_keywords": "Stock Show, Rodeo, TX construction, Fort Worth events",
    },
    "the-woodlands-tx": {
        "name": "The Woodlands",
        "state": "TX",
        "state_name": "Texas",
        "county": "Montgomery County",
        "description": "The Woodlands porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving TX. Get a free quote!",
        "title": "Porta Potty Rental The Woodlands, TX | Montgomery County | Same-Day Delivery",
        "og_title": "The Woodlands Porta Potty Rentals | Houston Metro | Same-Day Delivery",
        "og_description": "From Cynthia Woods Pavilion to The Woodlands Village events, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "1400 Woodlands Pkwy",
        "address_zip": "77380",
        "theme_color": "#dc2626",
        "brand_50": "#fef2f2",
        "brand_100": "#fee2e2",
        "brand_300": "#fca5a5",
        "brand_500": "#ef4444",
        "brand_600": "#dc2626",
        "brand_700": "#b91c1c",
        "brand_800": "#991b1b",
        "brand_900": "#7f1d1d",
        "areas": [
            ("Town Center", "Perfect for The Woodlands Mall and Cynthia Woods Pavilion events."),
            ("Grogan's Mill", "Serving Grogan's Mill Village and neighborhood events."),
            ("Panther Creek", "Quick delivery to Panther Creek Village and surrounding areas."),
            ("Sterling Ridge", "Premium sanitation for Sterling Ridge events and construction."),
            ("Cochran's Crossing", "Perfect for Cochran's Crossing neighborhood and schools."),
            ("Indian Springs", "Serving Indian Springs Village and local parks."),
            ("Alden Bridge", "Fast delivery to Alden Bridge community events."),
            ("Creekside", "Perfect for Creekside Park Village and George Mitchell Preserve."),
            ("Spring", "Serving Spring, TX and Klein area communities."),
            ("Conroe", "Quick delivery to Conroe and Lake Conroe events."),
        ],
        "hero_keyword": "Master Planned Community",
        "services_keywords": "Cynthia Woods, Houston Metro, TX construction, community events",
    },
    "baton-brouge-la": {
        "name": "Baton Rouge",
        "state": "LA",
        "state_name": "Louisiana",
        "county": "East Baton Rouge Parish",
        "description": "Baton Rouge porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving LA. Get a free quote!",
        "title": "Porta Potty Rental Baton Rouge, LA | East Baton Rouge Parish | Same-Day Delivery",
        "og_title": "Baton Rouge Porta Potty Rentals | Capital City | Same-Day Delivery",
        "og_description": "From LSU to Louisiana construction, Baton Rouge trusts us for porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "222 St Louis St",
        "address_zip": "70802",
        "theme_color": "#0891b2",
        "brand_50": "#f0f9ff",
        "brand_100": "#e0f2fe",
        "brand_300": "#7dd3fc",
        "brand_500": "#0ea5e9",
        "brand_600": "#0891b2",
        "brand_700": "#0e7490",
        "brand_800": "#155e75",
        "brand_900": "#164e63",
        "areas": [
            ("Downtown Baton Rouge", "Perfect for Louisiana State Capitol events and downtown festivals."),
            ("LSU", "Quick delivery to Tiger Stadium and LSU campus construction."),
            ("Southdowns", "Premium sanitation for Southdowns neighborhood events."),
            ("Highland Road", "Serving Highland Road Park and community facilities."),
            ("Perkins", "Perfect for Perkins Rowe shopping center and surrounding areas."),
            ("Broadmoor", "Community events and Broadmoor neighborhood festivals."),
            ("Sherwood Forest", "Quick delivery to Sherwood Forest and Garden District."),
            ("Bocage", "Premium services for Bocage Shopping Center events."),
            ("Mid City", "Serving Downtown Development District and Mid City."),
            ("Webre", "Perfect for Webre area and Baton Rouge Airport vicinity."),
        ],
        "hero_keyword": "Capital City",
        "services_keywords": "LSU games,Mardi Gras, Louisiana construction, Baton Rouge events",
    },
    "boulder-co": {
        "name": "Boulder",
        "state": "CO",
        "state_name": "Colorado",
        "county": "Boulder County",
        "description": "Boulder porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving CO. Get a free quote!",
        "title": "Porta Potty Rental Boulder, CO | Boulder County | Same-Day Delivery",
        "og_title": "Boulder Porta Potty Rentals | Flatirons | Same-Day Delivery",
        "og_description": "From Pearl Street to Colorado mountain events, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "1777 Broadway",
        "address_zip": "80302",
        "theme_color": "#059669",
        "brand_50": "#ecfdf5",
        "brand_100": "#d1fae5",
        "brand_300": "#6ee7b7",
        "brand_500": "#10b981",
        "brand_600": "#059669",
        "brand_700": "#047857",
        "brand_800": "#065f46",
        "brand_900": "#064e3b",
        "areas": [
            ("Downtown Boulder", "Perfect for Pearl Street Mall and Pearl Street concerts."),
            ("Pearl Street", "Quick delivery to Pearl Street Farmers Market events."),
            ("University Hill", "Serving CU Boulder campus and University Hill businesses."),
            ("Mapleton Hill", "Historic neighborhoods and boulder Creek path events."),
            ("Whittier", "Perfect for Whittier neighborhood and Eben G. Fine Park."),
            ("Baseline", "Serving Baseline Reservoir and east Boulder areas."),
            ("North Boulder", "Quick delivery to North Boulder and Foothills."),
            ("South Boulder", "Perfect for South Boulder and Marshall Lake activities."),
            ("Chautauqua", "Premium services for Chautauqua hiking and events."),
            ("Eldorado Springs", "Fast delivery to Eldorado Canyon and springs."),
        ],
        "hero_keyword": "Flatirons",
        "services_keywords": "CU Boulder, Pearl Street, CO hiking, Boulder events",
    },
    "bowling-green-ky": {
        "name": "Bowling Green",
        "state": "KY",
        "state_name": "Kentucky",
        "county": "Warren County",
        "description": "Bowling Green porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving KY. Get a free quote!",
        "title": "Porta Potty Rental Bowling Green, KY | Warren County | Same-Day Delivery",
        "og_title": "Bowling Green Porta Potty Rentals | WKU Area | Same-Day Delivery",
        "og_description": "From Corvette Plant to WKU events, Bowling Green trusts us for porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "1001 College St",
        "address_zip": "42101",
        "theme_color": "#0891b2",
        "brand_50": "#f0f9ff",
        "brand_100": "#e0f2fe",
        "brand_300": "#7dd3fc",
        "brand_500": "#0ea5e9",
        "brand_600": "#0891b2",
        "brand_700": "#0e7490",
        "brand_800": "#155e75",
        "brand_900": "#164e63",
        "areas": [
            ("Downtown Bowling Green", "Perfect for The Trace and Fountain Square events."),
            ("Schmidt", "Serving Schmidt development and surrounding areas."),
            ("Cumberland Trace", "Quick delivery to Cumberland Trace and KY Exhibition Center."),
            ("Rich Pond", "Perfect for Rich Pond neighborhood and community events."),
            ("Plano", "Serving Plano community and local parks."),
            ("Smiths Grove", "Fast delivery to Smiths Grove and Barren County."),
            ("Woodburn", "Perfect for Woodburn and Western Kentucky University area."),
            ("Oakland", "Premium sanitation for Oakland community events."),
            ("Smiths", "Quick delivery to Smiths neighborhood and businesses."),
            ("Alvaton", "Serving Alvaton and southern Warren County."),
        ],
        "hero_keyword": "Corvette City",
        "services_keywords": "Corvette Plant, WKU, Kentucky construction, Bowling Green events",
    },
    "brooklyn-park-mn": {
        "name": "Brooklyn Park",
        "state": "MN",
        "state_name": "Minnesota",
        "county": "Hennepin County",
        "description": "Brooklyn Park porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving MN. Get a free quote!",
        "title": "Porta Potty Rental Brooklyn Park, MN | Hennepin County | Same-Day Delivery",
        "og_title": "Brooklyn Park Porta Potty Rentals | Twin Cities | Same-Day Delivery",
        "og_description": "From Brooklyn Park construction to Twin Cities events, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "5200 85th Ave N",
        "address_zip": "55443",
        "theme_color": "#1d4ed8",
        "brand_50": "#eff6ff",
        "brand_100": "#dbeafe",
        "brand_300": "#93c5fd",
        "brand_500": "#3b82f6",
        "brand_600": "#2563eb",
        "brand_700": "#1d4ed8",
        "brand_800": "#1e40af",
        "brand_900": "#1e3a8a",
        "areas": [
            ("Central Brooklyn Park", "Perfect for Brooklyn Center and North Hennepin College."),
            ("North Brooklyn Park", "Quick delivery to North Brooklyn Park neighborhoods."),
            ("South Brooklyn Park", "Serving South Brooklyn Park and Mississippi Crossing."),
            ("East Brooklyn Park", "Perfect for East Brooklyn Park and Highway 610 corridor."),
            ("West Brooklyn Park", "Premium services for West Brooklyn Park area."),
            ("Edina", "Fast delivery to Edina and Southdale Center vicinity."),
            ("Crystal", "Serving Crystal and Robbinsdale communities."),
            ("Brooklyn Center", "Perfect for Brooklyn Center and Earle Brown Farm."),
            ("Plymouth", "Quick delivery to Plymouth and Wayzata area."),
            ("Champlin", "Premium services for Champlin and Hanthorne."),
        ],
        "hero_keyword": "Twin Cities",
        "services_keywords": "Twin Cities, MN construction, Brooklyn Park events, Minneapolis",
    },
    "centennial-co": {
        "name": "Centennial",
        "state": "CO",
        "state_name": "Colorado",
        "county": "Arapahoe County",
        "description": "Centennial porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving CO. Get a free quote!",
        "title": "Porta Potty Rental Centennial, CO | Arapahoe County | Same-Day Delivery",
        "og_title": "Centennial Porta Potty Rentals | Denver Tech Center | Same-Day Delivery",
        "og_description": "From DTC construction to Colorado events, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "7272 S Lima St",
        "address_zip": "80016",
        "theme_color": "#059669",
        "brand_50": "#ecfdf5",
        "brand_100": "#d1fae5",
        "brand_300": "#6ee7b7",
        "brand_500": "#10b981",
        "brand_600": "#059669",
        "brand_700": "#047857",
        "brand_800": "#065f46",
        "brand_900": "#064e3b",
        "areas": [
            ("Denver Tech Center", "Perfect for Denver Tech Center and business park construction."),
            ("Independence", "Quick delivery to Independence Plaza and surrounding areas."),
            ("Willow Creek", "Serving Willow Creek neighborhood and parks."),
            ("Cherry Creek", "Premium sanitation for Cherry Creek Shopping Center."),
            ("Parker", "Fast delivery to Parker and Lincoln Meadows."),
            ("Foxridge", "Perfect for Foxridge and Centennial center area."),
            ("Highlands", "Serving Highlands at Pinehurst and surrounding neighborhoods."),
            ("Silverbrook", "Quick delivery to Silverbrook and Walnut Hills."),
            ("Louviers", "Premium services for Louviers and Dove Valley."),
            ("Cottonwood", "Fast delivery to Cottonwood and Aspen Hills."),
        ],
        "hero_keyword": "Denver Tech Center",
        "services_keywords": "DTC, Colorado construction, Centennial events, Denver tech",
    },
    "highlands-ranch-co": {
        "name": "Highlands Ranch",
        "state": "CO",
        "state_name": "Colorado",
        "county": "Douglas County",
        "description": "Highlands Ranch porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving CO. Get a free quote!",
        "title": "Porta Potty Rental Highlands Ranch, CO | Douglas County | Same-Day Delivery",
        "og_title": "Highlands Ranch Porta Potty Rentals | Denver Metro | Same-Day Delivery",
        "og_description": "From Highlands Ranch to Colorado construction, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "9368 S Foresthill Rd",
        "address_zip": "80129",
        "theme_color": "#059669",
        "brand_50": "#ecfdf5",
        "brand_100": "#d1fae5",
        "brand_300": "#6ee7b7",
        "brand_500": "#10b981",
        "brand_600": "#059669",
        "brand_700": "#047857",
        "brand_800": "#065f46",
        "brand_900": "#064e3b",
        "areas": [
            ("North Highlands Ranch", "Perfect for C-470 corridor and HRCA recreation."),
            ("East Highlands Ranch", "Quick delivery to East Highlands Ranch neighborhoods."),
            ("South Highlands Ranch", "Serving South Highlands Ranch and Black Forest."),
            ("West Highlands Ranch", "Premium sanitation for West Highlands Ranch."),
            ("Westridge", "Perfect for Westridge and Back Country events."),
            ("Southglenn", "Quick delivery to Southglenn Shopping Center."),
            ("Cougar", "Serving Cougar area and Littleton communities."),
            ("Eastridge", "Fast delivery to Eastridge and Falcon Creek."),
            ("Ranch", "Perfect for Main Street Highlands Ranch events."),
            ("Highlands", "Premium services for all Highlands Ranch villages."),
        ],
        "hero_keyword": "Master Planned Community",
        "services_keywords": "Douglas County, Colorado construction, Highlands Ranch events",
    },
    "hoover-al": {
        "name": "Hoover",
        "state": "AL",
        "state_name": "Alabama",
        "county": "Jefferson County",
        "description": "Hoover porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving AL. Get a free quote!",
        "title": "Porta Potty Rental Hoover, AL | Jefferson County | Same-Day Delivery",
        "og_title": "Hoover Porta Potty Rentals | Birmingham Metro | Same-Day Delivery",
        "og_description": "From Hoover subdivisions to Alabama events, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "100 Municipal Dr",
        "address_zip": "35216",
        "theme_color": "#0891b2",
        "brand_50": "#f0f9ff",
        "brand_100": "#e0f2fe",
        "brand_300": "#7dd3fc",
        "brand_500": "#0ea5e9",
        "brand_600": "#0891b2",
        "brand_700": "#0e7490",
        "brand_800": "#155e75",
        "brand_900": "#164e63",
        "areas": [
            ("The Preserve", "Perfect for The Preserve and Riverchase events."),
            ("Ross Bridge", "Quick delivery to Ross Bridge and Hoover Metropolitan."),
            ("Greystone", "Premium sanitation for Greystone Golf Club events."),
            ("Riverchase", "Serving Riverchase Galleria and Patriot Park."),
            ("Lake Cyrus", "Perfect for Lake Cyrus and Deer Valley area."),
            ("Big Creek", "Quick delivery to Big Creek and Weatherly."),
            ("Deer Valley", "Fast delivery to Deer Valley and Valleydale."),
            ("Carmel", "Premium services for Carmel and Cahaba Heights."),
            ("Inverness", "Serving Inverness and Shelby County."),
            ("Cahaba Heights", "Quick delivery to Cahaba Heights and Mountain Brook."),
        ],
        "hero_keyword": "Birmingham Metro",
        "services_keywords": "Hoover, Birmingham metro, AL construction, Hoover events",
    },
    "huntsville-al": {
        "name": "Huntsville",
        "state": "AL",
        "state_name": "Alabama",
        "county": "Madison County",
        "description": "Huntsville porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving AL. Get a free quote!",
        "title": "Porta Potty Rental Huntsville, AL | Madison County | Same-Day Delivery",
        "og_title": "Huntsville Porta Potty Rentals | Rocket City | Same-Day Delivery",
        "og_description": "From NASA to Rocket City construction, Huntsville trusts us for porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "300 Monroe St",
        "address_zip": "35801",
        "theme_color": "#0891b2",
        "brand_50": "#f0f9ff",
        "brand_100": "#e0f2fe",
        "brand_300": "#7dd3fc",
        "brand_500": "#0ea5e9",
        "brand_600": "#0891b2",
        "brand_700": "#0e7490",
        "brand_800": "#155e75",
        "brand_900": "#164e63",
        "areas": [
            ("Downtown Huntsville", "Perfect for Von Braun Center and courthouse square."),
            ("Five Points", "Quick delivery to Five Points neighborhood events."),
            ("Cliftons", "Serving Cliftons and campus area near UAH."),
            ("Medical District", "Premium sanitation for Huntsville Hospital construction."),
            ("Campus", "Fast delivery to Alabama A&M and Oakwood University."),
            ("Merrill", "Perfect for Merrill and Redstone Arsenal vicinity."),
            ("Lake Forest", "Quick delivery to Lake Forest and Whitesburg."),
            ("Hampton Cove", "Premium services for Hampton Cove and Owens Cross Roads."),
            ("Meridianville", "Fast delivery to Meridianville and Hazel Green."),
            ("Madison", "Serving Madison, AL and Redstone Gateway."),
        ],
        "hero_keyword": "Rocket City",
        "services_keywords": "NASA, Redstone Arsenal, AL construction, Huntsville events",
    },
    "independence-mo": {
        "name": "Independence",
        "state": "MO",
        "state_name": "Missouri",
        "county": "Jackson County",
        "description": "Independence porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving MO. Get a free quote!",
        "title": "Porta Potty Rental Independence, MO | Jackson County | Same-Day Delivery",
        "og_title": "Independence Porta Potty Rentals | Truman Home | Same-Day Delivery",
        "og_description": "From Truman Home to Missouri construction, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "111 E Maple Ave",
        "address_zip": "64050",
        "theme_color": "#059669",
        "brand_50": "#ecfdf5",
        "brand_100": "#d1fae5",
        "brand_300": "#6ee7b7",
        "brand_500": "#10b981",
        "brand_600": "#059669",
        "brand_700": "#047857",
        "brand_800": "#065f46",
        "brand_900": "#064e3b",
        "areas": [
            ("Downtown Independence", "Perfect for Truman Historic District and Square events."),
            ("Englewood", "Quick delivery to Englewood and Little Blue areas."),
            ("River", "Serving Truman Road and river bottoms communities."),
            ("Little Blue", "Premium sanitation for Little Blue neighborhood."),
            ("Knoche", "Fast delivery to Knoche and Van Branch."),
            ("Sugar Creek", "Perfect for Sugar Creek and Grain Valley."),
            ("Lake Tapawingo", "Quick delivery to Lake Tapawingo and Blue Springs."),
            ("Lee's Summit", "Premium services for Lee's Summit and Unity Village."),
            ("Blue Springs", "Fast delivery to Blue Springs and Adams Dairy."),
            ("Kansas City", "Serving Kansas City metro and Grandview."),
        ],
        "hero_keyword": "Truman's Hometown",
        "services_keywords": "Truman Home, MO construction, Independence events, Kansas City",
    },
    "kansas-city-mo": {
        "name": "Kansas City",
        "state": "MO",
        "state_name": "Missouri",
        "county": "Jackson County",
        "description": "Kansas City porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving MO. Get a free quote!",
        "title": "Porta Potty Rental Kansas City, MO | Jackson County | Same-Day Delivery",
        "og_title": "Kansas City Porta Potty Rentals | Metro Area | Same-Day Delivery",
        "og_description": "From KC BBQ events to Missouri construction, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "414 E 12th St",
        "address_zip": "64106",
        "theme_color": "#059669",
        "brand_50": "#ecfdf5",
        "brand_100": "#d1fae5",
        "brand_300": "#6ee7b7",
        "brand_500": "#10b981",
        "brand_600": "#059669",
        "brand_700": "#047857",
        "brand_800": "#065f46",
        "brand_900": "#064e3b",
        "areas": [
            ("Downtown Kansas City", "Perfect for Power & Light District and Sprint Center."),
            ("Crossroads", "Quick delivery to Crossroads Arts District."),
            ("Westport", "Premium sanitation for Westport and Waldo."),
            ("Plaza", "Fast delivery to Country Club Plaza and Loose Park."),
            ("Brookside", "Perfect for Brookside Farmers Market and neighborhood."),
            ("Waldo", "Quick delivery to Waldo and Brookside."),
            ("Lee's Summit", "Serving Lee's Summit and Lake Lotawana."),
            ("Independence", "Fast delivery to Independence and Truman Historic District."),
            ("North Kansas City", "Premium services for North KC and Claycomo."),
            ("Gladstone", "Quick delivery to Gladstone and Liberty."),
        ],
        "hero_keyword": "BBQ Capital",
        "services_keywords": "KC BBQ, Chiefs games, MO construction, Kansas City events",
    },
    "lexington-ky": {
        "name": "Lexington",
        "state": "KY",
        "state_name": "Kentucky",
        "county": "Fayette County",
        "description": "Lexington porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving KY. Get a free quote!",
        "title": "Porta Potty Rental Lexington, KY | Fayette County | Same-Day Delivery",
        "og_title": "Lexington Porta Potty Rentals | Horse Capital | Same-Day Delivery",
        "og_description": "From Keeneland to UK Wildcats, Lexington trusts us for porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "101 E Vine St",
        "address_zip": "40507",
        "theme_color": "#0891b2",
        "brand_50": "#f0f9ff",
        "brand_100": "#e0f2fe",
        "brand_300": "#7dd3fc",
        "brand_500": "#0ea5e9",
        "brand_600": "#0891b2",
        "brand_700": "#0e7490",
        "brand_800": "#155e75",
        "brand_900": "#164e63",
        "areas": [
            ("Downtown Lexington", "Perfect for Rupp Arena and Cheapside Park."),
            ("Chevy Chase", "Quick delivery to Chevy Chase and Pavilion."),
            ("Southland", "Premium sanitation for Southland Drive events."),
            ("Hamburg", "Fast delivery to Hamburg and Lexington Green."),
            ("Palgrove", "Perfect for Palgrove and Tates Creek area."),
            ("Beaumont", "Quick delivery to Beaumont and Masterson Station."),
            ("Bryan Station", "Premium services for Bryan Station and Greendale."),
            ("Tates Creek", "Fast delivery to Tates Creek and Lansdowne."),
            ("Mount Tabor", "Serving Mount Tabor and Nicholasville Road area."),
            ("Gardens", "Perfect for Gardens at Kentucky Horse Park."),
        ],
        "hero_keyword": "Horse Capital",
        "services_keywords": "Keeneland, UK Wildcats, Kentucky horse farms, Lexington events",
    },
    "mobile-al": {
        "name": "Mobile",
        "state": "AL",
        "state_name": "Alabama",
        "county": "Mobile County",
        "description": "Mobile porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving AL. Get a free quote!",
        "title": "Porta Potty Rental Mobile, AL | Mobile County | Same-Day Delivery",
        "og_title": "Mobile Porta Potty Rentals | Alabama Gulf Coast | Same-Day Delivery",
        "og_description": "From port construction to Mardi Gras events, Mobile trusts us for porta potty rentals. Construction, events & emergency service.",
        "address_street": "100 Government St",
        "address_zip": "36602",
        "theme_color": "#0891b2",
        "brand_50": "#f0f9ff",
        "brand_100": "#e0f2fe",
        "brand_300": "#7dd3fc",
        "brand_500": "#0ea5e9",
        "brand_600": "#0891b2",
        "brand_700": "#0e7490",
        "brand_800": "#155e75",
        "brand_900": "#164e63",
        "areas": [
            ("Downtown Mobile", "Perfect for Cathedral Square and Bienville Square."),
            ("Midtown", "Quick delivery to Midtown and Oakleigh Garden District."),
            ("Spring Hill", "Premium sanitation for Spring Hill College and area."),
            ("West Mobile", "Fast delivery to West Mobile and University of South Alabama."),
            ("Semmes", "Perfect for Semmes and west Mobile communities."),
            ("Theodore", "Quick delivery to Theodore and Mobile Airport."),
            ("Prichard", "Premium services for Prichard and Chickasaw."),
            ("Chickasaw", "Fast delivery to Chickasaw and Satsuma."),
            ("Tillmans", "Perfect for Tillmans Corner and Theodore."),
            ("Cottage Hill", "Quick delivery to Cottage Hill and Forest Hill."),
        ],
        "hero_keyword": "Gulf Coast",
        "services_keywords": "Mardi Gras, port construction, AL gulf coast, Mobile events",
    },
    "myrtle-beach-sc": {
        "name": "Myrtle Beach",
        "state": "SC",
        "state_name": "South Carolina",
        "county": "Horry County",
        "description": "Myrtle Beach porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving SC. Get a free quote!",
        "title": "Porta Potty Rental Myrtle Beach, SC | Horry County | Same-Day Delivery",
        "og_title": "Myrtle Beach Porta Potty Rentals | Grand Strand | Same-Day Delivery",
        "og_description": "From Myrtle Beach boardwalk to SC events, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "1000 N Ocean Blvd",
        "address_zip": "29577",
        "theme_color": "#059669",
        "brand_50": "#ecfdf5",
        "brand_100": "#d1fae5",
        "brand_300": "#6ee7b7",
        "brand_500": "#10b981",
        "brand_600": "#059669",
        "brand_700": "#047857",
        "brand_800": "#065f46",
        "brand_900": "#064e3b",
        "areas": [
            ("Myrtle Beach", "Perfect for Broadway at the Beach and Beachwalk."),
            ("Ocean Forest", "Quick delivery to Ocean Forest and Dunes area."),
            ("Arcadian", "Premium sanitation for Arcadian Shores events."),
            ("Briarcliffe", "Fast delivery to Briarcliffe Acres and Carolina Forest."),
            ("North Myrtle Beach", "Perfect for Cherry Grove and Windy Hill Beach."),
            ("Surfside", "Quick delivery to Surfside Beach and Garden City."),
            ("Garden City", "Premium services for Garden City Beach."),
            ("Murrells Inlet", "Fast delivery to Murrells Inlet and Pawleys Island."),
            ("Conway", "Perfect for Conway and Horry Georgetown Tech."),
            ("Loris", "Quick delivery to Loris and Aynor."),
        ],
        "hero_keyword": "Grand Strand",
        "services_keywords": "Myrtle Beach, golf, SC beach events, Grand Strand",
    },
    "plymouth-ma": {
        "name": "Plymouth",
        "state": "MA",
        "state_name": "Massachusetts",
        "county": "Plymouth County",
        "description": "Plymouth porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving MA. Get a free quote!",
        "title": "Porta Potty Rental Plymouth, MA | Plymouth County | Same-Day Delivery",
        "og_title": "Plymouth Porta Potty Rentals | Where It All Began | Same-Day Delivery",
        "og_description": "From Plymouth Rock to Massachusetts events, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "11 Lincoln Blvd",
        "address_zip": "02360",
        "theme_color": "#0891b2",
        "brand_50": "#f0f9ff",
        "brand_100": "#e0f2fe",
        "brand_300": "#7dd3fc",
        "brand_500": "#0ea5e9",
        "brand_600": "#0891b2",
        "brand_700": "#0e7490",
        "brand_800": "#155e75",
        "brand_900": "#164e63",
        "areas": [
            ("Downtown Plymouth", "Perfect for waterfront and Plymouth Rock events."),
            ("Waterfront", "Quick delivery to Plymouth Harbor and Mayflower II."),
            ("The Pinehills", "Premium sanitation for Pinehills Golf Club."),
            ("Plymouth Beach", "Fast delivery to Long Beach and Plymouth Beach."),
            ("West Plymouth", "Perfect for West Plymouth and Manomet."),
            ("North Plymouth", "Quick delivery to North Plymouth and Cedarville."),
            ("South Plymouth", "Premium services for South Plymouth area."),
            ("Manomet", "Fast delivery to Manomet and White Horse Beach."),
            ("Sagamore Beach", "Perfect for Sagamore Beach and MA-3 corridor."),
            ("Bourne", "Quick delivery to Bourne and Sagamore Bridge."),
        ],
        "hero_keyword": "America's Hometown",
        "services_keywords": "Plymouth Rock, Mayflower, MA history, Cape Cod events",
    },
    "south-fulton-ga": {
        "name": "South Fulton",
        "state": "GA",
        "state_name": "Georgia",
        "county": "Fulton County",
        "description": "South Fulton porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving GA. Get a free quote!",
        "title": "Porta Potty Rental South Fulton, GA | Fulton County | Same-Day Delivery",
        "og_title": "South Fulton Porta Potty Rentals | Atlanta Metro | Same-Day Delivery",
        "og_description": "From College Park to Union City, South Fulton trusts us for porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "5360 Old National Hwy",
        "address_zip": "30349",
        "theme_color": "#3b82f6",
        "brand_50": "#eff6ff",
        "brand_100": "#dbeafe",
        "brand_300": "#93c5fd",
        "brand_500": "#3b82f6",
        "brand_600": "#2563eb",
        "brand_700": "#1d4ed8",
        "brand_800": "#1e40af",
        "brand_900": "#1e3a8a",
        "areas": [
            ("College Park", "Perfect for College Park, airport, and Porsche event center."),
            ("Union City", "Quick delivery to Union City and Welcome All Park."),
            ("Fairburn", "Premium sanitation for Fairburn and Renaissance."),
            ("Palmetto", "Fast delivery to Palmetto and Coweta County."),
            ("Red Oak", "Perfect for Red Oak and Fort Gillem."),
            ("Chattahoochee Hills", "Quick delivery to Serenbe and Chattahoochee Hills."),
            ("East Point", "Premium services for East Point and MARTA."),
            ("Forest Park", "Fast delivery to Forest Park and Lake Spivey."),
            ("Jonesboro", "Perfect for Jonesboro and St. Francis area."),
            ("Riverdale", "Quick delivery to Riverdale and Mount Zion."),
        ],
        "hero_keyword": "Atlanta Metro",
        "services_keywords": "College Park, airport, GA construction, South Fulton events",
    },
    "wichita-ks": {
        "name": "Wichita",
        "state": "KS",
        "state_name": "Kansas",
        "county": "Sedgwick County",
        "description": "Wichita porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving KS. Get a free quote!",
        "title": "Porta Potty Rental Wichita, KS | Sedgwick County | Same-Day Delivery",
        "og_title": "Wichita Porta Potty Rentals | Air Capital | Same-Day Delivery",
        "og_description": "From Air Capital to Kansas construction, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "455 N Main St",
        "address_zip": "67202",
        "theme_color": "#0891b2",
        "brand_50": "#f0f9ff",
        "brand_100": "#e0f2fe",
        "brand_300": "#7dd3fc",
        "brand_500": "#0ea5e9",
        "brand_600": "#0891b2",
        "brand_700": "#0e7490",
        "brand_800": "#155e75",
        "brand_900": "#164e63",
        "areas": [
            ("Downtown Wichita", "Perfect for Old Town and Century II."),
            ("Old Town", "Quick delivery to Old Town and Commerce Street."),
            ("Delano", "Premium sanitation for Delano neighborhood."),
            ("Riverside", "Fast delivery to Riverside and Arkansas River."),
            ("North Riverside", "Perfect for North Riverside and Scribner."),
            ("South Riverside", "Quick delivery to South Riverside and Cowtown."),
            ("Matlock", "Premium services for Matlock and Lincoln Park."),
            ("County Line", "Fast delivery to County Line and Goddard."),
            ("Cowtown", "Perfect for Cowtown and Sedgwick County Zoo."),
            ("Sunset", "Quick delivery to Sunset and Longview."),
        ],
        "hero_keyword": "Air Capital",
        "services_keywords": "Wichita aviation, KS construction, Mid-Continent, Wichita events",
    },
    "murfreesboro-tn": {
        "name": "Murfreesboro",
        "state": "TN",
        "state_name": "Tennessee",
        "county": "Rutherford County",
        "description": "Murfreesboro porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving TN. Get a free quote!",
        "title": "Porta Potty Rental Murfreesboro, TN | Rutherford County | Same-Day Delivery",
        "og_title": "Murfreesboro Porta Potty Rentals | Rutherford County | Same-Day Delivery",
        "og_description": "From MTSU to Rutherford County construction, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "111 W Vine St",
        "address_zip": "37130",
        "theme_color": "#059669",
        "brand_50": "#ecfdf5",
        "brand_100": "#d1fae5",
        "brand_300": "#6ee7b7",
        "brand_500": "#10b981",
        "brand_600": "#059669",
        "brand_700": "#047857",
        "brand_800": "#065f46",
        "brand_900": "#064e3b",
        "areas": [
            ("Downtown Murfreesboro", "Perfect for Historic Square and MTSU campus."),
            ("MTSU", "Quick delivery to Middle Tennessee State University."),
            ("The Blvd", "Premium sanitation for The Boulevard and area."),
            ("Barfield", "Fast delivery to Barfield Park and Veterans Park."),
            ("North Murfreesboro", "Perfect for North Murfreesboro and Airport."),
            ("South Murfreesboro", "Quick delivery to South Murfreesboro."),
            ("Smyrna", "Premium services for Smyrna and La Vergne."),
            ("La Vergne", "Fast delivery to La Vergne and Percy Priest."),
            ("Walter Hill", "Perfect for Walter Hill and Stones River."),
            ("Lascassas", "Quick delivery to Lascassas and Union Hall."),
        ],
        "hero_keyword": "Boro",
        "services_keywords": "MTSU, TN construction, Murfreesboro events, Rutherford County",
    },
    "nashville-tn": {
        "name": "Nashville",
        "state": "TN",
        "state_name": "Tennessee",
        "county": "Davidson County",
        "description": "Nashville porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving TN. Get a free quote!",
        "title": "Porta Potty Rental Nashville, TN | Davidson County | Same-Day Delivery",
        "og_title": "Nashville Porta Potty Rentals | Music City | Same-Day Delivery",
        "og_description": "From Broadway to Music City construction, Nashville trusts us for porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "100 4th Ave N",
        "address_zip": "37219",
        "theme_color": "#059669",
        "brand_50": "#ecfdf5",
        "brand_100": "#d1fae5",
        "brand_300": "#6ee7b7",
        "brand_500": "#10b981",
        "brand_600": "#059669",
        "brand_700": "#047857",
        "brand_800": "#065f46",
        "brand_900": "#064e3b",
        "areas": [
            ("Downtown Nashville", "Perfect for Broadway and Bridgestone Arena."),
            ("Germantown", "Quick delivery to Germantown and Bicentennial Mall."),
            ("East Nashville", "Premium sanitation for East Nashville arts district."),
            ("The Gulch", "Fast delivery to The Gulch and Music Row."),
            ("12 South", "Perfect for 12 South and Sevier Park."),
            ("Bellevue", "Quick delivery to Bellevue and Harpeth Valley."),
            ("Antioch", "Premium services for Antioch and Cane Ridge."),
            ("Madison", "Fast delivery to Madison and Goodlettsville."),
            ("Hermitage", "Perfect for Hermitage and Donelson."),
            ("Brentwood", "Quick delivery to Brentwood and Franklin."),
        ],
        "hero_keyword": "Music City",
        "services_keywords": "Broadway, Nashville music, TN construction, Nashville events",
    },
    "athens-ga": {
        "name": "Athens",
        "state": "GA",
        "state_name": "Georgia",
        "county": "Clarke County",
        "description": "Athens porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving GA. Get a free quote!",
        "title": "Porta Potty Rental Athens, GA | Clarke County | Same-Day Delivery",
        "og_title": "Athens Porta Potty Rentals | Classic City | Same-Day Delivery",
        "og_description": "From UGA to Athens classic city events, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "325 E Washington St",
        "address_zip": "30601",
        "theme_color": "#3b82f6",
        "brand_50": "#eff6ff",
        "brand_100": "#dbeafe",
        "brand_300": "#93c5fd",
        "brand_500": "#3b82f6",
        "brand_600": "#2563eb",
        "brand_700": "#1d4ed8",
        "brand_800": "#1e40af",
        "brand_900": "#1e3a8a",
        "areas": [
            ("Downtown Athens", "Perfect for UGA campus and Classic City events."),
            ("Normaltown", "Quick delivery to Normaltown and surrounding areas."),
            ("Five Points", "Premium sanitation for Five Points and Prince Avenue."),
            ("Bishop Park", "Fast delivery to Bishop Park and East Athens."),
            ("Georgia Square", "Perfect for Georgia Square Mall and surrounding areas."),
            ("Prince Avenue", "Quick delivery to Prince Avenue corridor."),
            ("Alps Road", "Premium services for Alps Road and West Athens."),
            ("East Athens", "Fast delivery to East Athens and Normaltown."),
            ("Oconee Hills", "Perfect for Oconee Hills and surrounding neighborhoods."),
            ("Barnett Shoals", "Quick delivery to Barnett Shoals and east side."),
        ],
        "hero_keyword": "Classic City",
        "services_keywords": "UGA, Athens music, GA college town, Athens events",
    },
    "augusta-ga": {
        "name": "Augusta",
        "state": "GA",
        "state_name": "Georgia",
        "county": "Richmond County",
        "description": "Augusta porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving GA. Get a free quote!",
        "title": "Porta Potty Rental Augusta, GA | Richmond County | Same-Day Delivery",
        "og_title": "Augusta Porta Potty Rentals | Garden City | Same-Day Delivery",
        "og_description": "From Masters Tournament to Augusta construction, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "535 Telfair St",
        "address_zip": "30901",
        "theme_color": "#3b82f6",
        "brand_50": "#eff6ff",
        "brand_100": "#dbeafe",
        "brand_300": "#93c5fd",
        "brand_500": "#3b82f6",
        "brand_600": "#2563eb",
        "brand_700": "#1d4ed8",
        "brand_800": "#1e40af",
        "brand_900": "#1e3a8a",
        "areas": [
            ("Downtown Augusta", "Perfect for Augusta Canal and Riverwalk events."),
            ("Summerville", "Quick delivery to Summerville neighborhood."),
            ("North Augusta", "Premium sanitation for North Augusta and SC side."),
            ("Aiken", "Fast delivery to Aiken and Horse District."),
            ("West Augusta", "Perfect for West Augusta and I-20 corridor."),
            ("South Augusta", "Quick delivery to South Augusta and Lake Greenwood."),
            ("Riverwood", "Premium services for Riverwood and National Hills."),
            ("Belair", "Fast delivery to Belair and Augusta West."),
            ("Martinez", "Perfect for Martinez and Columbia County."),
            ("Evans", "Quick delivery to Evans and Grovetown."),
        ],
        "hero_keyword": "Garden City",
        "services_keywords": "Masters Tournament, GA golf, Augusta construction, Augusta events",
    },
    "decatur-ga": {
        "name": "Decatur",
        "state": "GA",
        "state_name": "Georgia",
        "county": "DeKalb County",
        "description": "Decatur porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving GA. Get a free quote!",
        "title": "Porta Potty Rental Decatur, GA | DeKalb County | Same-Day Delivery",
        "og_title": "Decatur Porta Potty Rentals | ATL Metro | Same-Day Delivery",
        "og_description": "From Emory to Decatur square events, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "123 E Ponce de Leon Ave",
        "address_zip": "30030",
        "theme_color": "#3b82f6",
        "brand_50": "#eff6ff",
        "brand_100": "#dbeafe",
        "brand_300": "#93c5fd",
        "brand_500": "#3b82f6",
        "brand_600": "#2563eb",
        "brand_700": "#1d4ed8",
        "brand_800": "#1e40af",
        "brand_900": "#1e3a8a",
        "areas": [
            ("Downtown Decatur", "Perfect for Decatur Square and Emory Village."),
            ("Emory", "Quick delivery to Emory University and CDC."),
            ("Oakhurst", "Premium sanitation for Oakhurst neighborhood."),
            ("Lake Claire", "Fast delivery to Lake Claire and Edgewood."),
            ("Kirkwood", "Perfect for Kirkwood and East Lake neighborhoods."),
            ("Avondale Estates", "Quick delivery to Avondale Estates and Scottdale."),
            ("Candler Park", "Premium services for Candler Park and Inman Park."),
            ("Druid Hills", "Fast delivery to Druid Hills and Emory Village."),
            ("North Decatur", "Perfect for North Decatur and Medlock."),
            ("Glenwood", "Quick delivery to Glenwood and Gresham."),
        ],
        "hero_keyword": "ATL Metro",
        "services_keywords": "Emory, Decatur Square, GA college, Decatur events",
    },
    "macon-ga": {
        "name": "Macon",
        "state": "GA",
        "state_name": "Georgia",
        "county": "Bibb County",
        "description": "Macon porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving GA. Get a free quote!",
        "title": "Porta Potty Rental Macon, GA | Bibb County | Same-Day Delivery",
        "og_title": "Macon Porta Potty Rentals | Cherry Blossom City | Same-Day Delivery",
        "og_description": "From Cherry Blossom Festival to Macon construction, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "456 Cherry St",
        "address_zip": "31201",
        "theme_color": "#3b82f6",
        "brand_50": "#eff6ff",
        "brand_100": "#dbeafe",
        "brand_300": "#93c5fd",
        "brand_500": "#3b82f6",
        "brand_600": "#2563eb",
        "brand_700": "#1d4ed8",
        "brand_800": "#1e40af",
        "brand_900": "#1e3a8a",
        "areas": [
            ("Downtown Macon", "Perfect for Cherry Blossom Trail and Ocmulgee Mounds."),
            ("Ingleside", "Quick delivery to Ingleside and Vesta Terrace."),
            ("Villages at", "Premium sanitation for The Villages at Macon."),
            ("East Macon", "Fast delivery to East Macon and Shurling."),
            ("Warner Robins", "Perfect for Warner Robins and Houston County."),
            ("Milledgeville", "Quick delivery to Milledgeville and Baldwin County."),
            ("Bolingbroke", "Premium services for Bolingbroke and surrounding areas."),
            ("Juliette", "Fast delivery to Juliette and Ocmulgee region."),
            ("Ocmulgee", "Perfect for Ocmulgee National Monument and parks."),
            ("Talmage", "Quick delivery to Talmage and Lizella."),
        ],
        "hero_keyword": "Cherry Blossom City",
        "services_keywords": "Cherry Blossom, Macon music, GA construction, Macon events",
    },
    "savannah-ga": {
        "name": "Savannah",
        "state": "GA",
        "state_name": "Georgia",
        "county": "Chatham County",
        "description": "Savannah porta potty rentals - fast delivery, affordable rates. Standard, deluxe, luxury trailers & ADA units. Serving GA. Get a free quote!",
        "title": "Porta Potty Rental Savannah, GA | Chatham County | Same-Day Delivery",
        "og_title": "Savannah Porta Potty Rentals | Hostess City | Same-Day Delivery",
        "og_description": "From Savannah squares to Tybee Island, we provide porta potty rentals. Fast delivery, clean units, affordable rates.",
        "address_street": "2 E Bryan St",
        "address_zip": "31401",
        "theme_color": "#3b82f6",
        "brand_50": "#eff6ff",
        "brand_100": "#dbeafe",
        "brand_300": "#93c5fd",
        "brand_500": "#3b82f6",
        "brand_600": "#2563eb",
        "brand_700": "#1d4ed8",
        "brand_800": "#1e40af",
        "brand_900": "#1e3a8a",
        "areas": [
            ("Historic District", "Perfect for Savannah squares and River Street."),
            ("Savannah Victorian", "Quick delivery to Victorian District."),
            ("Starland", "Premium sanitation for Starland District arts."),
            ("Thomas Square", "Fast delivery to Thomas Square and Habersham Hills."),
            ("Ardsley Park", "Perfect for Ardsley Park and Habersham Village."),
            ("Wilmington Island", "Quick delivery to Wilmington Island and Talahi."),
            ("Tybee Island", "Premium services for Tybee Beach and events."),
            ("Southside", "Fast delivery to Southside Savannah."),
            ("Pooler", "Perfect for Pooler and West Chatham."),
            ("Garden City", "Quick delivery to Garden City and Port Wentworth."),
        ],
        "hero_keyword": "Hostess City",
        "services_keywords": "Savannah squares, Tybee Island, GA coast, Savannah events",
    },
}

def build_areas_html(areas):
    html = ""
    for name, desc in areas:
        html += f'''
                        <div class="p-4 bg-gray-50 rounded-lg border border-gray-200">
                            <h5 class="font-semibold text-gray-800 mb-1">{name}</h5>
                            <p class="text-sm text-gray-600">{desc}</p>
                        </div>'''
    return html

def regenerate_city_page(city_slug: str, city_data: dict) -> str:
    with open(TEMPLATE_PATH, "r", encoding="utf-8") as f:
        html = f.read()
    
    replacements = [
        ("Atlanta", city_data["name"]),
        ("Georgia", city_data["state_name"]),
        ("Fulton County", city_data["county"]),
        (f"porta-potty-rental-atlanta-ga", f"porta-potty-rental-{city_slug}"),
        (city_data["description"], city_data["description"]),
        (f"<title>Porta Potty Rental Atlanta, GA | Fulton County</title>", f"<title>{city_data['title']}</title>"),
        ("Atlanta Porta Potty Rentals", city_data["og_title"].replace(" | Same-Day Delivery", "")),
        (f'<meta property="og:description" content="From Mercedes-Benz Stadium to Buckhead weddings', f'<meta property="og:description" content="{city_data["og_description"]}'),
        ("Atlanta Sanitation Solutions", f"{city_data['name']} Sanitation Solutions"),
        ("100 Peachtree St NW", city_data["address_street"]),
        ('"Atlanta"', f'"{city_data["name"]}"'),
        ('"30303"', f'"{city_data["address_zip"]}"'),
        ("33.7537;-84..99", f"0;0"),
        (f'"{city_data["theme_color"]}', f'"{city_data["theme_color"]}'),
        ("Mercedes-Benz Stadium, Braves games", city_data["services_keywords"]),
        ("Peach State", city_data["hero_keyword"]),
        ("Buckhead", city_data["areas"][0][0]),
        ("Peachtree Corners", city_data["areas"][1][0]),
        ("Alpharetta", city_data["areas"][2][0]),
        ("Smyrna", city_data["areas"][3][0]),
        ("Marietta", city_data["areas"][4][0]),
        ("Roswell", city_data["areas"][5][0]),
        ("Sandy Springs", city_data["areas"][6][0]),
        ("Decatur", city_data["areas"][7][0]),
        ("College Park", city_data["areas"][8][0]),
        ("East Point", city_data["areas"][9][0]),
    ]
    
    for old, new in replacements:
        if old in html:
            html = html.replace(old, new)
    
    html = re.sub(r'<meta name="description" content="[^"]*">', f'<meta name="description" content="{city_data["description"]}">', html)
    html = re.sub(r'<title>[^<]*</title>', f"<title>{city_data['title']}</title>", html)
    html = re.sub(r'<meta property="og:title" content="[^"]*">', f'<meta property="og:title" content="{city_data["og_title"]}">', html)
    html = re.sub(r'<meta property="og:description" content="[^"]*">', f'<meta property="og:description" content="{city_data["og_description"]}">', html)
    html = re.sub(r'#\w{6}', city_data["theme_color"], html, count=1)
    
    areas_html = build_areas_html(city_data["areas"])
    html = re.sub(
        r'<div class="grid sm:grid-cols-2 gap-4 mt-4">.*?</div>\s*(?=<h4|</section)',
        f'<div class="grid sm:grid-cols-2 gap-4 mt-4">{areas_html}</div>',
        html,
        flags=re.DOTALL
    )
    
    html = re.sub(
        r'(<section id="areas"[^>]*>.*?<h2[^>]*>)[^<]*Proudly Serving[^<]*',
        rf'\1Proudly Serving {city_data["name"]} and All of {city_data["county"]}',
        html,
        flags=re.DOTALL
    )
    
    html = re.sub(r'<h4 class="font-bold text-brand-800 mb-3">Neighborhoods We Serve[^<]*', f'<h4 class="font-bold text-brand-800 mb-3">Neighborhoods We Serve in {city_data["name"]}:', html)
    
    return html

def main():
    if not TEMPLATE_PATH.exists():
        print(f"Template not found: {TEMPLATE_PATH}")
        return
    
    fixed = 0
    for city_slug, city_data in CITY_DATA.items():
        print(f"Regenerating {city_slug}...")
        html = regenerate_city_page(city_slug, city_data)
        
        output_path = Path(f"porta-potty-rental-{city_slug}/index.html")
        if output_path.exists():
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(html)
            print(f"  Done: {city_slug}")
            fixed += 1
        else:
            print(f"  Skip: {city_slug} (not found)")
    
    print(f"\nTotal regenerated: {fixed}")

if __name__ == "__main__":
    main()
